TRaSH-Guides/Guides

Radarr/Collection-of-Custom-Formats-for-Radarr.md

The image for x264 regex was correct but the text was missing a period.

Fix x264 regex

---

docs/Sonarr/V3/Sonarr-Release-Profile-RegEx.md

By making the release quality type (i.e.: webdl/rip) part of a non-capturing group, renames with {Preferred Words} won't overlap with {Quality Title} (e.g.: WEB-DL won't occur twice).

Add non-capturing groups to Sonarr Release Source regex

---

docs/Sonarr/V3/Sonarr-Release-Profile-RegEx.md
docs/Sonarr/V3/Sonarr-recommended-naming-scheme.md

```yml
Updated: Sonarr Release Profile RegEx (WEB-DL)
- Added: APTV to the AppleTV Streaming Service Regex
```
thnx to @MrRehan#2948 for reporting
```yml
Updated: Sonarr Recommended naming scheme
- Removed: Brackets for {[MediaInfo AudioLanguages]} to {MediaInfo AudioLanguages} being it's get added by default
```
thnx to @DarkKnight#2447  for reporting

Maintenance release 20210108

---

docs/Misc/how-to-set-up-hardlinks-and-atomic-moves.md
docs/Radarr/V3/Collection-of-Custom-Formats-for-RadarrV3.md
docs/Radarr/V3/Radarr-recommended-naming-scheme.md
docs/index.md

```yml
Updated: Collection of Custom Formats for Radarr V3
- Fixed: FraMeSToR Custom Format so it scores correctly and doesn't get double counted
- Renamed: HDR (FraMeSToR) to  HDR (indeterminate), to be consistent and feature proof
- Changed: Anime-Dual Audio to recornized dual audio better+other fixes
```
thnx to @jyggen#1337 for the help with the `HDR (indeterminate)`
```yml
Updated: Radarr Recommended naming scheme
- Added: info to add {MediaInfo AudioLanguages} token if you do anime
- Added: info about Radarr now supports iMDb ID and TMDb ID in the folder name.
```
thnx to @DarkKnight#2447  for reporting `{MediaInfo AudioLanguages}` token if you do anime
```yml
Updated: How To Set Up Hardlinks and Atomic-Moves
- Changed: order of the synology warning
```

Maintanance release 20210110

---

docs/Sonarr/V3/Sonarr-recommended-naming-scheme.md

- Changed: {[Mediainfo AudioCodec}{ Mediainfo AudioChannels]} -> [{Mediainfo AudioCodec} { Mediainfo AudioChannels}] to correct for a bug.
- Why: To match the Sonarr - Release Profile RegEx (Anime).

Updated: Sonarr - Release Profile RegEx (WEB-DL)

---

docs/Misc/x265-4k.md
docs/Radarr/V3/Radarr-collection-of-custom-formats.md
docs/Sonarr/V3/Sonarr-Release-Profile-RegEx.md

```yml
Updated: Misc - x265-4k
- Changed: Golden Rule Formatting
- Changed: redirect from old URL link to new URL link for Radarr-collection-of-custom-formats
- Changed: Golden Rule Formatting
- Changed: Golden Rule Formatting
```

Golden rule formatting fix

---

docs/Sonarr/V3/Sonarr-Quality-Settings-File-Size.md

```yml
- Changed: HDTV-720p lowered from 17.9 to 15 (for Riverdale and This is Us episodes)
- Changed: Bluray-720p lowered from 34.9 to 25 (for South Park episodes)
```

Updated: Sonarr - Quality Settings (File Size)

---

docs/Sonarr/V3/Sonarr-Release-Profile-RegEx-Anime.md

- [Added] M2TS/BDMV into Must Not Contain to block Blu-Ray fullrips from being downloaded.

Added a filter

---

docs/Radarr/V3/Radarr-Quality-Settings-File-Size.md
docs/Radarr/V3/Radarr-collection-of-custom-formats.md

```yml
Updated: Radarr - Quality Settings (File Size)
- Changed: Lowered Remux-1080p minimum from [170.8](10/15/20GB) to [136.8](8/12/16GB)
- Fixed: 3D - Solved issue with recornizing 3D in obfuscated file names + cleanup regex
```

Maintenance release 20210327

---

docs/Radarr/V3/Radarr-collection-of-custom-formats.md

```yml
- Updated: DoVi - Fixed+Cleaned Regex for better recognizing.
- Updated: Dolby Vision (Single Layer) - Fixed+Cleaned Regex for better recognizing.
- Added: Dolby Vision (no WEB-DL) - This is a special Custom Format that ignores DV for WEB-DL but allows for other sources. WEB-DL from Streaming Services don't have the fallback to HDR(10), What can results in weird playback issues like weird colors if you want to play it on a not DoVi compatible setup. Remuxes and Bluray have a fallback to HDR(10).
```

Updated: Radarr - Collection of Custom Formats - DoVi Fix + NoWEBDL

---

docs/Radarr/V3/Radarr-collection-of-custom-formats.md

Updates the Not DTS-HD regex to match against DTS-HD HRA, stops releases with DTS-HD HRA from being matched against both DTS and DTS-HD HRA custom formats.

Update Basic DTS / Not DTS-HD regex

---

docs/Sonarr/V3/Sonarr-Release-Profile-RegEx.md

```yml
- Added: Optional Ignore DoVi for WEBDL - This is a RegEx that ignores DV for WEB-DL but allows for other sources. WEB-DL from Streaming Services don't have the fallback to HDR(10), What can results in weird playback issues like weird colors if you want to play it on a not DoVi compatible setup. Remuxes and Bluray have a fallback to HDR(10).
```

Added: Optional Ignore DoVi for WEBDL

---

docs/Sonarr/V3/Sonarr-Quality-Settings-File-Size.md
docs/Sonarr/V3/Sonarr-Release-Profile-RegEx.md

```yml
- Updated: Optional Ignore DoVi for WEBDL - Fixed recornizing DoVi after WEB-DL
Updated: Sonarr - Quality Settings (File Size)
- WEBDL-720p + WEBRip-720p lowered from 15 to 10 (for The Lost Pirate Kingdom)
- WEBDL-1080p + WEBRip-1080p lowered from 22 to 15 (for The Lost Pirate Kingdom)
- WEBDL-2160p + WEBRip-2160p + HDTV-2160p lowered from 84.5 to 69.1 (for Wanda Vision)
```

Sonarr patch210403

---

docs/Radarr/V3/Radarr-collection-of-custom-formats.md

```yml
- Updated: DD - Theres a release group called DDP that seems to match itself against the dolby digital plus custom format.
- Updated: BR-DISK - Added MPEG-2 recornizing, Better x265/hevc recornizing
- Added: No-RlsGroup - Some indexers strip out the release group what could result in LQ groups getting a higher score.
```

Radarr cf collection patch20210411

---

docs/Radarr/V3/Radarr-collection-of-custom-formats.md

```yml
- Updated: x265 (720/1080p) - Better x265/hevc recornizing, Added Quality Group Exeptions
- Fixed: Formatting
- Updated: HDR (undefined) - Fixed stop match if detects DoVi in release title. (Double Scoring)
```

Radarr cf collection patch20210411 2100

---

docs/Hardlinks/How-to-setup-for/Dockstarter.md

```yml
Updated: Hardlinks - How-to-setup-for - Dockstarter
- Fixed: direct links to examples
```

Fixed: direct links to examples

---

.github/workflows/deploy.yml
.github/workflows/lint.yml
docs/requirements.txt

This will trigger a number of dependabot pull requests that will need to be merged.
Going forward, version changes should  be handled by dependabot PRs, and it should be more obvious when they happen.
Currently in the requirements.txt file where `>=` is used, any version of the dependency that is greater than or equal to the specified version can be used and dependabot does not make PRs to bump those versions. The desired behavior is to use an exact version with `==` and let dependabot PR new versions. This also makes rollback easier when an issue occurs (see note below about upcoming mkdocs version bump).
UPCOMING MKDOCS VERSION BUMP:
Version 1.2 of mkdocs seems to have an issue with pushing to the `gh-pages` branch. When dependabot creates the PR for this update, I would advise to not …

Let dependabot handle versioning

---

docs/Bazarr/Setup-Guide.md

Clean up of Base URL section. Emphasis on instances where a Base URL is needed, and where it isn't. Also a typo fix. trough to through.

Bazarr Base URL step adjustment

---

docs/json/radarr/hq.json

- FIXED: [HQ] - Ignores REMUX so you don't get double scoring from [HQ-Remux]

FIXED: [HQ] - Ignores REMUX so you don't get double scoring from [HQ-Remux]

---

docs/Sonarr/Sonarr-Release-Profile-RegEx-Anime.md

Fixes the anime profile regex to match the `Anime Time` release group when the space is replaced by a period: `Anime.Time`

Fix anime regex to match `Anime.Time`

---

docs/json/radarr/dd-atmos.json
docs/json/radarr/dolby-digital-plus.json

Updated: [DD+ Atmos]
- Added: Support for DDPA recognizing
Updated: [DD+]
- Fixed: So it doesn't recognize DDPA

Radarr CF DDPA

---

docs/Radarr/Radarr-Quality-Settings-File-Size.md

- Changed: Lowered WEBDL/RIP 1080p Quality Size because of more and more NF 1080p are getting over compressed.

Changed: Lowered WEBDL/RIP 1080p Quality Size

---

docs/Bazarr/index.md
docs/Radarr/index.md
docs/Sonarr/index.md

- Changed: GitHub Container Registry to Docker Hub until further notice

Changed: GitHub Container Registry to Docker Hub until further notice

---

docs/Hardlinks/How-to-setup-for/Synology.md

1. When 2 commands were in a bash, it copied both of them. This doesn't work well when pasting in terminal apps.
2. Some textual edits.

fixes on bash commands

---

docs/json/radarr/4k-remaster.json
docs/json/radarr/atmos-undefined.json
docs/json/radarr/criterion-collection.json
docs/json/radarr/hdr-undefined.json
docs/json/radarr/hdr.json
docs/json/radarr/truehd-atmos.json
docs/json/radarr/truehd.json

- Updated: CF `[4K Remaster]` Scores to the new scoring standard.
- Updated: CF `[Criterion Collection]` Scores to the new scoring standard.
- Fixed: CF `[TrueHD Atmos]` to recognize groups that only use Atmos/TrueHD in their release name.
- Fixed: CF `[ATMOS (undefined)]` to prevent double scoring with latest update of `[TrueHD Atmos]`.
- Fixed: CF `[TrueHD]` to prevent double scoring with latest update of `[TrueHD Atmos]`.
- Changed: CF `[HDR]` `[HDR (undefined)]`condition name.

Cf update 20220116

---

docs/Sonarr/Sonarr-Release-Profile-RegEx.md

Add Remux into the list of sources to pull DoVi. Found these GOT examples of DV BluRay remuxes.
.

add Remux to DoVi

---

docs/Sonarr/Sonarr-Release-Profile-RegEx.md
docs/json/radarr/truehd-atmos.json
docs/json/radarr/truehd.json

- Fixed: CF [TrueHD Atmos] to recognize groups that only use Atmos/TrueHD in their release name.
- Fixed: CF [TrueHD] to prevent double scoring with latest update of [TrueHD Atmos].
Updated: Sonarr- Release Profile RegEx (WEB-DL)
- Changed: Scores HBO MAX (hmax|hbom).

Maintenace release 20220121

---

docs/Hardlinks/How-to-setup-for/Synology.md

Use of `sudo` to execute `wget` and `mkdir` is not necessary. These are simple commands that do not require elevated permissions to execute correctly.
Also some minor updates to clarify phrasing.

Updating Synology.md to remove unnecessary usages of `sudo`

---

docs/Radarr/Radarr-setup-custom-formats.md
docs/json/radarr/bhdstudio.json
docs/json/radarr/hq-remux.json
docs/json/radarr/truehd-atmos.json
docs/json/radarr/truehd.json
docs/json/radarr/uhd-hqmux.json
docs/json/radarr/uhd-legi0n.json
docs/json/radarr/uhd-webdv.json
includes/cf/hq-source-group.md
includes/cf/hq4k.md
includes/sqp/1-1-cf-scoring.md
includes/sqp/1-2-cf-scoring.md

Radarr Custom Format Collection 20220127
- Changed: Several CF Scoring for better results.
- Fixed: CF `[TrueHD Atmos]` to recognize groups that only use Atmos/TrueHD in their release name.
- Fixed: CF `[TrueHD]` to prevent double scoring with latest update of `[TrueHD Atmos]`.

Radarr Custom Format Collection 20220127

---

docs/Sonarr/Sonarr-Release-Profile-RegEx.md
docs/json/radarr/2160p.json
docs/json/radarr/dv.json
docs/json/radarr/hdr-undefined.json
docs/json/radarr/hdr.json
docs/json/radarr/hlg.json
docs/json/radarr/pq.json

This allows different DV custom format to deal with badly named DV files

Fix for badly named (dolbyvision) DV files

---

docs/json/radarr/lq.json
docs/json/radarr/obfuscated.json

- Updated: CF [LQ] added `Liber8` to the `Nominated Unwanted Groups` condition.
- Updated: CF [Obfuscated] added `_nzb` to the `Retagged`condition.

Radarr cf collection 20220211

---

docs/json/radarr/lq.json

Added: `FZHD` to the `Nominated Unwanted Groups` condition.
- Bad Naming
- Wrong and Incorrect Info
- Often Playback issues Audio/Video
- Fake 4K (Re Grade/Upscaled)

Radarr CF LQ FZHD

---

docs/Sonarr/Sonarr-Release-Profile-RegEx.md

Hi @TRaSH- !
This one fixes badly named DV release withotu HDR fallback, for example this one : `Slow.Horses.S01E06.MULTI.DOLBYVISION.2160p.ATVP.WEB-DL.DDP5.1.Atmos.HEVC-AXLBEN.mp4`
Thanks!

Fix DoVi without HDR fallback for badly named releases

---

docs/Sonarr/Sonarr-Release-Profile-RegEx.md

Fixed word boundary by removing escaping introduced in #574 by me.
Sorry about that.

Fix regex word boundary

---

docs/json/radarr/lq.json
docs/updates.txt

- Updated: CF [LQ] added `KIRA` to the `Nominated Unwanted Groups` condition. (Wrong main Audio Track in filename)

Radarr CF [LQ] KIRA

---

docs/json/radarr/no-rlsgroup.json

Added the group de[42] to be excluded from the No -RlsGroup CF

Updated: de[42] to be excluded from No -Rlsgroup

---

docs/Sonarr/Sonarr-Release-Profile-RegEx.md
docs/json/sonarr/lqGroups.json
docs/updates.txt

- Added: Pahe.ph|Pahe.in to the LQ Groups because of their re-encoded microsized releases.

Sonarr Low Quality Groups - Release Profile

---

docs/json/radarr/lq.json

- Updated: CF [LQ] added `PTNK` to the `Nominated Unwanted Groups` condition. (Using different sources like EVO releases, BLUR hardcoded subs,  and also strips out all other subs)

Radarr CF [LQ] PTNK

---

docs/Misc/trash-sync.md

- Updated: Rebranding trash-updater to recyclarr v2 (With this update it means i will also drop updates for v1)

Updated Re-branding trash-updater to recyclarr

---

docs/Sonarr/Sonarr-Release-Profile-RegEx.md
docs/json/sonarr/lqGroups.json
docs/json/sonarr/optionals.json

- Added: The group `SIC` to `Optional - Ignore Dolby Vision without HDR10 fallback` exception.
- Added: The group `NERO` to `Low Quality Groups - Release Profile` because they only provide dubbed French audio track.

Sonarr Release Profile Regex WEBDL

---

docs/Hardlinks/How-to-setup-for/Unraid.md
docs/Misc/trash-sync.md

- Added: IBRACORP video link for notifiarr TRaSH-Sync.
- Updated: TRaSH Updater re-branding to Recyclar.

IBRACORP Video Link

---

docs/json/sonarr/v4/normal/dv-hdr10.json
docs/json/sonarr/v4/normal/dv-hlg.json
docs/json/sonarr/v4/normal/dv-sdr.json
docs/json/sonarr/v4/normal/hdr10.json
docs/json/sonarr/v4/normal/hdr10plus.json
docs/json/sonarr/v4/normal/hlg.json
docs/json/sonarr/v4/normal/pq.json

Without them, some HDR releases will result download loops as
the scene name states HDR, but after import it is actually HDR10

Add all HDR metadata CF json files

---

docs/Downloaders/index.md

Change to more reliable release versioning for versions of deluge and rutorrent.
it should be noted that rutorrent is just a front end and the rtorrent version should be used instead.

fix: software versions

---

docs/json/sonarr/v4/normal/dislike-obfuscated.json
docs/json/sonarr/v4/normal/dislike-retags.json
docs/json/sonarr/v4/normal/dislike-scene-releases.json
docs/json/sonarr/v4/normal/hdr-undefined.json

Updated: Sonarr-CF [Dislike Obfuscated] Switched to separate conditions for the groups
- Changed: CF [Dislike Obfuscated] Conditions to separate conditions for the groups.
Updated: Sonarr-CF [Dislike retags] Switched to separate conditions for the groups
- Changed: CF [Dislike retags] Conditions to separate conditions for the groups.
Updated: Sonarr-CF [Dislike scene releases] Switched to separate conditions for the groups
- Changed: CF [Dislike scene releases] Conditions to separate conditions for the groups.
Updated: Sonarr-CF [HDR (undefined)]
- NEW: Added [HDR (undefined)] [Score: 500]

Sonarr cf separated group conditions

---

docs/json/radarr/dv-hdr10.json
docs/json/radarr/dv-hlg.json
docs/json/radarr/dv-sdr.json
docs/json/radarr/dv-webdl.json
docs/json/radarr/dv.json
docs/json/radarr/hdr10.json
docs/json/radarr/hdr10plus.json

- Added: Fix for bad (re)named DV HDR10 releases.
- Added: `Not DV` Condition to `[HDR10]` prevent double scoring for bad (re)named DV HDR10 Releases.

Radarr cf dv hdr10 fix for bad (re)named files

---

docs/json/radarr/imax.json

- Updated: CF `[IMAX]` Raised score from `25` to `800` to match `Imax Enhanced`.

Raised score from `25` to `800` to match `Imax Enhanced`.

---

docs/json/radarr/lq.json

- Removed: EVO from the `[LQ]`, please use `[EVO (NOWEBL)]`

Removed: EVO from the [LQ]

---

docs/Sonarr/Sonarr-Release-Profile-RegEx.md
docs/json/sonarr/optionals.json
docs/json/sonarr/p2pRepackProper.json

- Fixed: Better recognizing of 1080p/x265 in random order.
- Added: GNOME to HQ WEBDL Tier 2 (P2P Groups with a score of 125).
- Added: ABBIE to HQ WEBDL Tier 2 (P2P Groups with a score of 125).

Sonarr RP 20220717

---

docs/json/radarr/ma.json

- Fix: CF `[MA]` false positive, seems in some cases Radarr picks up the path for the CF, and it triggered false on `DTS-HD MA`.

Fix: CF [MA] false positive

---

docs/Downloaders/qBittorrent/Basic-Setup.md

ZFS does not support fallocate[1] which means if the `pre-allocate`
option is set to true qBittorrent will error when adding torrent files
1. https://github.com/openzfs/zfs/issues/326

Add warning to qBittorrent about ZFS/Pre-Allocate

---

docs/Radarr/Radarr-collection-of-custom-formats.md
docs/Sonarr/Sonarr-Release-Profile-RegEx.md
docs/json/radarr/bad-dual-groups.json
docs/json/sonarr/optionals.json
includes/cf/unwanted.md

- Added: [Sonarr] `Optional - Ignore Bad Dual Audio Groups` - These groups take the original release, then they add their own preferred language (ex. Portuguese) as the main audio track (AAC 2.0), What results after renaming and FFprobe that the media file will be recognized as Portuguese AAC audio. It's a common rule that you add the best audio as first.
Also they often even rename the release name in to Portuguese.
- Added: [Radarr] CF `[Bad Dual Groups]` - These groups take the original release, then they add their own preferred language (ex. Portuguese) as the main audio track (AAC 2.0), What results after renaming and FFprobe that the media file will be recognized as Portuguese AAC audio. It's a common rule that you add the best audio as first.
Also they often even rename the release …

Dislike bad dual audio groups

---

docs/Misc/how-to-provide-a-docker-compose.md

- Added: `Notifiarr.com`
- Added: `bpaste`
- Removed: `0bin` because of the issues it's having
- Removed `Ubuntu Pastebin` because you need a account to make use of it.

Updated: Paste sites

---

docs/json/radarr/bad-dual-groups.json
docs/json/radarr/framestor.json
docs/json/radarr/hq-remux.json
docs/json/radarr/uhd-legi0n.json
docs/updates.txt
includes/cf/hq4k.md

- Changed: Raised score for CF `[Framestore]`.
- Added: regex to prevent download loop with bad dual groups. Issue: #685
- Added: `EXTREME` to the CF `[Bad Dual Groups]`. Issue: #694

Radarr CF 20220804

---

docs/json/radarr/lq.json

Updated the `LQ` CF to include a few more groups, sorted and formatted the json as well.
Added `EPiC` to the `LQ` CF to fix #702

Updated: `LQ` CF with new Groups

---

docs/json/radarr/hq-remux.json
docs/json/radarr/hq-webdl.json
docs/json/radarr/hq.json

Added more word boundaries to the `HQ` custom formats to prevent incorrect matching of release groups to fix #710

Fixed: Added word boundaries to `HQ` CFs

---

docs/json/radarr/hd-bluray-tier-01.json
docs/json/radarr/hd-bluray-tier-02.json
docs/json/radarr/remux-tier-01.json
docs/json/radarr/remux-tier-02.json
docs/json/radarr/web-tier-01.json
docs/json/radarr/web-tier-02.json
docs/json/radarr/web-tier-03.json

Added word boundaries for all the tiered CFs to prevent wrongfully matching another release group.

Fixed: Word Boundaries for Tiered CFs

---

docs/Downloaders/SABnzbd/scripts/Clean/Clean.py

Add regex match for -D-Z0N3 in SABnzbd Clean script. This resolves an issue where "-D-Z0N3-xpost" was being shortened to "-D".

Regex match for -D-Z0N3 in Clean script (SABnzbd)

---

docs/json/radarr/cf/dts-es.json
docs/json/radarr/cf/dts-hd-hra.json
docs/json/radarr/cf/dts-hd-ma.json
docs/json/radarr/cf/dts-x.json
docs/json/radarr/cf/dts.json
docs/json/sonarr/cf/dts-es.json
docs/json/sonarr/cf/dts-hd-hra.json
docs/json/sonarr/cf/dts-hd-ma.json
docs/json/sonarr/cf/dts-x.json
docs/json/sonarr/cf/dts.json

**Purpose**
Fix an issue with the recognition of DTS-HD MA when the file was named DTS-XLL
**Approach**
Adjusted the regex to no longer recognize DTS-XLL as DTS-X but rather DTS-HD MA
**Learning**

Fixed: `DTS-X` and `DTS-HD MA` recognition

---

docs/json/radarr/cf/web-tier-01.json
docs/json/radarr/cf/web-tier-02.json
docs/json/radarr/cf/web-tier-03.json

- Decrease WEB Tiers scores by 50 so it doesn't overlap with Bluray Tiers
**Purpose**
Decrease WEB Tier scores by 50 so it doesn't overlap with the Bluray Tiers
**Approach**
N/A
**Learning**

Decrease WEB Tier scores by 50

---

docs/json/radarr/cf/dts-hd-ma.json
docs/json/radarr/cf/dts.json
docs/json/sonarr/cf/dts-hd-ma.json
docs/json/sonarr/cf/dts.json

**Purpose**
Fixed the recognition of `DTS-HD MA` for both the Radarr and Sonarr CFs that use the regex.
**Approach**
Added `hd` to the regex to cover for wrongly named `DTS-HD MA` files
**Learning**

Fixed: `DTS-HD MA` recognition

---

docs/json/radarr/cf/dts-hd-ma.json
docs/json/radarr/cf/dts.json
docs/json/sonarr/cf/dts-hd-ma.json
docs/json/sonarr/cf/dts.json

**Purpose**
Fixed the recognition of `DTS-HD MA` for both the Radarr and Sonarr CFs that use the regex.
**Approach**
Added `hd` to the regex to cover for wrongly named `DTS-HD MA` files
**Learning**

Updated: Change to cleaner regex for `DTS-HD MA`

---

docs/json/radarr/cf/aac.json
docs/json/radarr/cf/atmos-undefined.json
docs/json/radarr/cf/dd.json
docs/json/radarr/cf/ddplus-atmos.json
docs/json/radarr/cf/ddplus.json
docs/json/radarr/cf/dts-es.json
docs/json/radarr/cf/dts-hd-hra.json
docs/json/radarr/cf/dts-hd-ma.json
docs/json/radarr/cf/dts-x.json
docs/json/radarr/cf/dts.json
docs/json/radarr/cf/flac.json
docs/json/radarr/cf/pcm.json
docs/json/radarr/cf/truehd-atmos.json
docs/json/radarr/cf/truehd.json
docs/json/sonarr/cf/aac.json
docs/json/sonarr/cf/atmos-undefined.json
docs/json/sonarr/cf/dd.json
docs/json/sonarr/cf/ddplus-atmos.json
docs/json/sonarr/cf/ddplus.json
docs/json/sonarr/cf/dts-es.json
docs/json/sonarr/cf/dts-hd-hra.json
docs/json/sonarr/cf/dts-hd-ma.json
docs/json/sonarr/cf/dts-x.json
docs/json/sonarr/cf/dts.json
docs/json/sonarr/cf/flac.json
docs/json/sonarr/cf/pcm.json
docs/json/sonarr/cf/truehd-atmos.json
docs/json/sonarr/cf/truehd.json

**Purpose**
Fixed the regex in the all the sound CFs to recognize `E-AC3` correctly.
**Approach**
Added a check for some common spacing characters to the regex for `EAC3`
**Learning**

Fixed: `EAC3` regex in the sound CFs

---

docs/json/radarr/cf/aac.json
docs/json/radarr/cf/atmos-undefined.json
docs/json/radarr/cf/dd.json
docs/json/radarr/cf/ddplus-atmos.json
docs/json/radarr/cf/ddplus.json
docs/json/radarr/cf/dts-es.json
docs/json/radarr/cf/dts-hd-hra.json
docs/json/radarr/cf/dts-hd-ma.json
docs/json/radarr/cf/dts-x.json
docs/json/radarr/cf/dts.json
docs/json/radarr/cf/flac.json
docs/json/radarr/cf/pcm.json
docs/json/radarr/cf/truehd-atmos.json
docs/json/radarr/cf/truehd.json
docs/json/sonarr/cf/aac.json
docs/json/sonarr/cf/atmos-undefined.json
docs/json/sonarr/cf/dd.json
docs/json/sonarr/cf/ddplus-atmos.json
docs/json/sonarr/cf/ddplus.json
docs/json/sonarr/cf/dts-es.json
docs/json/sonarr/cf/dts-hd-hra.json
docs/json/sonarr/cf/dts-hd-ma.json
docs/json/sonarr/cf/dts-x.json
docs/json/sonarr/cf/dts.json
docs/json/sonarr/cf/flac.json
docs/json/sonarr/cf/pcm.json
docs/json/sonarr/cf/truehd-atmos.json
docs/json/sonarr/cf/truehd.json

**Purpose**
Fix the `E-AC3` detection again.
**Approach**
Add word boundaries to the `Dolby Digital Plus` conditions.
**Learning**

Fixed: `E-AC3` detection again

---

docs/json/radarr/cf/ddplus.json
docs/json/sonarr/cf/ddplus.json

**Purpose**
Remove `Basic Dolby Digital` negation from `DD+` CFs
**Approach**
If a release is improperly tagged as DD or DD+ but the file is in fact the opposite, no CF is applied. Removing this negation allows the correct CF to be applied.
**Learning**

DD+ Negation Fix

---

docs/json/radarr/cf/x265-no-hdrdv.json
docs/json/sonarr/cf/x265-no-hdrdv.json

Added: recognizing HDR10(+|Plus)
Added: regex Case
**Purpose**
**Approach**
**Learning**

[Starr] CF [x265 (no HDR/DV)] include HDR10(+|Plus)

---

docs/json/sonarr/cf/hmax.json

Changed: CF `HMAX` hash because it was identical with CF `HLG`
Fixed: typo in redex
**Purpose**
**Approach**
**Learning**

[Sonarr] Change CF HMAX hash + fix

---

docs/Radarr/Radarr-collection-of-custom-formats.md
docs/Radarr/Radarr-setup-custom-formats.md
docs/Sonarr/sonarr-collection-of-custom-formats.md
docs/Sonarr/sonarr-setup-custom-formats.md
includes/cf/radarr-misc.md
includes/cf/sonarr-misc.md
includes/merge-quality/radarr-current-logic.md

- Changed: link repack-proper to repackproper to be consistent with `/` being removed by markdown

[Backend] consistent naming across CF

---

docs/json/radarr/cf/flights-no-imax.json
includes/sqp/1-2-cf-scoring.md

- Lowered Score to `0` because it will be removed upcoming weekend, and it's already added to CF `[HQ-Remux]` and `[Remux Tier 02]`

Radarr CF `[Flights (no IMAX)`

---

docs/Sonarr/sonarr-collection-of-custom-formats.md

**Purpose**
Updating the collection of custom formats for Sonarr as I missed dubs only in the Anime optional section
**Approach**
**Learning**

Missed dubs only in the anime tables

---

docs/json/sonarr/cf/anime-lq-groups.json
docs/json/sonarr/cf/dubs-only.json

**Purpose**
Moving Yameii from Anime LQ to Dubs Only for Sonarr CFs
**Approach**
**Learning**

Moving Yameii from Anime LQ to Dubs Only for Sonarr CFs

---

docs/Radarr/Radarr-recommended-naming-scheme.md
docs/Sonarr/Sonarr-recommended-naming-scheme.md

- Removed: Sonarr `{[MediaInfo VideoDynamicRangeType]}` version warning.
- Removed: Radarr `{[MediaInfo VideoDynamicRangeType]}` version warning.
- Removed: link to imdb support for plex.

[Guide] Removed `{[MediaInfo VideoDynamicRangeType]}` version warning

---

docs/requirements.txt

Revert "build(deps): bump mkdocs-include-markdown-plugin from 3.8.0 to 3.9.0"

---

docs/json/radarr/cf/imax.json

**Purpose**
Get rid of the double naming for the IMAX CF.
**Approach**
Remove the CF naming for IMAX to get rid of the double naming.

Fixed: Double IMAX in the file name

---

docs/json/radarr/cf/dts-hd-ma.json
docs/json/sonarr/cf/dts-hd-ma.json

**Purpose**
Similar to #781 
With a release tagged as DTS but detected on import as DTS-HD MA, no CFs will be applied to the file on disk because of the Basic DTS negation. This results in a grab/upgrade loop.
**Approach**
Remove Basic DTS negation. The DTS CF will handle this negation to ensure both are not applied.
**Learning**

DTS-HD MA: Remove Basic DTS negation

---

docs/json/sonarr/cf/web-tier-01.json

**Purpose**
`HONE` and `CRFW` release `DV HDR` hybrids of various shows.
**Approach**
Adding `HONE` and `CRFW` to `WEB Tier 01`.

Added: `HONE` and `CRFW` to `WEB Tier 01`

---

docs/Plex/.pages
docs/Plex/Tips/.pages
docs/Plex/Tips/4k-transcoding.md
docs/Plex/profiles/index.md

- Moved: Tips above profiles.
- Fixed: copy/paste option.
- Fixed: Formatting for profiles page.
- Added: warning for untested on new Shield/Chromecast models.

Plex: cleanup

---

docs/json/radarr/cf/special-edition.json
docs/json/radarr/quality-size/sqp-streaming.json
docs/updates.txt
includes/sqp/1-cf-scoring.md
includes/sqp/hd-radarr-optional.md
includes/sqp/uhd-radarr-unwanted.md

**[SQP-1]**
- Removed: un-needed optional.
**[Radarr]**
- Updated: CF `[Special Edition]` Score from `25` to `125`.
**[SQP-2-5]**
- Add: correct link for CF `[SDR]`.

[Guide] Maintenance Release 20221107

---

docs/json/sonarr/cf/anime-raws.json

**Purpose**
add Lilith-Raws to anime-raws.json
**Approach**
This change is to add an additional raws group to the anime-raws.json to avoid pulling an additional group releasing raws. 
https://regex101.com/r/k2Xmal/1

add Lilith-Raws to anime-raws.json

---

docs/Radarr/Radarr-collection-of-custom-formats.md

**Purpose**
To fix incorrect json for AV1 on Radarr Collection of Custom Formats guide page
**Approach**
Removed incorrect Sonarr Scene json, added correct Radarr AV1 json
**Learning**

Correct incorrect AV1 json

---

docs/Sonarr/sonarr-collection-of-custom-formats.md
docs/json/sonarr/cf/nlz.json
docs/json/sonarr/cf/vdl.json
docs/json/sonarr/cf/web-tier-03.json
docs/json/sonarr/rp/lqGroups.json
docs/json/sonarr/rp/optionals.json
docs/json/sonarr/rp/p2pRepackProper.json
docs/json/sonarr/rp/streaming.json

**[Sonarr]**
- Added: Videoland + NLZIET streaming services
- Added: RlsGrp `SwAgLaNdEr` This is a group that's on the BTN list and does Dutch TV shows from different Dutch Streaming Services.
- Added: RlsGrp `CRFW`, `SDCC`, `SLiGNOME`, `T4H`.
- Added: RlsGrp `HONE` known for their hybrid 4k releases.
- Updated: Scores to be consistent with Radarr/Sonarr.
- Updated: Scores to be consistent with Radarr/Sonarr.

Sonarr maintenance release

---

docs/json/radarr/cf/anime-raws.json
docs/json/sonarr/cf/anime-raws.json

**Purpose**
to add NanakoRaws and Lilith-Raws to anime-raws for radarr and to add NanakoRaws to sonarr anime-raws
**Approach**
This will prevent NanakoRaws from being acidentially grabbed
https://regex101.com/r/kEwblA/1
**Learning**

added NanakoRaws and Lilith-Raws to anime-raws

---

docs/SQP/yml/sqp-1.yml

Comment out lines relating to the HD Bluray tiers, and add extra comments to advise users to explicitly uncomment this section if they want to enable these. Also a small clarification for the IMAX section to refer to multiple lines.
**Purpose**
To set the HD Bluray Tiers as optional in the SQP1 yml
**Approach**
The guide shows these CFs as optional, so this brings the yml in line.
**Learning**

Set HD Bluray Tiers as Optional in SQP1 yml

---

docs/Sonarr/Sonarr-recommended-naming-scheme.md
docs/updates.txt

- Sonarr V4 - Is now using Custom Formats instead of Release Profiles. Use the the new naming scheme instead.

[Sonarr v4] Added naming scheme

---

docs/json/radarr/cf/2160p.json
docs/json/radarr/cf/sdr.json
docs/json/sonarr/cf/2160p.json
docs/json/sonarr/cf/sdr.json

**Purpose**
Change 2160p CFs to oneliners, update SDR with negated HDR formats
**Approach**
2160p now properly only matches HDR formats, and SDR correctly excludes HDR formats
**Learning**

Update 2160p CFs (Radarr/Sonarr) and SDR CF (Radarr)

---

docs/Radarr/radarr-setup-quality-profiles-french-fr.md
docs/json/radarr/cf/french-vfq.json
includes/french-guide/radarr-french-advanced-audio-information-fr.md

**Purpose**
Corrected some French wording and grammar.
Corrected VFQ format to not recognise FRENCH alone. It needs now MULTi in front of it (but will not recognise the Multi-French format) so it should leave alone the French original movies.
This is still not bulletproof but should lead to less false positives.
**Learning**

[Radarr] Update Radarr french cf

---

docs/json/radarr/naming/radarr-naming.json
docs/json/sonarr/naming/sonarr-naming.json
metadata.json
metadata.schema.json

- This is part 1 to move the naming scheme to a json file so 3rd party apps can make use of it. (in part 2 it will be also used in the Guide it self)

[Guide] Move naming scheme to json part1

---

docs/json/radarr/cf/sdr.json
docs/json/sonarr/cf/sdr.json

**Purpose**
Updated SDR CFs to include SICFoI. This PR addresses issue #1032 
**Learning**

feat(sdr) - update SDR CFs

---

docs/SQP/yml/sqp-4.yml
docs/SQP/yml/sqp-5.yml

**Purpose**
To remove erroneous DV FEL CF entries from SQP 4+5 recyclarr yml files
**Approach**
Removed the CFs
**Learning**

Remove unnecessary DV FEL CF in SQP 4+5 recyclarr yml files

---

docs/json/sonarr/cf/french-anime-fansub.json
docs/json/sonarr/cf/french-canal.json
docs/json/sonarr/cf/french-rtbf.json
docs/json/sonarr/cf/french-salto.json
docs/json/sonarr/cf/french-web-tier-01.json
docs/json/sonarr/cf/french-web-tier-02.json
docs/json/sonarr/cf/french-web-tier-03.json

**Purpose**
Sonarr: `FR Anime FanSub` had the same ID and name as `FR WEB Tier 01`
French WEBDL and WEBRIP had Radarr CF values (7and 8)
**Approach**
Name changed and new hash code generated with contribution directives.
I changed the value of WEBDL and WEBRIP to 3 and 4 and now they correspond to the right values.
**Learning**

Sonarr FR -  Update CF errors

---

docs/json/radarr/cf/lq.json
docs/json/radarr/cf/uhd-bluray-tier-03.json

- Moved: RlsGrp `BiTOR` from `UHD Bluray Tier 3` to `LQ`. Reason: Fake DV Layer: HDR10+ conversion.

[Radarr] Removed: `BiTOR`

---

.github/dependabot.yml
.github/workflows/deploy.yml
.github/workflows/lint.yml
.github/workflows/metadata-validation.yml

**Purpose**
Using the full semver (ex: `v3.0.0` instead of `v3`) allows dependabot to open PRs to update to `v3.0.1` instead of waiting for `v4`
Also switch dependabot from `daily` to `weekly` to reduce the work it has to do.
**Approach**
Add `.0.0` to the end of all GitHub Actions. This will result in multiple follow up PRs from @dependabot to get caught up.

Use full semver for GHA

---

docs/SQP/yml/sqp-1.yml
docs/SQP/yml/sqp-2.yml
docs/SQP/yml/sqp-3.yml
docs/SQP/yml/sqp-4.yml
docs/SQP/yml/sqp-5.yml

**Purpose**
When running recyclarr in configs mode (i.e., using multiple config files from the configs folder), if `delete_old_custom_formats` is enabled in a config file then specified CFs can potentially be deleted. This is because each file is processed in turn, and if there are CFs loaded by any of your preceeding files and not the last one then any CFs that are called in the last file can be deleted as they're seen as 'old' CFs.
**Approach**
Removed `delete_old_custom_formats` from all SQP config files. Have also specified radarr instance names for better identification when running.
**Learning**
If you're adding a new Custom Format make sure you follow the [Radarr/Sonarr Custom Format (JSON) …

Update SQP YMLs to fix issue with CF deletions

---

docs/json/radarr/cf/lq.json

**Purpose**
Add CREATiVE24 to Low Quality
Poorly named releases including
"DTSHD-MA" as PCM
WEBDLs as m2ts
**Approach**
add to LQ
**Learning**
Closes #1069

Radarr - Add CREATiVE24 to Low Quality

---

docs/json/radarr/cf/dv-hdr10.json
docs/json/radarr/cf/dv-hlg.json
docs/json/radarr/cf/dv-sdr.json
docs/json/radarr/cf/dv.json
docs/json/radarr/cf/hdr10.json
docs/json/radarr/cf/hdr10plus-boost.json
docs/json/radarr/cf/hdr10plus.json
docs/json/sonarr/cf/dv-hdr10.json
docs/json/sonarr/cf/dv-hlg.json
docs/json/sonarr/cf/dv-sdr.json
docs/json/sonarr/cf/dv.json
docs/json/sonarr/cf/hdr10.json
docs/json/sonarr/cf/hdr10plus-boost.json
docs/json/sonarr/cf/hdr10plus.json

**Purpose**
The "DV HDR10" currently matches with "DV.HDR10" and "DV.HDR10+", but not "DV.HDR10Plus". This is to update the CF to be consistent and only match with "DV.HDR10"
**Approach**
This is the current regex https://regex101.com/r/YQXE5R/1
This is the new regex https://regex101.com/r/KQO62Q/1
It only matches "DV.HDR10"
**Learning**

exclude hdr10+ from DV HDR10 CF

---

docs/Sonarr/Sonarr-Quality-Settings-File-Size.md

Add the preferred quality note from the Radarr page (amended to say Sonarr)
**Purpose**
User had a question in Discord about the preferred sizes for Sonarr, noticed that this note wasn't on the Sonarr page.
**Approach**
Copy the note panel from the Radarr page, change name to Sonarr
**Learning**

Add preferred quality note to Sonarr filesize page

---

docs/json/sonarr/cf/anime-bd-tier-04-seadex-muxers.json
docs/json/sonarr/cf/anime-web-tier-06-fansubs.json

**Purpose**
French release group matches "Anime Web Tier 06" and "Anime BD Tier 04" by mistake. Incoporate changes to exclude Tsundere-Raws being matched as Tsundere. 
Change is borrowed from discord in the message of rg9400:
https://discord.com/channels/492590071455940612/934222763709833217/1059948136103157870
**Approach**
This will lower the score of Tsundere-Raws releases to 0 if they forget to include VOSFTR.
**Learning**

Change Anime tiers to exclude Tsundere-Raws.

---

docs/json/radarr/cf/dv-webdl.json
docs/json/radarr/cf/opus.json
docs/json/sonarr/cf/dv-webdl.json
docs/json/sonarr/cf/opus.json
docs/updates.txt

- [Starr] Prevent CF `Opus` (audio) to be matched if Opus is in the release name. (Mainly for Sonarr being the regex matching starts after Episode number, but also added it to Radarr CF to be consistent + Added: regex example).
- [Starr] Remove RlsGrp `SiC` from CF `DV (WEBDL)` being they now also do DV only.

 Maintenance-Release-20230122

---

docs/json/radarr/cf/anime-bd-tier-02-seadex-muxers.json
docs/json/radarr/cf/anime-web-tier-01-muxers.json
docs/json/sonarr/cf/anime-bd-tier-02-seadex-muxers.json
docs/json/sonarr/cf/anime-web-tier-01-muxers.json

**Purpose**
Adding LYS1TH3A to BD tier 02 and Web Tier 01
**Learning**

feat(anime) - add LYS1TH3A to the Anime tiers

---

docs/Radarr/Radarr-collection-of-custom-formats.md
docs/Radarr/recyclarr-config/hd_bluray_web.yml
docs/Radarr/recyclarr-config/remux_web_1080p.yml
docs/Radarr/recyclarr-config/remux_web_2160p.yml
docs/Radarr/recyclarr-config/uhd_bluray_web.yml
docs/SQP/yml/sqp-1.yml
docs/SQP/yml/sqp-2.yml
docs/SQP/yml/sqp-3.yml
docs/SQP/yml/sqp-4.yml
docs/SQP/yml/sqp-5.yml
docs/Sonarr/Sonarr-Release-Profile-RegEx.md
docs/json/radarr/cf/hbo.json
docs/json/radarr/cf/hmax.json
docs/json/sonarr/cf/hbo.json
docs/json/sonarr/cf/hmax.json
docs/json/sonarr/rp/streaming.json
includes/cf/radarr-streaming-services.md

**Purpose**
There are inconsistencies between the HBO and HBO Max custom formats across the Sonarr V3/V4 and Radarr guides, and also the Sonarr V4 HBO CF was matching any release from the HBO rlsgrp.
**Approach**
- Apply consistent regexes across all areas of the guide, including conditionals for matching the streaming service only
- Created a new HBO Radarr CF for matching older HBO (not HMAX) releases
- Update relevant guide pages and recyclarr configs
**Learning**

Fix HBO/HMAX inconsistencies across Sonarr V3/V4 and Radarr, Fix HBO rlsgrp matching HBO/HMAX Streaming CF

---

docs/SQP/yml/sqp-2.yml
docs/SQP/yml/sqp-3.yml
docs/SQP/yml/sqp-4.yml
docs/SQP/yml/sqp-5.yml

**Purpose**
To update the SQP recyclarr configs to add a comment for optionally disabling the x264 CF to match the updated guide pages
**Approach**
Add a comment to each YML file advising users to comment out the appropriate code block to disable the x264 CF
**Learning**

Update SQP recyclarr configs with optional x264 comment

---

docs/Sonarr/Sonarr-Release-Profile-RegEx.md
docs/Sonarr/recyclarr-config/web_1080p_v4.yml
docs/Sonarr/recyclarr-config/web_2160p_v4.yml
docs/Sonarr/sonarr-collection-of-custom-formats.md
docs/json/sonarr/cf/cc.json
docs/json/sonarr/rp/streaming.json
includes/cf/sonarr-streaming-services.md

**Purpose**
Comedy Central streaming service missing in Sonarr custom formats.
**Approach**
Added Comedy Central streaming service to the Sonarr custom formats.
Closes #1148 

feat(sonarr): added `Comedy Central` CF

---

docs/json/radarr/cf/bad-dual-groups.json

**Purpose**
Prevent TvR releases from getting fetched, because first audio is always german despite not being labeled as such.
**Approach**
Add TvR to the Bad Dual Audio CF. 
Closes #1156 

feat(radarr): add `TvR` to `Bad Dual Audio` CF

---

metadata.json
metadata.schema.json

The `recyclarr` property was under `json_paths` which isn't appropriate for a few reasons:
1. `json_paths` is expected to be for guide-only data (like custom formats).
2. The recyclarr path at the moment is to YAML files, not JSON files.

Move recyclarr property up a level

---

docs/json/radarr/cf/dv-fel.json
docs/json/radarr/cf/dv-hdr10.json
docs/json/radarr/cf/dv-hlg.json
docs/json/radarr/cf/dv-sdr.json
docs/json/radarr/cf/dv-webdl.json
docs/json/radarr/cf/dv.json
docs/json/radarr/cf/hdr-undefined.json
docs/json/radarr/cf/hdr.json
docs/json/radarr/cf/hdr10.json
docs/json/radarr/cf/hdr10plus-boost.json
docs/json/radarr/cf/hdr10plus.json
docs/json/radarr/cf/hlg.json
docs/json/radarr/cf/pq.json
docs/json/radarr/cf/sdr.json
docs/json/sonarr/cf/dv-fel.json
docs/json/sonarr/cf/dv-hdr10.json
docs/json/sonarr/cf/dv-hlg.json
docs/json/sonarr/cf/dv-sdr.json
docs/json/sonarr/cf/dv-webdl.json
docs/json/sonarr/cf/dv.json
docs/json/sonarr/cf/hdr-undefined.json
docs/json/sonarr/cf/hdr.json
docs/json/sonarr/cf/hdr10.json
docs/json/sonarr/cf/hdr10plus-boost.json
docs/json/sonarr/cf/hdr10plus.json
docs/json/sonarr/cf/hlg.json
docs/json/sonarr/cf/pq.json
docs/json/sonarr/cf/sdr.json
docs/updates.txt

**Purpose**
Rework the HDR metadata CFs, to prevent false matches from happening.
**Approach**
Rewrote almost all the regex for the HDR metadata CFs to be oneliners, to prevent false matches from happening.

feat(starr): rework of HDR metadata CFs

---

docs/json/radarr/cf/dv-fel.json
docs/json/radarr/cf/dv.json
docs/json/radarr/cf/hdr10.json
docs/json/sonarr/cf/dv-fel.json
docs/json/sonarr/cf/dv.json
docs/json/sonarr/cf/hdr10.json
docs/updates.txt

**Purpose**
Fix mistakes in changes to the HDR metadata CFs that where merged with #1171.
**Approach**
Change some regex to correctly match `DV`, `HDR10` and `DV (FEL)`.

fix(starr): fix mistakes in HDR metadata CFs

---

docs/Hardlinks/How-to-setup-for/TrueNAS-Core.md

Trivial: remove extra separator at the bottom since the support include already contains it
**Learning**

Trivial: remove extra separator at the bottom of TrueNAS-Core Guide

---

docs/recyclarr-configs/radarr/anime-radarr.yml
docs/recyclarr-configs/radarr/hd-bluray-web.yml
docs/recyclarr-configs/radarr/remux-web-1080p.yml
docs/recyclarr-configs/radarr/remux-web-2160p.yml
docs/recyclarr-configs/radarr/sqp-1.yml
docs/recyclarr-configs/radarr/sqp-2.yml
docs/recyclarr-configs/radarr/sqp-3.yml
docs/recyclarr-configs/radarr/sqp-4.yml
docs/recyclarr-configs/radarr/sqp-5.yml
docs/recyclarr-configs/radarr/uhd-bluray-web.yml
docs/recyclarr-configs/sonarr/anime-sonarr-v4.yml
docs/recyclarr-configs/sonarr/web-1080p-v4.yml
docs/recyclarr-configs/sonarr/web-2160p-v4.yml

Some default scores not set, some CFs needed moving to custom scoring section for easier identification.
**Purpose**
To fix and update the recyclarr anime configs for Sonarr V4 and Radarr
**Approach**
Match them to the guide, add scores where scores don't exist in the guide, move some CFs to the custom scoring sections so users know these can be manually adjusted
**Learning**

Fixes to anime recyclarr configs

---

docs/json/radarr/cf/special-edition.json

**Purpose**
Special Edition matches "IMAX Edition", so adding unnecessary extra scoring to releases that already match "IMAX"
**Approach**
Add an additional negate for "IMAX Edition"
**Learning**

Exclude "IMAX Edition" from Special Edition CF

---

docs/json/radarr/cf/upscaled.json

**Purpose**
Fix the `Upscaled` CF not matching `Upscale` in the release title.
Should fix https://discord.com/channels/492590071455940612/1074721364059107388/1082678793979822190
**Approach**
Adjust the regex to match `Upscale`.

fix(radarr): `Upscaled` CF not matching `Upscale`

---

docs/json/radarr/cf/bad-dual-groups.json

**Purpose**
Prevent `ONLYMOViE` from being picked up, because they put french audio first.
**Approach**
Add `ONLYMOViE` to the `Bad Dual Groups` custom format.

feat(radarr): add `ONLYMOViE` to `Bad Dual Groups` CF

---

docs/Sonarr/Sonarr-Release-Profile-RegEx.md
docs/json/sonarr/rp/optionals.json
docs/updates.txt

**[New]**
- None
**[Updated]**
- None
**[Fixed]**
- [Sonarr v3] Fix copy/paste error with PR#1234 for the Optional `Scene` prevent matching on releases renamed by trackers.

Fix `PR1234`

---

docs/json/sonarr/cf/sho.json

**Purpose**
Fix the `SHO` CF wrongfully matching "Showtime" in the episode title.
Closes #1247 
**Approach**
Adjust the regex to account for episode titles.

fix(sonarr): `SHO` CF mismatching

---

docs/Radarr/Radarr-collection-of-custom-formats.md
docs/Sonarr/sonarr-collection-of-custom-formats.md
docs/updates.txt

**Purpose**
Correct the scores for some `Unwanted`/`Optional` CFs in the Guides.
Fixes #1252 
**Approach**
Change the scores in the Guides from `-1000` OR `-10000` to only `-10000`.

fix(guide): unwanted CF scores

---

docs/Downloaders/SABnzbd/scripts/replace_for/replace_for.py

**Purpose**
There were a typo on `try` block, but the real issue is the post-processing scripts have differents list of args than pre-queue scripts, so the variables were wrong (specifict the `directory`)
Im not sure yet if __post-scripts__ changed the number of variables like __pre-queue__ does, Im still waiting an answer on that.
**Approach**
**Learning**

Revert "SABnzbd - Update replace_for.py to work with V.4.0.0"

---

docs/recyclarr-configs/radarr/anime-radarr.yml
docs/recyclarr-configs/radarr/hd-bluray-web.yml
docs/recyclarr-configs/radarr/remux-web-1080p.yml
docs/recyclarr-configs/radarr/remux-web-2160p.yml
docs/recyclarr-configs/radarr/sqp/sqp-1.yml
docs/recyclarr-configs/radarr/sqp/sqp-2.yml
docs/recyclarr-configs/radarr/sqp/sqp-3.yml
docs/recyclarr-configs/radarr/sqp/sqp-4.yml
docs/recyclarr-configs/radarr/sqp/sqp-5.yml
docs/recyclarr-configs/radarr/uhd-bluray-web.yml
docs/recyclarr-configs/sonarr/anime-sonarr-v4.yml
docs/recyclarr-configs/sonarr/web-1080p-v4.yml
docs/recyclarr-configs/sonarr/web-2160p-v4.yml

Updated recyclarr configs to support new YML configuration requirements for `reset_unmatched_scores`.
**Purpose**
YML configuration for `reset_unmatched_scores` is changing in recyclarr v5, and is also supported in the newly released v4.4.0.
**Approach**
Relocate `reset_unmatched_scores` configuration item.
**Learning**

Updated recyclarr configs

---

docs/json/radarr/cf/anime-bd-tier-03-seadex-muxers.json
docs/json/radarr/cf/anime-bd-tier-06-fansubs.json
docs/json/radarr/cf/anime-web-tier-03-official-subs.json
docs/json/sonarr/cf/anime-bd-tier-03-seadex-muxers.json
docs/json/sonarr/cf/anime-bd-tier-06-fansubs.json
docs/updates.txt

**Purpose**
Added LazyRemux to tier 03 for Radarr and Sonarr
Fixed web tier 03 CF for Radarr. Wrong source codes were used
**Learning**

feat(anime) CF updates

---

docs/recyclarr-configs/sonarr/anime-sonarr-v4.yml

**Purpose**
Template file for recyclarr Anime have divergent scores for streaming services that guide shows.
AMZN (100), DSNP (90) and NF (90) needs to be like guide says.
**Approach**
Add the section to recyclarr to override the score as the guide says.
**Learning**

fix(recyclarr/anime): override score for streaming services

---

docs/json/sonarr/cf/lq.json

**Purpose**
Prevent `HiQVE` releases from getting grabbed, because the do x265 encodes with their tag hardcoded in the top right.
Closes #1279 
**Approach**
Add `HiQVE` to the `LQ` CF.

feat(sonarr): add HiQVE to LQ

---

docs/json/sonarr/cf/10bit.json

In addition to `10bit` and `10.bit`, some releases I've seen on animebytes have the substring `10-bit`. This change supports that.
Example: https://regex101.com/r/6FX1ts/1

Update 10bit.json for sonarr to support hyphens

---

docs/json/radarr/cf/10bit.json

**Purpose**
Just like https://github.com/TRaSH-/Guides/pull/1283, I made this PR to support hyphenated `10-bit` strings for radarr.
Example: https://regex101.com/r/6FX1ts/1

Update 10bit.json for radarr to support hyphens

---

docs/json/sonarr/quality-size/series.json
docs/updates.txt

**[New]**
- None
**[Updated]**
- [Sonarr] Changed quality size mix/max - Set the max size to max to be consistent with Radarr, and this also helps to prevent issues with usenet files being always bigger, lowered the min size for several qualities.
**[Fixed]**
- None

[Sonarr] Change quality size mix/max

---

docs/json/sonarr/cf/lq.json
docs/json/sonarr/rp/lqGroups.json

**Purpose**
Prevent `TG` releases from getting grabbed, because the do releases in strange aspect ratios and mislabel their releases.
Closes #1297 
**Approach**
Add `TG` to the `LQ` CF.

feat(sonarr): add TG to LQ

---

docs/json/sonarr/cf/br-disk-btn.json

- NEW: CF `BR-DISK (BTN)`, being that BTN renames their BR-DISK wrong (and why rename in the first place ? ex AVC to H.264), they aren't detected as BR-DISK for this I edited the normal CF `BR-DISK` so it will be recognized, but this could also result in a few false positive. that's why it won't be added to the original `BR-DISK`. it's best to just use both.

Sonarr v4 Special CF BR-DISK for BTN

---

docs/json/radarr/cf/vinegar-syndrome.json

**Purpose**
Fix false positive matches on `vs` in movie titles for the `Vinegar Syndrome` CF.
Fixes #1314 
**Approach**
Make `-` non-optional.

fix(radarr): VS false positives

---

docs/Radarr/Radarr-collection-of-custom-formats.md
docs/Sonarr/Sonarr-Release-Profile-RegEx.md
docs/Sonarr/sonarr-collection-of-custom-formats.md
docs/json/radarr/cf/max.json
docs/json/sonarr/cf/max.json
docs/json/sonarr/rp/streaming.json
includes/cf/radarr-streaming-services.md
includes/cf/sonarr-streaming-services.md

**Purpose**
Add `Max` CF to match the renamed `HBO Max` streaming service.
**Approach**
Add the `Max` CF to all the jsons and guides.

feat(starr): add Max CF

---

docs/json/radarr/cf/lq.json

**Purpose**
Add `OFT` to the `LQ` CF, because they are a continuation group of nikt0.
Fixes #1341 
**Approach**
Add `OFT` to the `LQ` CF.

feat(radarr): add OFT to LQ

---

docs/Sonarr/Sonarr-Release-Profile-RegEx.md
docs/json/radarr/cf/scene.json
docs/json/sonarr/cf/scene.json
docs/json/sonarr/rp/optionals.json

**Purpose**
To exclude the scene group `EDITH` since a few trackers are renaming their releases and thus making it eligible for grabbing.
Eg. `The Series S01E07 1080p WEB-DL DD+ 5.1 H.264-EDITH`
100% a scene group according to predb and srrdb.
**Approach**
By adding `EDITH` to the scene list since the catch all regex doesn't catch it.
**Learning**

Added: `EDITH` as scene group

---

docs/json/radarr/cf/remux-tier-03.json
docs/updates.txt

**[Fixed]**
- [Radarr] Removed: RlsGrp `CiNEPHiLES` from Remux Tier to prevent download loops.
**[Info]**
This RlsGrp has a weird file naming structure what results in to download loops.
At the moment Radarr only probes the first audio track, and it doesn't read the nfo's. This would require scraping the tracker/indexer, which is undesired and mostly frowned upon and at very least simply forbidden. So in the current state it needs to work with the info provided in the filename and/or release name and what's used as first audio track.
So this is something that needs to be fixed on the RlsGrp side and they have 2 options how to solve it.
- Fix their bad/wrong naming choice.
- Change what they select as default/first track.
I've contacted them about this issue and they will not be changing …

Removed: RlsGrp `CiNEPHiLES` from Remux Tier to prevent download loops

---

docs/json/radarr/cf/hd-bluray-tier-02.json

**Purpose**
Put `HiDt` into the HD Bluray Tiers because they got a number of GP releases on PTP and recently started to release again after a longer downtime.
**Approach**
Add `HiDt` to the `HD Bluray Tier 02` CF.

feat(radarr): add HiDt to HD Bluray Tier 02

---

includes/sqp/1-4k-qp-settings-sqp1.md
includes/sqp/1-4k-qp-settings.md
includes/sqp/1-qp-settings.md

Update the information as to why a user may want to lower the minimum quality profile score from 1000 to 10
**Purpose**
To amend the reasoning behind why a user may want to lower the SQP-1/SQP-1 (2160p) minimum QP score
**Approach**
Amend the text to include 'searching for content that is more rare' as a valid reason to lower the score.
**Learning**

Update SQP1 / SQP1 2160p Minimum Score Guidance

---

docs/json/radarr/cf/remux-tier-02.json

**Purpose**
Fix #1374
**Approach**
Add `CiNEPHiLES` to `Remux Tier 02`.

feat(radarr): add CiNEPHiLES to Remux Tier 02

---

docs/json/sonarr/cf/dubs-only.json
includes/cf/sonarr-streaming-services-anime.md

**Purpose**
Updated dubs only CF for Sonarr and streaming services Anime guide
Changelog update not needed as these were part of the previous update that were missed
**Learning**

fix(anime): updated dubs only for sonarr and updated anime streaming services

---

includes/cf/radarr-optional-uhd.md
includes/cf/sonarr-optional-uhd.md
includes/sqp/1-4k-cf-scoring-sqp1.md
includes/sqp/1-4k-cf-scoring.md
includes/sqp/uhd-radarr-optional.md

**Purpose**
Fix #1370
**Approach**
Several Quality profiles have a demanding MUST must warning for several CF that should be used, change warning/description to choice.

fix(starr): change must warning to suggestion

---

.github/workflows/lint-markdown.yml
.markdownlint.jsonc

Commit fb6b49f9 introduced a regression in the markdown lint workflow by converting the inline configuration options to a `.markdownlint.jsonc` file. However, this file is not used by the Ruby version of markdownlint (which is used here). It is used by the Node version instead. The correct file would have been `.mdlrc`.
This commit simply restores the inline options as they were before that job was refactored out into its own file. This gets the lint logic working again without much fuss.

ci: Fix markdown lint

---

.github/workflows/hold-merge.yml

Adds fail workflow if PR is labeled on hold to prevent merging

chore(GIT): block merging by label

---

docs/Sonarr/Sonarr-Release-Profile-RegEx.md
docs/json/sonarr/cf/web-scene.json
docs/updates.txt
includes/cf/sonarr-hq-source-group.md

To apply a more appropriate score to the Sonarr WEB Scene custom format, and update sections of the Sonarr V3 guide

fix(Sonarr): Updated WEB Scene score and some V3 guide updates

---

docs/json/radarr/cf/lq.json
docs/json/radarr/cf/upscaled.json

Add VISIONPLUSHDR to LQ group as they do fake HDR releases
https://regex101.com/r/IjNcAe/1
Change regrade filter to match re-grade and regrade
https://regex101.com/r/lGyI2i/1

VISIONPLUSHDR + re-grade

---

docs/json/radarr/cf/uhd-bluray-tier-01.json
docs/json/radarr/cf/uhd-bluray-tier-02.json
docs/json/radarr/cf/uhd-bluray-tier-03.json
docs/updates.txt
includes/sqp/1-4k-cf-scoring-sqp1.md
includes/sqp/1-4k-cf-scoring.md
includes/sqp/1-cf-scoring.md
includes/sqp/2-cf-scoring.md
includes/sqp/5-cf-scoring.md
includes/sqp/uhd-radarr-misc.md
includes/sqp/uhd-radarr-resolution.md

To make the UHD Tier CFs compatible with the main guides
Planned date and time to merge: Saturday 15 July 2023 around 12:00 GMT+2 <https://everytimezone.com/s/ad03ff37>

fix(radarr): Update UHD Bluray Tier scores

---

includes/sqp/1-4k-cf-scoring-sqp1.md
includes/sqp/1-4k-merge-qualities-sqp1.md
includes/sqp/1-4k-select-qualities-sqp1.md
includes/sqp/1-cf-scoring.md
includes/starr/move-quality-to-top.md

Fix the following GHI:
- #1483
- #1484
- #1485
- Add CF `SDR` to table
- Add tip if you prefer 2160p Imax-E
- Updated BHDStudio Imax info
- Removed Code block `HD-Bluray-Tier-xx`

fix(radarr): `SQP-1 (2160p)` PR#1473

---

docs/json/radarr/cf/dd.json
docs/json/radarr/cf/ddplus-atmos.json
docs/json/radarr/cf/ddplus.json
includes/sqp/1-cf-scoring.md

Boost the audio scores DD, DDP and DDPA. So they are preferred over DTS.
Fix the following GHI:
- #1498

fix(sqp-1): boost audio scores DD, DDP and DDPA

---

docs/json/radarr/cf/lq.json

Fix #1509 
Adjust `24xHD` in LQ CF.

fix(radarr): 24xHD regex in LQ CF

---

docs/json/radarr/cf/lq.json

Fix: #1519 
- #1519 
Added rlsgrp `41RGB` to `LQ`

fix(radarr): add rlsgrp `41RGB` to `LQ`

---

docs/json/radarr/cf/truehd-atmos.json
docs/json/sonarr/cf/truehd-atmos.json

Fix: #1528
- #1528 
Remove rlsgrp `CtrlHD` from CF `TrueHD Atmos`

fix(starr): remove rlsgrp `CtrlHD` from CF `TrueHD Atmos`

---

docs/json/radarr/cf/uhd-bluray-tier-02.json

To add the MainFrame rlsgrp to UHD Bluray Tier 02
Modify the UHD Bluray Tier 02 custom format to add in the MainFrame release group as a new optional Release Group condition
None

feat(radarr): Add MainFrame to UHD Bluray Tier 02

---

docs/json/radarr/cf/3d.json

Word boundaries don't apply to both sides of all values in 3d regex
Add parenthesis to prevent false positives

fix(radarr): Word boundaries not applying to 3d regex

---

docs/json/radarr/naming/radarr-naming.json

Fix: #1540
- #1540 
Change:
Radarr: `{[Mediainfo AudioCodec}{ Mediainfo AudioChannels}]`
to the correct way that Sonarr uses
Sonarr: `{[Mediainfo AudioCodec}{ Mediainfo AudioChannels]}`
This shouldn't create issues for existing naming scheme's
it's more to have a  consistent layout.

fix(radarr): copy /paste error in naming scheme

---

docs/json/radarr/cf/atmos-undefined.json
docs/json/radarr/cf/truehd-atmos.json
docs/json/radarr/cf/truehd.json
docs/json/sonarr/cf/atmos-undefined.json
docs/json/sonarr/cf/truehd-atmos.json
docs/json/sonarr/cf/truehd.json

fix(starr): Remove RlsGrps from CF TrueHD and TrueHD Atmos

---

docs/Hardlinks/How-to-setup-for/TrueNAS-Core.md

Updated the `Configure and enable NFS service` section to cover a common issue seen when enabling NFSv4. Unless the NAS and the host are on the same domain (or setup with idmapping, which is no longer recommended) users will observe `nobody:4294967294` when doing a `ls` on the files in the mount. Enabling `NFSv3 ownership model for NFSv4` solves that issue without the domain requirement if desired.
Closes #1476 by revising documentation to clarify NFSv4 gotcha.

feat(guides): revise truenas core NFSv4 section

---

docs/json/radarr/cf/lq.json

Resolve #1536 
Add `jennaortega` to the Radarr `LQ` CF.

feat(radarr): add jennaortega to LQ CF

---

docs/json/radarr/cf/dts-hd-ma.json
docs/json/radarr/cf/dts.json
docs/json/sonarr/cf/dts-hd-ma.json
docs/json/sonarr/cf/dts.json

Fixes #1558 
Adjusted the `DTS-HD MA` regex to match more accurately and added a regex example.

fix(starr): DTS-HD MA regex and add example

---

docs/Radarr/Radarr-recommended-naming-scheme.md
docs/Sonarr/Sonarr-recommended-naming-scheme.md
docs/json/radarr/naming/radarr-naming.json
docs/json/sonarr/naming/sonarr-naming.json

This is a tmp fix for: #1371 till #1386 can be merged that's waiting for Radarr/Sonarr to support `=` for ID when https://github.com/Radarr/Radarr/pull/8730 get's merged
tmp removed the Emby ID suggestions in the Radarr and Sonarr naming scheme guide

fix(guide): tmp fix for emby naming scheme

---

docs/updates.txt
includes/cf/radarr-unwanted-uhd.md
includes/cf/radarr-unwanted.md

Amend guide profiles to block 'Extras' releases by default
- Add the Extras CF to Radarr HD/UHD unwanted tables and descriptions
None

fix(guides): Add Extras CF to Radarr HD/UHD unwanted

---

docs/Radarr/Radarr-collection-of-custom-formats.md

Extras CF is missing from the Radarr collection of custom formats guide page
- Add Extras to Radarr Collection of Custom Formats guide page
None
If you're adding a new Custom Format, make sure you follow the [Radarr/Sonarr Custom Format (JSON) Guidelines](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md). -->

fix(guides): Add Extras CF to Radarr Collection of Custom Formats

---

docs/json/radarr/cf/dts-es.json
includes/sqp/1-4k-cf-scoring-sqp1.md
includes/sqp/1-cf-scoring.md

To allow DTS-ES releases under SQP-1 (1080p/2160p), and prevent some download loops
- Amend the DTS-ES score for both SQP-1 variants to 0 so that these releases are not blocked, and to prevent download loops resultant from mis-naming. DTS-ES contains a DTS core, so will fall back to this on non-compatible systems.

feat(guides): SQP-1 score change for DTS-ES Custom Format

---

docs/Downloaders/qBittorrent/Tips/How-to-run-the-unRaid-mover-for-qBittorrent.md

This adds instructions about how to run the qbittorrent mover.py script using [Python virtual environments](https://docs.python.org/3/library/venv.html) on Unraid.
Using pyenv allows you to create and run isolated Python (and pip) from within a specific location, doing so you **do not need to run any commands after reboot**.

docs(mover): Add Python venv method

---

docs/json/radarr/cf/br-disk.json
docs/json/sonarr/cf/br-disk-btn.json
docs/json/sonarr/cf/br-disk.json

Fix `BR-DISK` CF to match the edge case: `[BD]Movie.Title.2023.1080p.COMPLETE.BLURAY-RlsGrp`
Adjust the `BR-DISK` regex and bring it up-to-date with the Radarr one.

fix(starr): BR-DISK CF regex

---

docs/json/radarr/cf/bad-dual-groups.json
docs/json/sonarr/cf/bad-dual-groups.json

Fix: #1583 
- #1583 
This RlsGrp takes the original release, then they add their own preferred language (ex. Italian) as the main audio track ( often AAC 2.0), What results after renaming and FFprobe that the media file will be recognized as Italian AAC audio. It's a common rule that you add the best original audio track as first.

fix(starr): add RlsGrp BlackBit to Bad Dual Groups

---

docs/json/radarr/cf/lq.json

Fix: #1582 
- #1582 
SLOT was initially put into the LQ group for preing/releasing a mistagged version of Across the Spiderverse.
SLOT is also one of the few in scene that consistently does 4k web and has nearly 1000 releases, 99% of which are fine, so we decided to remove them from LQ because they only did till now 1 mistagged version
LQ are for RlsGRps that release fake, wrong or cause loops or other issues for automation.

fix(radarr): Remove RlsGrp `SLOT` from CF `LQ`

---

docs/json/radarr/cf/hd-bluray-tier-03.json

feat(radarr): add RlsGrp `LoRD` to `HD Bluray Tier 03`

---

docs/Downloaders/qBittorrent/Tips/Themes.md

Feature: #1545 
- https://github.com/TRaSH-Guides/Guides/issues/1545
Create a new guide page at Downloaders > qBittorrent > Tips > Themes, containing a table of known working qBittorrent themes
None

feat (Guides): Added new qBittorrent Tips page for known working themes

---

docs/json/radarr/cf/uhd-bluray-tier-01.json
docs/json/radarr/cf/uhd-bluray-tier-02.json
docs/json/radarr/cf/uhd-bluray-tier-03.json

Fix: #1588 
- #1588 
SDR can be handles with the SDR CF on user choice

fix:(radarr): remove SDR condition from UHD Bluray Tier 1-3

---

docs/Hardlinks/Replace-copies-with-hardlinks.md

I was browsing the jdupes repo and noticed the repo has moved, the github is now deprecated, see:
https://www.jdupes.com/2023/10/05/news-github-is-out-codeberg-is-in/
Github out, codeberg in.

chore(Guide): fix the jdupes repo as per Jody Bruchon’s website

---

docs/json/radarr/cf/bad-dual-groups.json
docs/json/sonarr/cf/bad-dual-groups.json

feat(starr): add RlsGrp `ZNM` to `Bad Dual Groups`

---

.gitignore
mkdocs.yml

https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/?h=twemoji#emoji
Removes deprecation warnings
Also add `site/` to gitignore, which helps when building locally.

fix: :arrow_up: use twemoji from mkdocs material

---

docs/Radarr/Radarr-collection-of-custom-formats.md
docs/Sonarr/sonarr-collection-of-custom-formats.md
docs/json/radarr/cf/sdr-no-webdl.json
docs/json/sonarr/cf/sdr-no-webdl.json

To create custom formats which allow users to permit 4K SDR WEB releases whilst still blocking 4K SDR Remux/Bluray releases.

feat(starr): Create SDR (no WEBDL) custom formats

---

docs/json/radarr/cf/bcore.json
docs/json/radarr/quality-size/sqp-streaming.json
includes/sqp/1-4k-cf-scoring-sqp1.md
includes/sqp/1-4k-streaming-services.md
includes/sqp/1-cf-scoring.md
includes/sqp/1-streaming-services.md

Fix: #1614
Fix: #1626
Fix: #1627
- #1614
- #1626
- #1627

fix(radarr): SQP-1 (2160p) several updates (v2)

---

docs/Radarr/Radarr-collection-of-custom-formats.md
docs/Sonarr/Sonarr-Release-Profile-RegEx.md
docs/Sonarr/sonarr-collection-of-custom-formats.md
docs/json/radarr/cf/fod.json
docs/json/radarr/cf/tver.json
docs/json/radarr/cf/u-next.json
docs/json/sonarr/cf/fod.json
docs/json/sonarr/cf/tver.json
docs/json/sonarr/cf/u-next.json
docs/json/sonarr/rp/streaming.json
includes/cf/radarr-streaming-services.md
includes/cf/sonarr-streaming-services.md

- Add the following streaming service to the guides
- `FOD`
- `TVer`
- `U-NEXT`
Added: Streaming Service `FOD`, `TVer` and `U-NEXT` with a score of `0`, mainly for the naming scheme
- Should the Sonarr v3 release profiles also be updated? In that case, what score would be appropriate?

feat(starr): add custom formats for Japanese streaming services `FOD`, `TVer` and `U-NEXT`

---

docs/Downloaders/qBittorrent/Tips/Themes.md

feat(guides): Add Honeywell qBittorrent Theme to Themes Page

---

docs/json/radarr/cf/retags.json

Retagging group VAV adding Vietnamese audio tracks to existing releases, causing unwanted release group parsing. Propose adding to Retag CF to filter out.
Recommend adding .VAV to retag CF to filter out unwanted VIE audio. Related to recent Radarr update adding VIE to Vietnamese Language parsing.
Modify the retags.json in guide with Trash-provided regex to filter out these releases.
Added code to retags.json as recommended. Task Complete?

feat(radarr): Added `.VAV` to the  `Retags` Custom Format

---

docs/json/radarr/cf/hd-bluray-tier-03.json
docs/json/radarr/cf/lq-release-title.json
docs/json/radarr/cf/lq.json
docs/json/sonarr/cf/lq-release-title.json

- Fix: #1641 
- Partial reversion of #1605 
- Add tarunk9c and DepraveD to `LQ`
- Add BiTOR 2160p releases to `LQ (Release Title)` (1080p releases are not currently added to LQ, but will now be un-tiered)
- Remove BiTOR from `HD Bluray Tier 03`

Add Groups to LQ

---

docs/json/radarr/cf/2160p.json
docs/json/radarr/cf/atmos-undefined.json
docs/json/radarr/cf/truehd-atmos.json
docs/json/radarr/cf/truehd.json
docs/json/sonarr/cf/2160p.json

- Fix: #1636 
- Partial reversion of #1553 for Radarr - allows TrueHD Atmos matches for groups who don't use full TrueHD Atmos text in releases

fix(starr): Custom Format Conditional Changes

---

docs/json/radarr/cf/truehd-atmos.json
docs/updates.txt

fix(radarr): Add CtrlHD to Atmos condition in TrueHD Atmos Radarr Custom Format

---

docs/Radarr/radarr-setup-quality-profiles.md
docs/Sonarr/sonarr-setup-quality-profiles.md
docs/json/radarr/cf/lq-release-title.json
includes/cf/radarr-optional-uhd.md
includes/cf/radarr-optional.md
includes/cf/sonarr-optional-uhd.md
includes/cf/sonarr-optional.md

Add missing optional panels from public Radarr/Sonarr guide pages.
Fix: #1656

fix(sonarr): Add Missing Optionals

---

docs/json/radarr/cf/lq-release-title.json

fix: #1678 
- Add 1XBET release group to LQ (Release Title) custom format
None

feat(guides): Add 1XBET to LQ (Release Title)

---

docs/json/sonarr/cf/french-anime-fansub.json

Added the FR group `Seimeisen` to the FR Anime FanSub CF.

feat(Sonarr-fr): add `Seimeisen` to FR Anime FanSub

---

docs/json/radarr/cf/dv-hdr10.json
docs/json/sonarr/cf/dv-hdr10.json

Fix `DV HDR10` CF matching on a file with `DV HDR10Plus` mediainfo after import.
Negate `DV HDR10Plus` in the `DV HDR10` CF.

fix(starr): DV HDR10 mismatching

---

docs/json/radarr/cf/retags.json
docs/json/radarr/naming/radarr-naming.json
docs/json/sonarr/cf/it.json
docs/updates.txt

Fix: #1661
Fix: #1684 
Fix: #1688 
Fix: #1689 
- Add `.heb` to Radarr retags custom format
- Reorder brackets in Radarr naming schemes
- Change `ReleaseTitleSpecification` condition to be required for `iT`
- Add `ORARBG` to Radarr retags custom format
None
If you're adding a new Custom Format, make sure you follow the [Radarr/Sonarr Custom Format (JSON) Guidelines](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md). -->

fix(Starr): Update Radarr retags Custom Format, Sonarr iT Custom Format, and Radarr Naming Scheme

---

includes/cf/radarr-all-hdr-formats.md
includes/cf/sonarr-all-hdr-formats.md
includes/sqp/1-4k-cf-scoring-sqp1.md

Fix missing DV HDR10Plus custom format on guide pages
- Add new DV HDR10Plus custom format to relevant guide page HDR sections
None
If you're adding a new Custom Format, make sure you follow the [Radarr/Sonarr Custom Format (JSON) Guidelines](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md). -->

fix(guides): Add DV HDR10Plus to Guides

---

docs/json/radarr/cf/lq-release-title.json

does a lot of cam/prerips where he merges video from one region with audio from cam to produce releases that still just aren't great and have issues half the time
Add RlsGrp `Will1869` to `LQ (Release Title)`

feat(Radarr): add RlsGrp `Will1869` to `LQ (Release Title)`

---

docs/json/sonarr/cf/retags.json

Add `.heb` to `Retags` to prevent Hebrew audio
Add `.heb` to `Retags`

feat(Sonarr): add `.heb` to `Retags`

---

docs/Radarr/Radarr-collection-of-custom-formats.md
docs/Sonarr/sonarr-collection-of-custom-formats.md
docs/json/radarr/cf/dv-disk.json
docs/json/sonarr/cf/dv-disk.json
includes/sqp/uhd-radarr-optional.md

We once created this CF mainly for framestor releases where they released after their hybrid (DV HDR10) from the steaming services a new release using the DV layer from a new released disk.
We did some research and most disk version had FEL but it could also be MEL. Because we can't be 100% sure what's used we decided to rename it to `DV (Disk)`
**NOTE:** If other RlsGrps have a consistent naming and a way we can figure out the difference between DV hybrid vs the original DV layer from the disk, we are willing to add them.

fix(Starr): renamed CF `DV (FEL)` to `DV (Disk)`

---

docs/json/radarr/cf/bad-dual-groups.json
docs/json/sonarr/cf/bad-dual-groups.json

This group adds Portuguese as the default audio and subtitle language
Add them to CF `Bad Dual Groups`

feat(starr): add rlsgrp `vnlls` to `Bad Dual Groups`

---

docs/json/radarr/cf/3d.json

Some releases include `BD3D` to indicate they're 3D instead of the existing specifications.
Adds a BD3D spec to the existing 3d cf.

fix(radarr): 3D CF should match BD3D

---

docs/json/radarr/cf/uhd-bluray-tier-03.json

Remove `LEGi0N` from UHD Bluray Tier 03
- Remove `LEGi0N` section from `uhd-bluray-tier-03.json`

feat(radarr:) Remove `LEGi0N` from UHD Blu-ray Tier 03

---

docs/Radarr/Radarr-collection-of-custom-formats.md
docs/Sonarr/sonarr-collection-of-custom-formats.md

specifies full streaming service name for BBC iPlayer in collections tables
rename and sorted to B's spot in the list/table
- Needs entire list sorted

fix(cf-collection): BBC iPlayer named in collection table

---

mkdocs.yml

currently we have no warnings on building that would affect building, this adds strict mode in mkdocs.yml and will fail building if broken links or previously unfound warnings are introduced
after adding the validation settings to ignore absolute, this should not be an issue unless new warnings or broken links are introduced
https://mkdocs.readthedocs.io/en/0.13.3/user-guide/configuration/?q=strict&check_keywords=yes&area=default#strict
```
WARNING -  redirects plugin: 'updates.txt' is not a valid markdown file!
WARNING -  Redirect target 'updates.txt' does not exist!
```
it is possible that the map in redirects (mkdocs.yml) actually is doing nothing based on these errors - besides warning - and its mere existence in the docs directory is why it works?

build(strict-mode): comments and strict mode for broken link build failure

---

docs/json/radarr/cf/bad-dual-groups.json
docs/json/sonarr/cf/bad-dual-groups.json

Add RlsGrp `LCD` to CF `Bad Dual Groups`

feat(Starr): Add RlsGrp `LCD` to CF `Bad Dual Groups`

---

docs/Radarr/Tips/How-to-setup-language-custom-formats.md

This guide is a shared guide with Radarr, so had to add info that Sonarr doesn't have a preferred language in the quality profile

fix(Starr): Add non existing preferred language for Sonarr

---

docs/Radarr/Radarr-collection-of-custom-formats.md
docs/Radarr/radarr-setup-quality-profiles.md
docs/Sonarr/sonarr-collection-of-custom-formats.md
docs/Sonarr/sonarr-setup-quality-profiles.md
docs/json/radarr/cf/proper.json
docs/json/radarr/cf/repack.json
docs/json/sonarr/cf/proper.json
docs/json/sonarr/cf/repack.json
includes/cf/radarr-misc.md
includes/cf/sonarr-misc.md
includes/sqp/uhd-radarr-misc.md

separates the current repack/proper CF into two and scores it above all repacks.
closes #1734 
Live preview: https://dox.ary.dev
bunch of search and replace and table rebuilding
After discussing with nitsua, this shouldn't break anything locally or on notifarr. He did not review changes, just their structure and the affect it would have on his site.

update(cf/repack-proper): separate repack and proper cfs in sonarr/radarr

---

docs/json/radarr/cf/lq.json

Does micro-ecoded releases. includes extra audio tracks which add more insult to video quality due to size. also fails to include if has hdr fallback so badly named things as well.
Example: 4.5G file for a 4k with dv+hdr10 fallback

feat(radarr): Add RlsGrp `MarkII` to `LQ`

---

docs/Hardlinks/How-to-setup-for/Unraid.md

In order to have all the folders and directories made in one command instead of using an external tool like WinSCP or Krusader. This could also teach the user more about the terminal.
FIx: #1747

feat(guide): Add to the unRaid Hardlinks Guide The fastest way to create the needed subfolders

---

docs/json/radarr/cf/lq-release-title.json
docs/json/sonarr/cf/lq-release-title.json

Update the LQ (Release Title) custom formats to add the BEN THE MEN release group, as their release titles don't format the release group name properly, or include the quality of the release (e.g., Bluray, WEBDL etc). This results in the breaking of automation.
- Add the rlsgrp BEN THE MEN to the LQ (Release Title) custom formats for Radarr and Sonarr
None
If you're adding a new Custom Format, make sure you follow the [Radarr/Sonarr Custom Format (JSON) Guidelines](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md). -->

feat (Starr): Add BEN THE MEN to LQ (Release Title) Custom Formats

---

docs/Downloaders/SABnzbd/scripts/Clean/Clean.py

normalize sys arguments
as pre-queue arguments were changed again in 4.2.0, so rather than handle all three variants (which isnt needed for this script as those fields arent used) can simplify to just focus on the ones that are.
make pre-q script work again 
solve issue with pre-q not working once sab was updated to 4.2.x

fix(guide): SABnzbd Scripts - Updated Clean.py

---

docs/Sonarr/sonarr-collection-of-custom-formats.md

Fix x265 (no HDR/DV) toggle so content correctly appears inside the selector.
- Fix indentation in x265 (no HDR/DV) description text.

fix (Sonarr): Fix x265 (no HDR/DV) section on Sonarr collection of custom formats page

---

docs/json/radarr/cf/10bit.json
includes/sqp/1-4k-cf-scoring-sqp1.md
includes/sqp/1-cf-scoring.md
includes/sqp/radarr-unwanted-sqp1.md
includes/sqp/radarr-unwanted-uhd-sqp1.md

Add CF `10bit` to unwanted to block `Hi10P`
Certain releases use the weird Hi10P for their encodes and this gives you often playback issues..

feat(guide): SQP-1 - Add CF `10bit` to unwanted to block `Hi10P`

---

docs/updates.txt
includes/sqp/1-4k-cf-scoring-sqp1.md

Added missing `DV HDR10+ Boost` to SQP-1 4k optional
Added `DV HDR10+ Boost` to SQP-1 4k optional and included warning and info

feat(guide): SQP - Add `DV HDR10+ Boost` to SQP-1 4k optional

---

docs/Plex/.pages
docs/Plex/Tips/.pages

Make the plex  tips section always seen (non collapse)
vs

style(guide): Plex make tips always seen

---

docs/Radarr/Radarr-collection-of-custom-formats.md
docs/Sonarr/sonarr-collection-of-custom-formats.md
docs/json/radarr/cf/htsr.json
docs/json/sonarr/cf/htsr.json
includes/cf-descriptions/htsr.md

- Add a new custom format to match the Disney+ Hotstar streaming service.
- Resolve: #1603

feat(guides): Add HTSR Streaming Service

---

docs/json/radarr/cf/htsr.json
docs/json/sonarr/cf/htsr.json

Allow `HS` as a distinct word in release titles to match the HTSR custom formats
None

fix(Starr): Update HTSR Custom Formats

---

docs/json/radarr/cf/anime-lq-groups.json
docs/json/sonarr/cf/anime-lq-groups.json
docs/json/sonarr/cf/french-anime-fansub.json

Currently, the French Guide has the `Kaerizaki-Fansub` team in the CF `FR Anime FanSub` but it is also in the CF `Anime LQ Groups`. This is because the team make VOSTFR release (#1822)
We can remove `Kaerizaki-Fansub` in the CF `Anime LQ Groups` because the release name contains `VOSTFR` so it has no impact on the Anime English Guide.
Also I have updated the regex in the french guide of `KaeriZaki` to `Kaerizaki[ .-]?Fansub` for better matching !

fix(Starr-Anime): remove Kaerizaki-Fansub to Anime LQ groups and update FR regex 

---

docs/Sonarr/sonarr-collection-of-custom-formats.md
docs/json/sonarr/cf/season-pack-spec.json

Proposing a slightly different approach to the new Season Pack CF using the Release Type spec. This would allow publishing the new CF now as guides only and not breaking sync rather than leaving as a draft PR.
Keep existing CF as-is with `trash_id` for sync users. Add new spec-based CF as a guides only CF and document version requirement. When feature hits master, rename new CF to replace existing, add in `trash_id` so sync tools pick that up as the new CF and merge sections in the docs.

update(cf/seasonpack(-spec)): Propose different approach

---

docs/json/radarr/cf/amzn.json
docs/json/sonarr/cf/amzn.json

A lot of the german releases coming from amazon video contain the keyword "AmazonHD" in the release title, which is currently not matched by the CF AMZN, which only searches for "amazon" or "amzn".
Regex test: https://regex101.com/r/aNiJfh/1
This PR adds "AmazonHD" for the AMZN CF for both, sonarr and radarr

fix(starr): AMZN CF should also match AmazonHD

---

docs/json/radarr/cf/obfuscated.json
docs/json/sonarr/cf/obfuscated.json

Fix #1842 
Adjust regex of `Obfuscated` CF to not match `Scrambled` in the title.

fix(starr): fix Obfuscated CF mismatching

---

docs/json/radarr/cf/vinegar-syndrome.json

Fix `Vinegar Syndrome` CF not matching `VinSyn`.
Add condition to `Vinegar Syndrome` CF for matching `VinSyn`.

fix(radarr): Vinegar Syndrome not matching VinSyn

---

docs/json/radarr/cf/nf.json
docs/json/sonarr/cf/nf.json

German releases often use NetflixHD in the release title, which is currently not matched by the custom format.
Basically the same as in https://github.com/TRaSH-Guides/Guides/pull/1829
Added optional HD suffix to the custom format.
Regex Test: https://regex101.com/r/QpfWrs/1

fix(starr): Netflix CF to match NetflixHD and NetflixUHD in title

---

docs/Sonarr/sonarr-collection-of-custom-formats.md
docs/json/sonarr/cf/season-pack-spec.json
docs/json/sonarr/cf/season-pack.json

Utilizes the new Season Pack Release Type in the Custom Format for Sonarr. This changes the download loop behavior previously seen.
Leaving this in draft currently until this addition hits master on Sonarr.

feat(sonarr): Add Season Pack CF using ReleaseType Condition

---

docs/json/radarr/cf/remux-tier-01.json
docs/json/radarr/cf/remux-tier-02.json
docs/json/radarr/cf/uhd-bluray-tier-01.json
docs/json/radarr/cf/uhd-bluray-tier-02.json
docs/updates.txt

To enact the first round of the review of release groups, and move them between tiers as appropriate
None

feat(guide): Move RlsGrps Between Tiers

---

docs/Radarr/Radarr-collection-of-custom-formats.md
docs/Sonarr/sonarr-collection-of-custom-formats.md
docs/json/radarr/cf/now.json
docs/json/radarr/cf/strp.json
docs/json/radarr/cf/tving.json
docs/json/sonarr/cf/dscp.json
docs/json/sonarr/cf/now.json
docs/json/sonarr/cf/strp.json
docs/json/sonarr/cf/tving.json
includes/cf-descriptions/dscp.md
includes/cf-descriptions/now.md
includes/cf-descriptions/strp.md
includes/cf-descriptions/tving.md
mkdocs.yml

Added CF Streaming Services `Star+`, `NOW`, `TVING`, `Discovery+`
Added CF Streaming Services `Star+`, `NOW`, `TVING`, `Discovery+`

feat(starr): Added CF Streaming Services `Star+`, `NOW`, `TVING`, `Discovery+`

---

docs/json/radarr/cf/upscaled.json
docs/json/sonarr/cf/upscaled.json

Fixes matching of TheUpscaler releases named in the format `TheUpscaler`, where previously it would only match if there was a space, period, underscore or hyphen between the two words.
Updated the regex to match `TheUpscaler`.
https://regex101.com/r/hRrgEh/1

fix(starr): TheUpscaler not matching

---

docs/json/radarr/cf/dts-es.json
docs/json/radarr/cf/dts-hd-hra.json
docs/json/radarr/cf/dts-hd-ma.json
docs/json/radarr/cf/dts-x.json
docs/json/radarr/cf/dts.json
docs/json/radarr/cf/truehd-atmos.json
docs/json/sonarr/cf/dts-es.json
docs/json/sonarr/cf/dts-hd-hra.json
docs/json/sonarr/cf/dts-hd-ma.json
docs/json/sonarr/cf/dts-x.json
docs/json/sonarr/cf/dts.json
docs/json/sonarr/cf/truehd-atmos.json

Fix the `DTS X` CF mismatching and not matching on various different naming schemes.
Update the regex to more accurately match `DTS X`.

fix(starr): DTS-X CF mismatching

---

.github/workflows/pr-naming-check.yml

verifies that the naming conventions we use are followed for PR open/reopen/edit

ci(pr-name-check): integrates pr naming convention into workflow

---

docs/json/radarr/cf/ddplus.json
docs/json/sonarr/cf/ddplus.json

Prevent double scoring `DD+` and `DD+ Atmos`
Add ` DDPA`  to `Not TrueHD/ATMOS` condition in the `DD+` Custom Format

fix(starr): Prevent double scoring `DD+` and `DD+ Atmos`

---

docs/Downloaders/qBittorrent/Tips/How-to-run-the-unRaid-mover-for-qBittorrent.md

…pt for mover.old
Remove option to edit script for mover.old
Remove outdated option to edit script for mover.old

fix(guide): unRAID Mover and qBittorrent - Remove option to edit script for mover.old

---

docs/json/radarr/cf/aac.json
docs/json/radarr/cf/anime-bd-tier-03-seadex-muxers.json
docs/json/radarr/cf/atmos-undefined.json
docs/json/radarr/cf/dd.json
docs/json/radarr/cf/ddplus-atmos.json
docs/json/radarr/cf/ddplus.json
docs/json/radarr/cf/dts-es.json
docs/json/radarr/cf/dts-hd-hra.json
docs/json/radarr/cf/dts-hd-ma.json
docs/json/radarr/cf/dts-x.json
docs/json/radarr/cf/dts.json
docs/json/radarr/cf/flac.json
docs/json/radarr/cf/pcm.json
docs/json/radarr/cf/truehd-atmos.json
docs/json/radarr/cf/truehd.json
docs/json/sonarr/cf/aac.json
docs/json/sonarr/cf/anime-bd-tier-03-seadex-muxers.json
docs/json/sonarr/cf/atmos-undefined.json
docs/json/sonarr/cf/dd.json
docs/json/sonarr/cf/ddplus-atmos.json
docs/json/sonarr/cf/ddplus.json
docs/json/sonarr/cf/dts-es.json
docs/json/sonarr/cf/dts-hd-hra.json
docs/json/sonarr/cf/dts-hd-ma.json
docs/json/sonarr/cf/dts-x.json
docs/json/sonarr/cf/dts.json
docs/json/sonarr/cf/flac.json
docs/json/sonarr/cf/pcm.json
docs/json/sonarr/cf/truehd-atmos.json
docs/json/sonarr/cf/truehd.json

Fix the `DD` CF not matching on `AC-3`. Fixes #1888 
Adjust `DD`, `DD+` & `DD+ ATMOS` regex for all audio CFs.

fix(starr): match `AC-3` as `DD`

---

docs/Sonarr/Sonarr-Release-Profile-RegEx.md
docs/json/radarr/cf/hmax.json
docs/json/sonarr/cf/hmax.json
docs/json/sonarr/cf/uhd-streaming-cut.json
docs/json/sonarr/rp/streaming.json

closes #1894 - non-standard naming of HBO Max service without separator
https://regex101.com/r/VZsSwC/2
see title
simple change to add optional `?` to existing separators `[ ._-]` of `hbo` and `max`
ctrl shift F -> go to each result and insert a `?` -> save files -> push branch -> create PR.... -> profit

update(cf/hbomax): adds capturing hbomax (without separator)

---

docs/Radarr/Radarr-collection-of-custom-formats.md
docs/Sonarr/sonarr-collection-of-custom-formats.md

fix exposed comment due to space after `!`
fix exposed comment due to space after `!`

chore(guide): fix exposed comment due to space after `!`

---

docs/Downloaders/qBittorrent/Tips/How-to-run-the-unRaid-mover-for-qBittorrent.md

Fix https://github.com/TRaSH-Guides/Guides/pull/1889#discussion_r1585551833
Add missing `"`.

fix(guide): missing quote in unraid mover

---

docs/Downloaders/NZBGet/Basic-Setup.md
docs/Downloaders/NZBGet/Paths-and-Categories.md
docs/Downloaders/NZBGet/index.md
docs/Downloaders/NZBGet/scripts/index.md
docs/Downloaders/SABnzbd/Basic-Setup.md
docs/Downloaders/SABnzbd/scripts/Clean/Clean.py
docs/Downloaders/SABnzbd/scripts/index.md
docs/Downloaders/SABnzbd/scripts/replace_for/replace_for.py
docs/Downloaders/index.md

Fix inconsistencies in the `Downloaders` pages.
Fix capitalization for the downloaders pages in several cases and remove the deprecation warning for NZBGet.

chore(guide): update inconsistent naming in downloaders pages

---

docs/Radarr/Tips/How-to-setup-language-custom-formats.md
docs/json/guide-only/language-german-and-original.json

Dual and Multi language is also picked up as original audio, for some users it's a preferred option, others rather don't get those releases because there is no way to determine upfront which audio track is used as main audio track.

feat(guide): Starr language tips add German dual and multi

---

docs/Downloaders/qBittorrent/Tips/How-to-run-the-unRaid-mover-for-qBittorrent.md

host => The URL you use to access qBittorrent locally. this says to use a URL which would be http://IP:PORT

fix(guide): unclear qbit mover script host vs url and added cache only

---

docs/Guide-Sync/index.md

Improve visuals and remove deprecated info on compare table for guide syncing.
Replace `v` with actual checkmarks and remove Sonarr v3 from the table.

chore(guide): clean up guide sync table

---

docs/json/sonarr/cf/720p.json

Adding a 720p CF to sonarr.
This is following the 2160p and 1080p formats already available for Sonarr, plus the 2160p, 1080p and 720p formats for Radarr, to complete the set.
Hash created via https://md5.gromweb.com/?string=Sonarr+720p

chore(sonarr): add 720p CF

---

docs/Radarr/Radarr-collection-of-custom-formats.md
docs/json/radarr/cf/it.json
docs/json/radarr/quality-profiles/hd-bluray-web.json
docs/json/radarr/quality-profiles/remux-web-1080p.json
docs/json/radarr/quality-profiles/remux-web-2160p.json
docs/json/radarr/quality-profiles/sqp-1-1080p.json
docs/json/radarr/quality-profiles/sqp-1-2160p.json
docs/json/radarr/quality-profiles/sqp-2.json
docs/json/radarr/quality-profiles/sqp-3.json
docs/json/radarr/quality-profiles/sqp-4.json
docs/json/radarr/quality-profiles/sqp-5.json
docs/json/radarr/quality-profiles/uhd-bluray-web.json
includes/cf/radarr-streaming-services.md
includes/sqp/1-4k-streaming-services.md
includes/sqp/1-streaming-services.md

Add Custom Format for iTunes streaming services
Created NEW Custom Format for iTunes streaming services

feat(Radarr): Add Custom Format for iTunes streaming services

---

docs/json/radarr/cf/hd-bluray-tier-03.json

Add RlsGrp `W4NK3R` to `HD Bluray Tier 03`
Added RlsGrp `W4NK3R` to `HD Bluray Tier 03`

feat(Radarr): Add RlsGrp `W4NK3R` to `HD Bluray Tier 03`

---

includes/support.md

Seems that some people don't see the bottom Question & Suggestion banner that they should join the discord channel for help etc
Created a huge CLICK HERE button (both buttons are clickable)
[Dark Mode]
[Light Mode]

feat(guides): Improve bottom Question & Suggestion banner

---

docs/Prowlarr/prowlarr-setup-proxy.md

Fix some typos in Prowlarr, how to setup proxy.

fix(prowlarr): fix typo in prowlarr-setup-proxy.md

---

.gitignore
docs/Radarr/Radarr-collection-of-custom-formats.md
docs/Sonarr/sonarr-collection-of-custom-formats.md
docs/json/radarr/quality-profiles/hd-bluray-web.json
docs/json/radarr/quality-profiles/remux-web-1080p.json
docs/json/radarr/quality-profiles/remux-web-2160p.json
docs/json/radarr/quality-profiles/sqp-1-1080p.json
docs/json/radarr/quality-profiles/sqp-1-2160p.json
docs/json/radarr/quality-profiles/sqp-2.json
docs/json/radarr/quality-profiles/sqp-3.json
docs/json/radarr/quality-profiles/sqp-4.json
docs/json/radarr/quality-profiles/sqp-5.json
docs/json/radarr/quality-profiles/uhd-bluray-web.json
docs/json/sonarr/quality-profiles/web-1080p.json
docs/json/sonarr/quality-profiles/web-2160p.json
includes/cf-descriptions/av1.md
includes/cf/radarr-unwanted-uhd.md
includes/cf/radarr-unwanted.md
includes/cf/sonarr-unwanted-uhd.md
includes/cf/sonarr-unwanted.md
includes/sqp/1-4k-cf-scoring-sqp1.md
includes/sqp/radarr-unwanted-sqp1.md
includes/sqp/radarr-unwanted-uhd-sqp1.md

feat(guides): Move AV1 to unwanted

---

docs/json/sonarr/naming/sonarr-naming.json

To provide an interim fix for an issue discovered with Notifiarr, and potentially Recyclarr, whereby the `default:3` and `default:4` values are expected in the Guides' sonarr-naming.json file.
Restore `default:3` and `default:4` as naming options in the sonar-naming.json file.

fix(sync_tools): Hotfix to re-add `default:3` and `default:4` Sonarr episode naming options

---

docs/json/radarr/cf/hallowed.json
docs/json/radarr/cf/hd-bluray-tier-03.json
docs/json/radarr/cf/uhd-bluray-tier-03.json
docs/updates.txt

- Add the 'hallowed' rlsgrp to Radarr (U)HD Bluray Tier 03
- Create new `hallowed` Radarr custom format for use with SQP-1 variants
- Give default score of `600` to new `hallowed` Radarr custom format
None

feat(guides): Add hallowed to (U)HD Bluray Tier 03 and create new `hallowed` Radarr custom format

---

docs/json/sonarr/naming/sonarr-naming.json

- Reverts TRaSH-Guides/Guides#1972

chore(sync_tools): Revert "fix(sync_tools): Hotfix to re-add `default:3` and `default:4` Sonarr episode naming options"

---

docs/Radarr/radarr-setup-quality-profiles.md
docs/Sonarr/sonarr-setup-quality-profiles.md
docs/index.md
docs/stylesheets/extra.css
includes/cf/score-attention.md
includes/support.md

started by switching to worker-based discord shields that fetch from discords public API
now shields.io seems to work again, so restored those

style(discord-shields): restore discord shields

---

docs/json/radarr/cf/hybrid.json
docs/json/radarr/cf/remux-tier-02.json
docs/json/radarr/cf/remux-tier-03.json
docs/json/sonarr/cf/hybrid.json

Resolve: #1996 and #1997 
- Move KRaLiMaRKo from Radarr Remux Tier 02 to Radarr Remux Tier 03 custom format
- Amend Hybrid custom formats for Sonarr and Radarr to also match Bluray qualities
- Tested in Sonarr and Radarr test instances
None

feat(guides): Move KRaLiMaRKo to Radarr Remux Tier 03 and expand Hybrid CF matching to include Bluray qualities

---

docs/json/radarr/cf/amzn.json
docs/json/sonarr/cf/amzn.json

Reverts TRaSH-Guides/Guides#1950
Major breaking change. Prevents future AMZN renames. This was not tested in Sonarr prior to merging and breaks renaming

fix(Revert): "fix(starr): Moved webdl and webrip into Amazon regex to prevent incorrect matches"

---

docs/.pages
docs/Lidarr/index.md

Many people asked if TRaSH Guides has a guide for Lidarr, so someone suggested adding a redirect to [Davo's Community Lidarr Guide](https://wiki.servarr.com/lidarr/community-guide "Like TRaSH Guides, but Davo for Lidarr")
Added Lidarr redirect to Davo's Community Lidarr Guide

feat(guides): Add Lidarr redirect to Davo's Community Lidarr Guide

---

docs/json/radarr/cf/anime-lq-groups.json
docs/json/sonarr/cf/anime-lq-groups.json

Resolve #1995 
Add `Mozzi2`, `uP`, `Kallango`, `Emmid` and `Sokudo` to the `Anime LQ Groups` CF.
- Sokudo - AV1
- Emmid - some releases missing subtitles, only have dubtitles, includes many unnecessary language tracks, not consistent with track labelling and order
- Kallango/uP - Not on Nyaa and I cannot figure out why I initially banned them. My guess though is that both do upscales which replace older shows. Kallango seems to be exclusively on one of the unnameables, but they have some non-anime releases on others where it is just pt-BR releases.
- Moozzi2 - As it was getting uploaded to usenet, was replacing a bunch of people's releases with low quality raws.

feat(starr-anime): add several RlsGrps to LQ

---

docs/json/radarr/cf/anime-raws.json
docs/json/sonarr/cf/anime-raws.json

Resolve #2008 
Add `Shiniori-Raws` to the `Anime Raws` CF for both Sonarr and Radarr.

feat(starr-anime): add Shiniori-Raws to Anime Raws CF

---

docs/json/radarr/cf/uhd-bluray-tier-03.json

To add PTer to Radarr UHD Bluray Tier 03, resolving #1612 
Modify the Radarr UHD Bluray Tier 03 custom format to add an optional Release Group match for `PTer`
None

feat(Radarr): Add PTer to Radarr UHD Bluray Tier 03

---

docs/json/radarr/cf/lq-release-title.json
docs/json/radarr/cf/lq.json
docs/json/sonarr/cf/lq.json

- KC: Uses "Ai" ambiguously in release titles
- SHD: Incorrect DV profile usage and incompatible file containers (.ts)
- VECTOR: Uses user-generated dynamic HDR metadata with DaVinci Resolve
- GalaxyRG: Also added to LQ (Release Title) as some releases are badly formatted
- DepraveD: Also added to Sonarr LQ as some TV releases identified
Resolve:
- #2002
- #2020
- #2021 
- #2022 
Add the following groups to LQ as follows:
- KC: Uses "Ai" ambiguously in release titles
- SHD: Incorrect DV profile usage and incompatible file containers (.ts)
- VECTOR: Uses user-generated dynamic HDR metadata with DaVinci Resolve
- GalaxyRG: Also added to LQ (Release Title) as some releases are badly formatted
- DepraveD: Also added to Sonarr LQ as some TV releases identified
None

feat(guide): Add Groups to LQ

---

docs/json/radarr/cf/upscaled.json
docs/json/sonarr/cf/upscaled.json

Fix the `Upscaled` CF not matching on certain release naming.
Adjust regex to match on `Upscaleregrade` and variations of it. Additionally added a condition for `AIUS`. Also adjusted the regex for `AI Upscales` to prevent false positives, regex examples for those here:
- [Radarr](https://regex101.com/r/RinDcg/latest)
- [Sonarr](https://regex101.com/r/mpMFKR/latest)

fix(starr): Upscaled CF not matching on certain naming

---

docs/Downloaders/Deluge/Tips/Thin-Client.md

clarification on the thin-client setup requiring installation on a second computer where you will be managing Deluge from

update(downloaders/deluge): clarify process of setting up thin-client

---

docs/json/radarr/cf/anime-lq-groups.json
docs/json/radarr/cf/anime-raws.json
docs/json/sonarr/cf/anime-lq-groups.json
docs/json/sonarr/cf/anime-raws.json

Adding raw groups like Moozzi2 and ReinForce to the Anime Raws CF
Add the above to the CFs and remove Moozzi2 from the Anime LQ CF for better classification

feat(starr-anime): add Moozzi2 and Reinforce to Anime Raws CF

---

docs/json/radarr/quality-size/movie.json
docs/json/radarr/quality-size/sqp-uhd.json

To maintain compatibility with Radarr after it merges an increase to the quality definition ranges - namely that `2000` is now 'Unlimited' where `400` was the previous value.
In the Radarr quality definitions JSON
- Change `399` to `1999` for preferred quality
- Change `400` to `2000` for max quality
None

fix(radarr): Increase preferred and maximum Radarr quality definition sizes

---

docs/json/sonarr/quality-size/anime.json
docs/json/sonarr/quality-size/series.json

To maintain compatibility with Sonarr after it merges an increase to the quality definition ranges - namely that `1000` is now 'Unlimited' where `400` was the previous value.
In the Sonarr quality definitions JSON
- Change `395` to `995` for preferred quality
- Change `400` to `1000` for max quality
None

fix(sonarr): Increase preferred and maximum Sonarr quality definition sizes

---

docs/Hardlinks/Hardlinks-and-Instant-Moves.md

@mynameisbogdan requested in Radarr discord if the hardlinks limitations could be always seen because some people can't be bothered to `Click to show/hide`  or read the FAQ in general.
Make it always visible

feat(guide): Hardlinks FAQ - Always show the limitations

---

docs/json/radarr/cf/anime-dual-audio.json
docs/json/sonarr/cf/anime-dual-audio.json

Remove unnecessary slashes as well
Adding Korean language to anime dual audio to handle a few cases like Tower of God. Also removing unnecessary slashes to make the dual audio easier to read
Adding Korean to the Sonarr and Radarr CF

feat(starr-anime): Add Korean to Anime Dual Audio

---

.github/workflows/mkdocs_bug_prevent.yml

Regex for `[[` in changed json and fail.
This is due to `[[` breaking the macro in mkdocs
Ref
- https://github.com/TRaSH-Guides/Guides/commit/38dac49f48ce12638742b0ea206c13c0602cc9c8

ci: prevent mkdocs macro issue

---

docs/json/radarr/cf-groups/movie-versions.json

new movies group to not required / optional

fix(guides): Adjust movie versions json files to make each individual custom format non-required (2/2)

---

docs/json/radarr/cf/web-tier-01.json
docs/json/radarr/cf/web-tier-02.json
docs/json/sonarr/cf/web-tier-01.json
docs/json/sonarr/cf/web-tier-02.json

After receiving several pieces of information and having a discussion with the team, we have decided to move RlsGrp `Kitsune` from `WEB Tier 02` to `WEB Tier 01`
Moved RlsGrp `Kitsune` from `WEB Tier 02` to `WEB Tier 01`

feat(guide): Move RlsGrp `Kitsune` from `WEB Tier 02` to `WEB Tier 01`

---

docs/Downloaders/SABnzbd/Basic-Setup.md

Lately, more and more releases have shown up with files included that can potentially be abused or exploited when triggered. According to the reports gathered, they are mainly scene releases that appear on Usenet and public trackers.
>[!TIP]
>If you encounter them, please report them to your indexers. If they ignore you, remove those indexers from your list.
> [!NOTE]
>The Starr apps focus solely on media files and usually ignore all other extensions.
Added cleanup list to prevent unwanted extensions (thanks to @thezoggy for providing this list)

feat(guide): Downloaders - Add SABnzb cleanup list to prevent unwanted extensions

---

docs/json/radarr/cf-groups/misc-uhd-optional.json
docs/json/radarr/cf-groups/sqp-2-3-4-5-misc-optional.json

Add missing HDR10+ Boost and DV HDR10+ Boost custom formats to profile JSONs.
Add missing HDR10+ Boost and DV HDR10+ Boost custom formats to profile JSONs.
None

fix(guides): Add missing HDR10+ Boost and DV HDR10+ Boost custom formats to profile JSONs

---

docs/Sonarr/Sonarr-Quality-Settings-File-Size.md
docs/json/sonarr/quality-size/anime.json

Add missing Bluray-576p quality to quality settings JSON and guide

fix(sonarr): Add Bluray-576p quality filesize settings for Anime

---

docs/Radarr/Radarr-collection-of-custom-formats.md
docs/Sonarr/sonarr-collection-of-custom-formats.md
docs/json/radarr/cf/vc-1.json
docs/json/sonarr/cf/vc-1.json
includes/cf-descriptions/vc-1.md

Some hardware media player devices like the AppleTV have issues playing 1080p Bluray Remuxes.
Added: Custom Format `VC-1` to Sonarr/Radarr collection table

feat(guide): Starr - Add Custom Format `VC-1`

---

docs/Downloaders/.pages
docs/Downloaders/3rd-party-tools.md
docs/Downloaders/qBittorrent/.pages
mkdocs.yml

This way, it’s just third-party tools relevant to downloaders, not just to qBittorrent.
Moved the third-party tools section out of the qBittorrent section and put it in the downloaders root section.

feat(guide): Move the third-party tools section out of the qBittorrent section and put it in the downloaders root section

---

docs/json/radarr/cf/anime-bd-tier-02-seadex-muxers.json
docs/json/sonarr/cf/anime-bd-tier-02-seadex-muxers.json

Add Moxie to the anime tiers due to high quality BD remuxes
Added to the json files

feat(starr-anime): Add Moxie to anime bd tier 2

---

docs/json/radarr/cf/anime-bd-tier-01-top-seadex-muxers.json
docs/json/radarr/cf/anime-bd-tier-02-seadex-muxers.json
docs/json/sonarr/cf/anime-bd-tier-01-top-seadex-muxers.json
docs/json/sonarr/cf/anime-bd-tier-02-seadex-muxers.json

Add SoM to Anime BD Tier 1 and Cunnysseur to Anime BD Tier 2
Edit the CF JSON files

feat(starr-anime): Add SoM and Cunnysseur to Anime BD Tiers

---

docs/Downloaders/SABnzbd/scripts/index.md

Added prerequisites for better understanding the following steps. It should be clearer now that the user needs to create a scripts folder and has to select it inside the settings.
Improved information  base for lesser-techie users.
From the user perspective, I had the issue to understand where to put the scripts. I tried to solve this by adding helpful informations and links to the official SABnzbd  KB.
Nothing to do here

feat(guides): SABnzbd - Updated description for utilizing the scripts folder

---

docs/json/radarr/cf/10bit.json

Fix incorrect score for 10-bit custom format under new SQP-1 WEB (1080p) profile.
- Add SQP-1 WEB (1080p) score for 10-bit custom format
None

fix(guide): Add SQP-1 WEB (1080p) score for 10-bit custom format

---

docs/json/sonarr/quality-profiles/web-2160p.json

The Sonarr 2160p QP JSON was missing the AMZN CF ID, which is required for syncing to external sync tools.
Added the AMZN ID to the Sonarr 2160p QP JSON

fix(backend): Add missing AMZN from Sonarr 2160p QP JSON

---

schemas/specs/language-spec.json

Fix `exceptLanguage` not being allowed in Custom Format jsons.
Add `exceptLanguage` to the allowed `fields` types as a `boolean` value.

fix(ci): allow exceptLanguage in CF schema validation

---

docs/Downloaders/3rd-party-tools.md
docs/File-and-Folder-Structure/How-to-set-up/Unraid.md
docs/File-and-Folder-Structure/How-to-set-up/Windows.md
docs/File-and-Folder-Structure/Replace-copies-with-hardlinks.md

Consistency in the wording of `hardlinks` vs `hard links`
Checked the consistency in the wording of `hard links` vs. `hardlinks`; we went with `hardlinks` because the Starr apps use `hard links`, and the guide is based on the Starr apps. (See message at the bottom)
Sections where the GUI shows `hard links` we left as `hard links`.
I received the following reply, and I think this might be the best option.
```
i think the bigger point than grammar with this particular instance is the colloquial usage and acceptance of the term as "hardlink"
given that, for the purpose and entire point of your guide being generally arr related, they've set the stage of it being hardlink
i would go with that.
its not always a matter of being "technically grammar correct"
as much as being consistent, making …
```

style(guide): Consistency in the wording of `hardlinks` vs `hard links`

---

docs/Radarr/radarr-setup-quality-profiles-german-en.md

The MULTi Settings on Indexers is not needed for German releases as this Tag is not used. We need to remove it so it doesn't create false positives. 
Removed the MULTi Recommendation

fix(radarr): remove MULTI recommendation from German Guide

---

docs/json/radarr/cf/language-german.json

Apparently if Trackers report a file as German only and the title contains German.DL both the "German" CF as well as the "German DL (undefined)" CF are matching. Thats not desired.
Change the German CF to not match DL.

fix(radarr): Adapt German CF to avoid matching DL

---

docs/json/radarr/quality-profiles/german-hd-bluray-web.json
docs/json/radarr/quality-profiles/german-uhd-bluray-web-alternative.json
docs/json/radarr/quality-profiles/german-uhd-bluray-web.json
docs/json/radarr/quality-profiles/german-uhd-remux-web.json
docs/json/radarr/quality-profiles/hd-bluray-web.json
docs/json/radarr/quality-profiles/remux-web-1080p.json
docs/json/radarr/quality-profiles/remux-web-2160p.json
docs/json/radarr/quality-profiles/sqp-1-1080p.json
docs/json/radarr/quality-profiles/sqp-1-2160p.json
docs/json/radarr/quality-profiles/sqp-1-web-1080p.json
docs/json/radarr/quality-profiles/sqp-2.json
docs/json/radarr/quality-profiles/sqp-3.json
docs/json/radarr/quality-profiles/sqp-4.json
docs/json/radarr/quality-profiles/sqp-5.json
docs/json/radarr/quality-profiles/uhd-bluray-web.json

Add upcoming QP language option for the 3rd party sync apps.
- Add upcoming QP language option for the 3rd party sync apps
- Fixed: wrong max score for the German Quality Profiles
- Fixed inconsistent in one of the Quality Profiles

chore(guide): Add upcoming QP language option for the 3rd party sync apps

---

includes/german-guide/radarr-german-unwanted-en.md

Upscaled, AV1 and Extras were missing in the unwanted section of the German Guide
Added the missing CFs

fix(radarr): Add missing entries to unwanted section of the german guide

---

docs/json/radarr/cf/anime-bd-tier-03-seadex-muxers.json
docs/json/sonarr/cf/anime-bd-tier-03-seadex-muxers.json

Require remux in NAN0 condition to prevent grabbing their full BR-DISKs
https://regex101.com/r/52pyIx/1

feat(starr-anime): Require remux in title for NAN0

---

docs/Radarr/radarr-setup-quality-profiles-anime.md
docs/Sonarr/sonarr-setup-quality-profiles-anime.md

Removes references to animebytes.tv from "Quality Profiles Anime" guides. We do not accept new members and have found that a lot of new users are approaching us in attempt to create account after discovering our site from this guide.
Simply removes reference to site from guide text; left public Nyaa as-is.

chore(cleanup): remove reference to animebytes.tv

---

docs/json/radarr/cf/anime-dual-audio.json
docs/json/sonarr/cf/anime-dual-audio.json

Update Anime Dual Audio Custom Format with ability to parse Dual VARYG as well
Due to DUAL VARYG file naming it doesn't match default Dual Audio regex, with tweaked regex it works just fine
```
BLEACH.Thousand.Year.Blood.War.S01E36.BABY.HOLD.YOUR.HAND.2.NEVER.ENDING.MY.DREAM.1080p.DSNP.WEB-DL.AAC2.0.H.264.DUAL-VARYG.mkv
```
doesn't meat dual audio format regext:
where new regex handles it well:
None

fix(starr):  add DUAL-VARYG to Dual Audio Custom Anime Format

---

docs/json/radarr/cf/german-bluray-tier-01.json
docs/json/radarr/cf/german-bluray-tier-02.json
docs/json/radarr/cf/german-bluray-tier-03.json

If a group is in the Bluray and the Remux Tiers we have double scoring.
Add a negated remux condition to the bluray groups.

fix(radarr): German Guide - add negated remux quality modifier to bluray groups to avoid double scoring

---

docs/Radarr/Radarr-collection-of-custom-formats.md
docs/Radarr/radarr-setup-quality-profiles-german-en.md
docs/json/radarr/cf/language-not-german-english.json
docs/json/radarr/quality-profiles/german-hd-bluray-web.json
docs/json/radarr/quality-profiles/german-uhd-bluray-web-alternative.json
docs/json/radarr/quality-profiles/german-uhd-bluray-web.json
docs/json/radarr/quality-profiles/german-uhd-remux-web.json
includes/cf-descriptions/language-not-german-english.md
includes/german-guide/radarr-german-audio-version-en.md

1. We want to explain why we use 25k as the max CF score
2. We need a CF to avoid releases which do not contain German or English Audio
Added paragraph to address 1 
Added "Not English or German" CF to address 2

feat(radarr): German Guide - add "not english or german" CF and explanation for the max CF score

---

docs/json/radarr/quality-profiles/german-hd-bluray-web.json
docs/json/radarr/quality-profiles/german-uhd-bluray-web-alternative.json
docs/json/radarr/quality-profiles/german-uhd-bluray-web.json
docs/json/radarr/quality-profiles/german-uhd-remux-web.json

This is a test to solve an error when you try to add a new QP to your Starr app with Notifiarr. Perhaps we should just add it to the JSON for future reference/changes and to be consistent.
Added `MinUpgradeFormatScore` to a QP JSON.

chore(backend-test): add `MinUpgradeFormatScore` for the 3rd party sync apps

---

docs/Guide-Sync/index.md

Add Configarr to 3rd party Guide-Sync tools. https://github.com/raydak-labs/configarr

feat(guide): add Configarr to 3rd party Guide Sync tools

---

docs/json/radarr/cf/german-lq.json
docs/json/radarr/cf/german-scene.json

Add RILE and W4K to the German Scene CF
Add AVTOMAT to German LQ for stealing from WAYNE
Add the Groups to the CF

fix(radarr): Add RILE and W4K to German Scene; AVTOMAT to German LQ

---

docs/json/radarr/cf/german-bluray-tier-01.json
docs/json/radarr/cf/german-web-tier-01.json

The renowned German group ZeroTwo has a couple of aliases which need to be added to the German Tiers.
Add the aliases into the German Bluray and Web Tier 01, to have aliases more easily maintainable we decided to add them into one condition called ZeroTwo Aliases.

feat(radarr): add ZeroTwo aliases to German Tier 01 CFs

---

docs/json/radarr/cf/german-bluray-tier-01.json
docs/json/radarr/cf/german-web-tier-01.json
docs/json/sonarr/cf/german-bluray-tier-01.json
docs/json/sonarr/cf/german-web-tier-01.json

Fix JSON error in the German Custom Formats.
Fixed the JSON error in the Custom Formats/
If `\b`, then the JSON needs `\\b`

fix(guide-german): JSON error in the Custom Formats

---

docs/json/radarr/cf/german-bluray-tier-03.json
docs/json/radarr/cf/german-lq.json
docs/json/radarr/cf/german-scene.json
docs/json/sonarr/cf/german-bluray-tier-01.json
docs/json/sonarr/cf/german-lq.json
docs/json/sonarr/cf/german-scene.json
docs/json/sonarr/cf/german-web-tier-01.json

- ENDSTATiON, PL3X, HDARCHiV, WATCHABLE to German Scene
- iSSEYMiYAKE to German LQ - Reason: using LD without putting it into the Release Name (see:`Terrifier.3.2024.German.DL.AC3D.1080p.AMZN.WEB.H264-iSSEYMiYAKE`) 
- LeetHD to German Tier 03
- D02KU to ZeroTwo Alias Condition
Add the Groups to the appropriate CFs

fix(starr): add more Groups to German Tier CFs

---

includes/german-guide/radarr-german-unwanted-en.md
includes/german-guide/sonarr-german-unwanted-en.md

The Information about Bad Dual Groups and Scene is already in the "Misc Optional" section, additional this paragraph confused more than it helped so we decided to remove it.
Remove the paragraph from the Sonarr and Radarr Guide.

fix(starr): Remove duplicate information about Bad Dual Groups and Scene from the German Guides

---

docs/Sonarr/.pages

The order of the elements was different between the Radarr and Sonarr section, this was driving me insane 😆 
Align the navigation to have the same order.

fix(guide): Align navigation to be the same between radarr and sonarr section.

---

CONTRIBUTING.md

Added mandatory todo for `Quality Profiles` to `CONTIBUTING.md`
When creating a new quality profile or editing an existing one, it's mandatory to ensure that these settings are updated/added to the following locations for the third-party sync apps.
Added mandatory todo for `Quality Profiles` to `CONTIBUTING.md`

chore(backend): Added mandatory todo for `Quality Profiles` to `CONTIBUTING.md`

---

docs/json/radarr/cf/anime-bd-tier-05-remuxes.json
docs/json/sonarr/cf/anime-bd-tier-05-remuxes.json
docs/json/sonarr/cf/bilibili.json

Enhance Bilibili to match on BILI and add PMR and CRUCiBLE to Anime Remux Tiers due to a higher number of best releases on SeaDex from those groups
Needed to ensure PMR matches on Remux only to prevent matches on their BMDV and misc releases

feat(starr-anime): Enhance Bilibili Streaming Service and Remux Tier CFs

---

CONTRIBUTING.md

Because the changelog is created automatically, we want to make the PR name as clear and consistent as possible.
Added PR naming information to the CONTRIBUTING.md

chore(backend): Added PR naming information to the CONTRIBUTING.md

---

docs/Radarr/Radarr-collection-of-custom-formats.md
docs/Sonarr/sonarr-collection-of-custom-formats.md
includes/cf-descriptions/1080p.md
includes/cf-descriptions/2160p.md
includes/cf-descriptions/720p.md
includes/german-guide/radarr-cf-german-resolution-scoring-en.md
includes/german-guide/radarr-cf-german-resolution-scoring-hd-only-en.md
includes/german-guide/sonarr-cf-german-resolution-scoring-en.md
includes/german-guide/sonarr-cf-german-resolution-scoring-hd-only-en.md
includes/sqp/hd-radarr-resolution.md
includes/sqp/uhd-radarr-resolution.md

Added Custom Format to boost 720p, 1080p, and/or 2160p releases. These are only useful if you use [Merge Qualities](https://trash-guides.info/Radarr/Tips/Merge-quality/) in your Quality Profile.
Added Custom Format to boost 720p, 1080p and/or 2160p releases

feat(starr): Added Custom Format to boost 720p, 1080p and/or 2160p releases

---

docs/json/radarr/cf/hdr-undefined.json
docs/json/radarr/cf/hdr.json
docs/json/radarr/cf/hdr10.json
docs/json/radarr/cf/hlg.json
docs/json/radarr/cf/pq.json
docs/json/sonarr/cf/hdr-undefined.json
docs/json/sonarr/cf/hdr.json
docs/json/sonarr/cf/hdr10.json
docs/json/sonarr/cf/hlg.json
docs/json/sonarr/cf/pq.json

To fix an incorrect regex for HDR10.
Use a negative lookahead condition to properly exclude +/Plus from matching
None

fix(Starr): Fix HDR10 regex to correctly exclude +/Plus

---

docs/json/radarr/cf/german-bluray-tier-01.json
docs/json/radarr/cf/german-bluray-tier-03.json
docs/json/radarr/cf/german-lq.json
docs/json/radarr/cf/german-remux-tier-01.json
docs/json/radarr/cf/german-remux-tier-02.json
docs/json/radarr/cf/german-scene.json
docs/json/radarr/cf/german-web-tier-01.json
docs/json/sonarr/cf/german-bluray-tier-01.json
docs/json/sonarr/cf/german-bluray-tier-03.json
docs/json/sonarr/cf/german-lq.json
docs/json/sonarr/cf/german-remux-tier-02.json
docs/json/sonarr/cf/german-scene.json
docs/json/sonarr/cf/german-web-tier-01.json
docs/json/sonarr/cf/german-web-tier-03.json

German Tier update
Add Groups to CFs

feat(starr-german): German Tier update

---

docs/Radarr/Radarr-collection-of-custom-formats.md
docs/json/radarr/cf/sing-along-versions.json
docs/json/radarr/quality-profiles/hd-bluray-web.json
docs/json/radarr/quality-profiles/remux-web-1080p.json
docs/json/radarr/quality-profiles/remux-web-2160p.json
docs/json/radarr/quality-profiles/sqp-1-1080p.json
docs/json/radarr/quality-profiles/sqp-1-2160p.json
docs/json/radarr/quality-profiles/sqp-1-web-1080p.json
docs/json/radarr/quality-profiles/sqp-2.json
docs/json/radarr/quality-profiles/sqp-3.json
docs/json/radarr/quality-profiles/sqp-4.json
docs/json/radarr/quality-profiles/sqp-5.json
docs/json/radarr/quality-profiles/uhd-bluray-web.json
includes/cf/radarr-unwanted-uhd.md
includes/cf/radarr-unwanted.md
includes/sqp/radarr-unwanted-sqp1.md
includes/sqp/radarr-unwanted-uhd-sqp1.md

Provide a way for Sing-Along versions of movies to be matched and blocked
Resolve #2234 
None

feat(radarr): Add new Sing-Along Versions custom format

---

docs/json/radarr/cf/anime-bd-tier-02-seadex-muxers.json
docs/json/sonarr/cf/anime-bd-tier-02-seadex-muxers.json

Add DemiHuman to Anime BD Tier 02 since almost all of their releases are marked as best on SeaDex
Standard anime regex

feat(starr-anime): Add DemiHuman to Anime BD Tier 02

---

docs/json/radarr/cf-groups/advanced-audio-formats.json

Add HD audio formats for the remux profiles.
Removed the profiles from the HD audio formats group that should have HD Audio formats included.

fix(guide-sync): Add HD audio formats for the remux profiles

---

docs/json/radarr/cf/black-and-white-editions.json

The B&W edition CF had a few conditions that matched after year only, but some of the other conditions were generic, causing it to match on movie titles such as the below.
Extend the regex to match after year to each condition

feat(radarr): Only match B&W edition after year

---

.github/workflows/deploy-pr.yml

Fix some minor issues with `Branch Preview URL` and `Lastest Commit` not displaying the correct values in the comment.
Adjust used secret for getting the commit hash and use `pages-deployment-alias-url` returned by the cloudflare wrangler to get the branch preview url.

ci(gha): fix PR building comment isses

---

docs/json/radarr/cf/retags.json
docs/json/sonarr/cf/retags.json

Add `EZTVx.to`, `eztv.io`, (etc.) to the Retags Custom Format
Added `EZTVx.to`, `eztv.io`, (etc.) to the Retags Custom Format

feat(starr): Add `EZTVx.to`, `eztv.io`, (etc.) to the Retags Custom Format

---

docs/json/sonarr/cf/lq-release-title.json
includes/german-guide/radarr-german-unwanted-en.md
includes/german-guide/sonarr-german-unwanted-en.md

The CF `LQ (release title)` was missing in the german guide, it could be helpful for users who also want to get english releases.
Add the CF to the Guide.

feat(starr-german): add LQ (release title) CF to the german guide

---

docs/json/sonarr/cf/french-anime-tier-03.json

The CF kazuizui is updated to match kazuizui and kazui (Who's his old name)

fix(sonarr-french): CF on FR Anime Tier 3 (kazuizui)

---

docs/json/radarr/cf/anime-bd-tier-03-seadex-muxers.json
docs/json/sonarr/cf/anime-bd-tier-03-seadex-muxers.json

CRUCiBLE is a common dictionary word, so need to limit the regex to only match anime group patters
Use narrower regex

feat(starr-anime): Fix CRUCiBLE regex

---

docs/json/radarr/cf/german-bluray-tier-01.json
docs/json/radarr/cf/german-lq-release-title.json
docs/json/radarr/cf/german-microsized.json
docs/json/radarr/cf/german-remux-tier-01.json
docs/json/radarr/cf/german-scene.json
docs/json/sonarr/cf/german-lq-release-title.json
docs/json/sonarr/cf/german-microsized.json
docs/json/sonarr/cf/german-scene.json
docs/json/sonarr/cf/german-web-tier-02.json

feat(starr-german): Add Groups to German Tiers

---

docs/requirements.txt

Reverts TRaSH-Guides/Guides#2270
Reverting due to potential breaking changes to the PR banner

Revert "build(deps): bump mkdocs-material from 9.6.1 to 9.6.3"

---

docs/json/sonarr/cf/lq-release-title.json

- Add CREATiVE24 to Sonarr lq-release-title custom format
- Address #2258

feat(sonarr): Add CREATiVE24 to Sonarr LQ (Release Title) CF

---

docs/json/radarr/cf/language-german.json
docs/json/sonarr/cf/language-german.json

Fix double scoring recently brought up in [Discord](https://discord.com/channels/492590071455940612/1320818257581838376/1339861976473403434)
Make DL Tag required and negated for the German Language CF to avoid double scoring.

fix(starr-german): Make DL Tag required and negated for the German Language CF to avoid double scoring.

---

docs/Misc/x265-4k.md
includes/docker/x265.md

Updated the `x265-4k` aka `The Golden Rule`
Updated the `x265-4k` aka `The Golden Rule`
Added Admonitions box
```
Many people think that TRaSH Guides dislikes x265 releases. We DO NOT. We simply dislike the reasoning behind why most x265 groups and users use them.
```

feat(misc): Updated the `x265-4k` aka `The Golden Rule`

---

docs/json/radarr/cf/anime-bd-tier-05-remuxes.json
docs/json/sonarr/cf/anime-bd-tier-05-remuxes.json

Right now, PMR regex requires it to be in the front of the filename due to requiring REMUX after it, so I added an option for REMUX to come first and PMR at end so it can match both filenames below
`[PMR] The Eminence in Shadow Season 2 (BD Remux 1080p AVC FLAC) [Dual Audio]`
`The Eminence in Shadow - S02E01 (BD Remux 1080p AVC FLAC) [Dual Audio] [PMR].mkv`
Just created the same regex as flipped and allowed condition to match on either

feat(starr-anime): Fix PMR regex to match if at end of filename

---

docs/json/radarr/cf/anime-lq-groups.json
docs/json/sonarr/cf/anime-lq-groups.json

shincaps posts raw tv footage at low quality or `.ts` files, so need to add them at LQ quality
Just add them to anime LQ CF

feat(starr-anime): Add shincaps to Anime LQ Groups

---

docs/json/radarr/cf/hd-bluray-tier-03.json
docs/json/radarr/cf/remux-tier-03.json
docs/json/radarr/cf/web-tier-03.json

Update the Radarr tiers with new 'known-good' groups

feat(radarr): Update Radarr Tiers

---

docs/json/radarr/cf/scene.json
docs/json/sonarr/cf/scene.json

To amend the Scene custom formats so they do not match the majority of German language releases
Fix #2289 
Add `Not GERMAN` conditions to the Radarr and Sonarr Scene custom formats.

fix(starr): SCENE custom formats matching most German language releases.

---

includes/cf-descriptions/aac.md
includes/cf-descriptions/atmos-undefined.md
includes/cf-descriptions/dd.md
includes/cf-descriptions/ddplus-atmos.md
includes/cf-descriptions/ddplus.md
includes/cf-descriptions/dts-es.md
includes/cf-descriptions/dts-hd-hra.md
includes/cf-descriptions/dts-hd-ma.md
includes/cf-descriptions/dts-x.md
includes/cf-descriptions/dts.md
includes/cf-descriptions/flac.md
includes/cf-descriptions/mp3.md
includes/cf-descriptions/opus.md
includes/cf-descriptions/pcm.md
includes/cf-descriptions/truehd-atmos.md
includes/cf-descriptions/truehd.md

Add details in the audio Custom Formats description specifying which format is lossy or lossless.
Added details in the audio Custom Formats description specifying which format is lossy or lossless.
Here's a breakdown of whether each format is **lossy** or **lossless**:  
- **TrueHD ATMOS** (Dolby TrueHD with Atmos – **lossless**)  
- **TrueHD** (Dolby TrueHD – **lossless**)  
- **DTS-HD MA** (DTS-HD Master Audio – **lossless**)  
- **FLAC** (Free Lossless Audio Codec – **lossless**)  
- **PCM** (Pulse Code Modulation – **lossless, uncompressed**)  
- **DTS X** (**Can be either lossy or lossless** depending on the underlying codec, usually DTS-HD MA for lossless or DTS-HD HRA for lossy.)  
- **ATMOS (undefined)** (Atmos is an object-based audio format that can be paired with **lossless …

feat(starr): Add details in the audio Custom Formats description specifying which format is lossy or lossless.

---

docs/json/sonarr/cf/web-tier-02.json

Fix an incorrect score in the Sonarr web tier 02 for anime-sonarr
Fix #2163

fix(sonarr): update sonarr web tier 02 anime-sonarr score to 250

---

docs/json/radarr/cf/crav.json
docs/json/radarr/cf/hbo.json
docs/json/radarr/cf/hmax.json
docs/json/radarr/cf/it.json
docs/json/radarr/cf/itvx.json
docs/json/radarr/cf/max.json
docs/json/radarr/cf/now.json
docs/json/radarr/cf/stan.json
docs/json/radarr/cf/tving.json
docs/json/radarr/cf/viu.json
docs/json/sonarr/cf/cc.json
docs/json/sonarr/cf/crav.json
docs/json/sonarr/cf/dscp.json
docs/json/sonarr/cf/hbo.json
docs/json/sonarr/cf/hmax.json
docs/json/sonarr/cf/it.json
docs/json/sonarr/cf/itvx.json
docs/json/sonarr/cf/max.json
docs/json/sonarr/cf/now.json
docs/json/sonarr/cf/red.json
docs/json/sonarr/cf/sho.json
docs/json/sonarr/cf/stan.json
docs/json/sonarr/cf/tving.json
docs/json/sonarr/cf/viu.json

It seems that some streaming services' custom formats no longer matched after the rename, and when renamed a second time, they lost the streaming services completely.
Improve streaming services recognition after renaming.

feat(starr): Improve streaming services recognition after renaming.

---

docs/json/radarr/cf/hd-bluray-tier-02.json

Resolve an issue where the sync tools would pull the wrong score for HD Bluray Tier 02
Add missing SQP-1 (2160p) score for HD Bluray Tier 02
None

fix(radarr): Add missing SQP-1 (2160p) score for HD Bluray Tier 02

---

docs/json/sonarr/cf-groups/season-packs.json
docs/json/sonarr/cf/season-pack.json

Add Season Pack to Sonarr Profile Groups

feat(guide-sync): Add Season Pack to Sonarr Profile Groups

---

docs/json/radarr/quality-profiles/anime-remux-1080p.json
docs/json/sonarr/quality-profiles/anime-remux-1080p.json

Add missing quality sources for the new  Anime profiles.
Add missing quality sources for the new  Anime profiles.

fix(guide-sync): Add missing quality sources for the new  Anime profiles

---

docs/json/radarr/cf-groups/optional-movie-versions.json
docs/json/radarr/quality-profiles/anime-remux-1080p.json
docs/json/sonarr/quality-profiles/anime-remux-1080p.json

Add group exclusion for the anime profiles.
Add group exclusion for the anime profiles.

fix(guide-sync): Add group exclusion for the anime profiles

---

docs/json/radarr/quality-profiles/anime-remux-1080p.json
docs/json/sonarr/quality-profiles/anime-remux-1080p.json

After fixing the source name, I forgot to edit the cutoff name for the anime profiles.
Fixed the cutoff name for the anime profiles.

fix(guide-sync): cutoff name for the anime profiles

---

docs/json/radarr/cf-groups/dv-hdr10-and-hdr10-boost.json

It appeared that both [DV HDR10+ and HDR10+ Boost](https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/cf-groups/dv-hdr10-and-hdr10-boost.json) and [HDR Formats](https://github.com/TRaSH-Guides/Guides/blob/master/docs/json/radarr/cf-groups/hdr-formats.json) had the same trash_id
Created a new unique trash_id for the `DV HDR10+ and HDR10+ Boost` group

fix(guide-sync): corrected duplicate trash_id with two groups

---

docs/json/radarr/cf/lq.json
docs/json/sonarr/cf/lq.json

Add RlsGrp `FMD` to `LQ`
Does NF mobile 480p releases and mess it up with non-standard resolutions like 396p
Added RlsGrp `FMD` to `LQ` for Radarr and Sonarr

feat(starr): Add RlsGrp `FMD` to `LQ`

---

docs/Radarr/Radarr-collection-of-custom-formats.md
docs/Sonarr/sonarr-collection-of-custom-formats.md
includes/cf-descriptions/language-original-plus-french.md
includes/cf-descriptions/special-edition.md

Centralize the last descriptions on the Custom Format Collection page
Centralize the last descriptions on the Custom Format Collection page

feat(guide): Centralize the last descriptions on the Custom Format Collection page

---

docs/Sonarr/sonarr-collection-of-custom-formats.md

- Fixing markdown includes that are not rendering properly in the documentation.
- Ensuring that included content is embedded correctly rather than appearing as plain text.
- Adjusted include paths to ensure they point to the correct files and are formatted correctly

chore(sonarr): Fix markdown includes not rendering correctly for some custom formats

---

docs/json/radarr/cf/anime-bd-tier-03-seadex-muxers.json
docs/json/sonarr/cf/anime-bd-tier-03-seadex-muxers.json

Add Flugel to Anime BD Tier 03 due to having almost all of their releases listed on SeaDex
Just add alongside other top tier remux groups in tier 03

feat(starr-anime): Add Flugel to Anime BD Tier 03

---

docs/json/radarr/cf/bad-dual-groups.json
docs/json/sonarr/cf/bad-dual-groups.json
includes/cf-descriptions/bad-dual-groups.md

Inconsistent first audio track choice breaks automation tools such as Radarr and Sonarr.
Add RlsGrp `tokar86a` to the `Bad Dual Groups` Custom Format.

feat(starr): Add RlsGrp `tokar86a` to the `Bad Dual Groups` Custom Format

---

.pre-commit-config.yaml

Add a pre-commit config to rule out any errors in the most commonly edited files before even committing to the repo.
Add `.pre-commit-config.yaml` to the root of the repo and add json schema validation and yaml, markdown and editorconfig linting.

ci(pre-commit): add config

---

docs/json/radarr/cf/anime-lq-groups.json
docs/json/sonarr/cf/anime-lq-groups.json

Currently, Anime LQ groups includes the term `HR` which can match a language code. I made it more precise. Also fixed a typo in the Hitoku regex that I noticed
Used the anime-specific group regex we use for more common words

feat(starr-anime): Anime LQ Groups should only match HR as an anime group and correct Hitoku typo

---

docs/Downloaders/NZBGet/scripts/index.md
docs/Downloaders/SABnzbd/scripts/index.md

Fix #1976 
Add instruction to run `dos2unix` before executing python scripts in SABnzbd or NZBGet.

fix(downloaders): run dos2unix before executing

---

.github/labeler.yml
docs/recyclarr-configs/README.md
metadata.json
metadata.schema.json

Enough time has passed that I think we don't need these anymore. 
- Remove the "Area: Recyclarr" label from labeler.yml
- Delete the docs/recyclarr-configs/README.md file
- Remove recyclarr-related properties from metadata.json and its schema

chore(guide-sync): Remove Recyclarr config templates

---

docs/json/radarr/cf-groups/dv-hdr10-and-hdr10-boost.json

A certain profile wasn't able to enable the `DV HDR10+/HDR10+ Boost groups`  because it was excluded.
Remove the exclude from the `DV HDR10+/HDR10+ Boost` group.

fix(guide-sync): Remove the exclude from the `DV HDR10+/HDR10+ Boost` group.

---

docs/json/radarr/cf/lq.json
docs/json/sonarr/cf/lq.json

BEN THE MEN was already in LQ (Release Title) custom format. This PR adds BTM to LQ custom format as well. 
---
Update the LQ custom formats to add the BEN THE MEN (i.e. BTM) release group, as their release titles don't format the release group name properly, or include the quality of the release (e.g., Bluray, WEBDL etc). This results in the breaking of automation.
- Add the rlsgrp BTM to the LQ custom formats for Radarr and Sonarr.
None

feat(starr): Add BTM to LQ Custom Formats

---

docs/json/sonarr/cf-groups/release-groups-french.json

2 Issues detected in the file docs/json/sonarr/cf-groups/release-groups-french.json :
The ID name dbfc0a4b5cb4cbd693311c4482ae9683 is incorrect.
The ID 2f3422339d185eb227a324644a2fbfca (name: FR Scene Groups) is missing.
It's just fix the file

fix(sonarr-french): update cf-groups/release-groups-french.json

---

docs/json/radarr/cf/lq-release-title.json
docs/json/radarr/cf/lq.json

After conducting some research, we did not find any issues with their WEBDL, so we decided to remove them from the `LQ` and move them to the `LQ (Release Title)` while excluding them from matching on WEBDL.
The reason they are in `LQ (Release Title)` is that we received several reports indicating that their non-WEBDL versions do not use the best sources (R5) or they use custom discs, resulting in issues such as artifacting in dark scenes, etc.
Removed RlsGrp `PiRaTeS` from the CF `LQ` and moved them to the `LQ (Release Title)` while excluding them from matching on WEBDL.

feat(radarr): Do not match RlsGrp `PiRaTeS` when it is a WEB-DL

---

docs/json/radarr/cf/lq-release-title.json

Fix false positives for files on disk for `PiRaTeS` & `EVO` releases that are not a WEB-DL.
Change the regex to look for a word boundary in front of `WEB`.

fix(radarr): PiRaTeS & EVO LQ (Release Title) regex

---

docs/json/radarr/cf/hd-bluray-tier-01.json
docs/json/radarr/cf/web-tier-01.json

ZoroSenpai, take a 2160p WEB-DL sourced from a better source, for example, MA 4K, and create/encode a 1080p WEBRip that looks superior to the available Blu-ray 1080p.
Add `ZoroSenpai` to `HD Bluray Tier 01` and `WEB Tier 01`

feat(radarr): Add `ZoroSenpai` to `HD Bluray Tier 01` and `WEB Tier 01`

---

.github/workflows/lint-markdown.yml
.markdownlint.yaml

Fix the Markdown Lint GitHub Action.
Disable `MD036` and `MD059` markdownlint rules.

ci(markdownlint): disable MD036 and MD059 markdownlint rules

---

docs/json/radarr/cf/bad-dual-groups.json
docs/json/sonarr/cf/bad-dual-groups.json

This was a mistaken from my part. The groups also does correct "not dual" releases. 
Adding it to "bad dual groups" would harm those releases - since the CF does not filter only dual.
The group does web-dl so quality is not in question.
The group follows trackers rules and the dual releases that does not have "original language" as primary track are not spread, it is not an issue.
Apologies.
This reverts commit 21c554b403afe9ff5394e62ef9b2557003d847bb introduced in #2399

Revert "feat(starr): add `BiOMA` and `sh4down` to Bad Dual Groups

---

docs/json/radarr/cf/language-german.json
docs/json/sonarr/cf/language-german.json

When a tracker reports a file as german only and the title contains "German.ML" both the German and German DL (undefined) CF are matching. This should not be the case.
Change German CF to not match ML.

fix(starr-german): add ML to German CF to avoid matching ML

---

docs/Downloaders/NZBGet/Basic-Setup.md
docs/Downloaders/SABnzbd/Basic-Setup.md
includes/downloaders/unwanted-extensions.md

2 new file extensions sln and vcxproj have been linked to malware and there is no reason a NZB should ever contain this filetype. These filetypes should be blacklisted.
Add sln and vcxproj to the SABnzbd Unwanted Extensions List
- [ ✅] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [ ✅] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).

feat(downloaders): Add `sln` and `vcxproj` to the SABnzbd/NZBGet Unwanted Extensions List
