TRaSH-Guides/Guides

RadarrV3/Collection-of-Custom-Formats-for-RadarrV3.md
Fix: BLOCK1 through BLOCK4 (/b to \b)
Enhance: BLOCK1 "-YIFY" to "YIFY" (Reason: not always a dash in YIFY releases)
Add: BLOCK1 "YTS" (Reason: YIFY AKA)
Fix: Various Typos, add clarity
=> Various Fixes/Enhancements

RadarrV3/Collection-of-Custom-Formats-for-RadarrV3.md
Low Quality Releases should NOT be required
IMG update needed
=> Fix: Low Quality Releases should NOT be required

docs/Sonarr/V3/Sonarr-recommended-naming-scheme.md
Added {Preferred Words} to naming schemes in order to avoid download loop issues.
=> Add {Preferred Words} to naming schemes

docs/Misc/how-to-set-up-hardlinks-and-atomic-moves.md, docs/Radarr/index.md, docs/Sonarr/index.md
Fixed Changes for Radarrv3 to stable
=> Fixed Changes for Radarrv3 to stable

docs/Radarr/V3/Collection-of-Custom-Formats-for-RadarrV3.md
Added: HQ-P2P
Changed: Dolby Vision to Dovi for better naming
=> Added: HQ-P2P Changed: Dolby Vision to Dovi for better naming

docs/Misc/how-to-set-up-hardlinks-and-atomic-moves.md
=> Added: guide for plain docker

docs/Misc/how-to-set-up-hardlinks-and-atomic-moves.md
Added: Bare Metal (Native) Guide
=> Added: Bare Metal (Native) Guide

docs/Radarr/V3/Collection-of-Custom-Formats-for-RadarrV3.md
Fixed: DoVi (proper Dolby Vision recornizing)
=> Fixed: DoVi (proper Dolby Vision recornizing)

docs/index.md, docs/stylesheets/extra.css, mkdocs.yml
=> Added: pymdownx.highlight

docs/Misc/how-to-set-up-hardlinks-and-atomic-moves.md
- Updated: the Synology section with:
- Added link to a docker-compose-collection
- Added copy/paste option for adding the media sub folders
- Updated: the Docker section with:
- Added link to a docker-compose-collection
- Added copy/paste option for adding the data+media sub folders
- Added permissions settings
- Updated: Bare Metal - native section with:
- Added copy/paste option for adding the data+media sub folders
- Added permissions settings
=> Updated: How To Set Up Hardlinks and Atomic-Moves

README.md, docs/index.md, mkdocs.yml
- Changed: Donate/Support to buy me a coffee
- Added: Buy me a coffee to github readme
=> Buy me a coffee

docs/Misc/how-to-provide-a-docker-compose.md, docs/Misc/how-to-set-up-hardlinks-and-atomic-moves.md, docs/Radarr/V3/How-to-importexport-Custom-Formats-and-truly-make-use-of-it.md, docs/Radarr/V3/Radarr-recommended-naming-scheme.md, docs/index.md
Update: Maintenance cleanup
- Cleanup: fixed several spelling errors in several guides
=> Update: Maintenance cleanup

docs/index.md, overrides/main.html
Update: Maintenance release
- Fixed: https://github.com/TRaSH-/Guides/pull/67#issuecomment-748667475
Co-Authored-By: Eric Nemchik <eric@nemchik.com>
=> Maintenance release

docs/Radarr/V3/Collection-of-Custom-Formats-for-RadarrV3.md, docs/stylesheets/extra.css
Updated: Collection of Custom Formats for Radarr V3
- Added: Imax Custom Format thnx to rg9400
- Added: Return to TOP (Table index) after every Custof Format
- Changed: Redisign of the layout
- Changed: Right side TOC grouped in to categories
- Changed: Splitted Table in 2 parts for better readability.
- Changed: Table color thnx to mr.hotio for helping with the .css
Co-Authored-By: rg9400 <39887349+rg9400@users.noreply.github.com>
Co-Authored-By: mrhotio <26902309+mrhotio@users.noreply.github.com>
=> Updated: Collection of Custom Formats

docs/Radarr/V3/.pages, docs/Radarr/V3/Radarr-collection-of-custom-formats.md, mkdocs.yml
=> Testing Redirect

docs/Radarr/V3/Radarr-recommended-naming-scheme.md, docs/Sonarr/V3/Sonarr-recommended-naming-scheme.md
Some suggested phrasing & grammar updates.
=> Clarify grammar

README.md, docs/Bazarr/index.md, docs/Bazarr/scripts/2to3-language-code/README.md, docs/Misc/Discord-Notifier-Basic-Setup.md, docs/Misc/How-to-setup-Torguard-for-port-forwarding.md, docs/Misc/how-to-provide-a-docker-compose.md, docs/Misc/how-to-set-up-hardlinks-and-atomic-moves.md, docs/Misc/x265-4k.md, docs/NZBGet/How-to-setup-NZBGet.md, docs/NZBGet/scripts/Clean/README.md, docs/NZBGet/scripts/HashRenamer/README.md, docs/NZBGet/scripts/WtFnZb-Renamer/README.md, docs/Plex/Profiles/README.md, docs/Radarr/V3/Collection-of-Custom-Formats-for-RadarrV3.md, docs/Radarr/V3/How-to-importexport-Custom-Formats-and-truly-make-use-of-it.md, docs/Radarr/V3/Radarr-recommended-naming-scheme.md, docs/Radarr/index.md, docs/Sonarr/V3/Sonarr-Release-Profile-RegEx.md, docs/Sonarr/V3/Sonarr-recommended-naming-scheme.md, docs/Sonarr/index.md, docs/index.md
- Security Fixes: noopener noreferrer to external URL redirects
- Info: Tabnabbing, sometimes called reverse tabnabbing, is an exploit that uses the browser's default behavior with target="_blank" to gain partial access to your page through the window.object API.
With tabnabbing, a page that you link to could cause your page to redirect to a fake login page. This would be hard for most users to notice because the focus would be on the tab that just opened – not the original tab with your page.
Sources:
[LINK 1](https://www.freecodecamp.org/news/how-to-use-html-to-open-link-in-new-tab/)
[LINK 2](https://dev.to/ben/the-targetblank-vulnerability-by-example)
=> Security Fixes: prevent a type of phishing known as tabnabbing.

mkdocs.yml
=> thnx-fix-2

docs/Sonarr/V3/Sonarr-Release-Profile-RegEx-Anime.md, docs/Sonarr/V3/Sonarr-Release-Profile-RegEx.md
Updated: Sonarr - Release Profile RegEx (Anime)
- Fixed: Formatting to make it more clear when you need to use `Include Preferred when Renaming`
- Fixed: Formatting to make it more clear when to create 2 release profiles
- Fixed: Formatting to make it more clear when you need to use `Include Preferred when Renaming`
=> Sonarr rp rpa formatting

docs/Sonarr/V3/Sonarr-Release-Profile-RegEx-Anime.md
- Added a note for dubs.
- Merged a lot of options.
- Reorganized into a more organized structure.
- Verified more groups and added/removed some.
=> Complete Overhaul of Regex

.github/FUNDING.yml, README.md, docs/index.md, overrides/main.html
=> Move Coffee to 1 location

docs/index.md, mkdocs.yml
=> move-coffee-to-one-location-cleanup

LICENSE
=> Switched LICENSE to MIT

docs/Sonarr/V3/Sonarr-Release-Profile-RegEx.md
- Added: Word boundaries for every group because -FC matched with FCK
=> Updated: Sonarr - Release Profile RegEx (WEB-DL)

docs/Misc/how-to-set-up-hardlinks-and-atomic-moves.md
```yml
- Updated: Docker section with:
- Changed: Complete overhaul/cleanup.
- Fixed: Some formatting.
- Added: Suggestion to use DockSTARTer.
- Added: line breaks to make it more readable.
- Removed: docker-compose.yml
- Removed: docker-compose-collection.yml
- Updated: Synology section with:
- Changed: Complete overhaul/cleanup.
- Added: New easier to use docker-compose.yml.
- Added: .env file for the use with the new docker-compose.yml.
- Added: New template Repository for Synology section of this Guide.
- Added: Breakdown of the Folder Structure.
- Added: docker-compose commands cheat sheet.
- Added: line breaks to make it more readable.
- Removed: docker-compose-collection.yml.
- Updated: Unraid section with:
- Fixed: Some formatting.
- Added: line breaks to make it more readable.
- …
```
=> Updated: Misc - How To Set Up Hardlinks and Atomic-Moves

docs/Sonarr/V3/Sonarr-Release-Profile-RegEx-Anime.md
Updated: Sonarr - Release Profile RegEx (Anime)
- Added: A lot of groups to the lists. See here: (https://docs.google.com/spreadsheets/d/1UuQzmYojDQTeBfJs6XR3p7nDHz56pEOiyX5hdz4ZOmM/edit?usp=sharing)
- Changed: Scoring system to be more defined and upgradeable.
- Changed: Moved some of the groups around to account for discrepancies.
=> Sonarr anime regex

docs/Radarr/V3/Radarr-setup-custom-formats.md
```yml
- Added: Highlighted to disable proper/repack in Radarr
```
=> Updated: Radarr - How to setup Custom Formats

docs/Radarr/V3/Radarr-collection-of-custom-formats.md
```yml
- Added: RiffTrax to the Low Quality Releases CF in [BLOCK5]
```
=> Updated: Radarr - Collection of Custom Formats

docs/Bazarr/index.md, docs/Radarr/index.md, docs/Sonarr/index.md
Fixes the version badges so that they use the new repository location.
=> fix badge links

docs/Sonarr/V3/Sonarr-Release-Profile-RegEx-Anime.md
- Fixed: Easy format DO NOT WANT
=> Fixed the easy format

docs/Sonarr/V3/Sonarr-Quality-Settings-File-Size.md
```yml
- Changed: WEBDL-720p + WEBRip-720p lowered from 20 to 15 (for Ghost Nation,Blue Bloods)
```
=> Updated: Sonarr - Quality Settings (File Size)

docs/Radarr/V3/Tips/Radarr-rename-your-folders.md
```yml
- Fixed: Wrong URL to the naming scheme.
- Changed: Description.
- Added: Warming about running time and not to interrupt the process.
```
=> Updated: Radarr - Tips - How to rename your folders

docs/NZBGet/scripts/Clean/Clean.py
Started to run into "WRTEAM" and "CAPTCHA" in the wild.
=> 2 new suffixes for Clean.py

docs/Radarr/V3/Radarr-collection-of-custom-formats.md, docs/Sonarr/V3/Sonarr-Release-Profile-RegEx.md
```yml
Updated: Sonarr - Release Profile RegEx
- Added: ViSiON [100]
- Added: WRTEAM [-25] Optional (use these only if you dislike renamed and retagged releases)
- Added: CAPTCHA [-25] Optional (use these only if you dislike renamed and retagged releases)
- Updated: LQ - [BLOCK5]
- Added: RU4HD (Decode ATMOS/TrueHD to wavs, Re-encoded to DTS-HD MA)
- Added: HQ - [BLOCK4]
- Added: BHDStudio (Optimized for PLEX, emby, Jellyfin, and other streaming platforms, Downmixed Lossless audio track to Dolby Digital 5.1)
- Added: HQ - [Remux Groups]
- Added: PmP|-BLURANiUM|-SiCFoI|-SURFINBIRD
```
=> Maintenance release 20210318

docs/Sonarr/V3/Sonarr-Release-Profile-RegEx.md
```yml
Updated: Sonarr - Release Profile RegEx
- Added: ROCCaT [125]
```
=> Added: ROCCaT [125

docs/Misc/how-to-provide-a-docker-compose.md
Added: 0bin.net link
"A client side encrypted PasteBin"
All pastes are AES256 encrypted, we cannot know what you paste...
=> Added: 0bin.net link

docs/Radarr/V3/Radarr-collection-of-custom-formats.md
```yml
- Changed: [BR-DISK] Fixed wrong recognizing of files.
```
=> Changed: [BR-DISK] Fixed wrong recognizing of files.

docs/Notifiarr/Quick-Start.md, docs/manifest.webmanifest
Fixed: Fixed slash/backslash issue for image
=> Fixed slash/backslash issue for image

docs/Radarr/V3/Radarr-collection-of-custom-formats.md
```yml
- Added: trash_id for notifiarr CF sync and others.
```
=> Added: trash_id for notifiarr CF sync and others.

.gitattributes, docs/Sonarr/V3/Sonarr-Release-Profile-RegEx-Anime.md, docs/Sonarr/V3/Sonarr-Release-Profile-RegEx.md
- Added: trash_id for auto sync (WIP).
=> Added: trash_id for auto sync (WIP).

docs/Sonarr/V3/Sonarr-Release-Profile-RegEx.md
=> Added: Flux

docs/Radarr/V3/Radarr-collection-of-custom-formats.md
```yml
- Updated: BR-DISK - Better BR-DISK recornizing, Added BR-DISK Groups.
- Updated: Special Editions - Fixed Formatting
```
=> Radarr cf collection 20210417

docs/Sonarr/V3/Sonarr-Release-Profile-RegEx.md
```yml
- Added: HDR with a score of [10] to the optional
```
=> Added: HDR with a score of [10] to the optional

docs/Sonarr/V3/Sonarr-Release-Profile-RegEx.md
- Fixed: Issue while creating the guide and not being consistent with the scoring so it broke the sync
=> Fixed: Issue while creating the guide and not being consistent with the scoring so it broke the sync

docs/Radarr/V3/Radarr-collection-of-custom-formats.md
```yml
- Updated: [BR-DISK] - Better recornizing of VC-1/VC.1
- Changed: [Dolby Vision (no WEB-DL)] - Admonitions formatting change from info to danger/warning
- Fixed: [720/1080p no x265] - Typo.
```
=> Radarr cf collection 20210419

docs/Sonarr/V3/Sonarr-Release-Profile-RegEx.md
```yml
- Added: [rarbg] - To optional dislike renamed and retagged releases
```
=> Added: [rarbg] - To optional dislike renamed and retagged releases

docs/Radarr/V3/Radarr-collection-of-custom-formats.md
```yml
- Updated: [BR-DISK] - Added BR-DISK Group.
- Fixed: Formatting
```
=> Updated: [BR-DISK] - Added BR-DISK Group

docs/Sonarr/V3/Sonarr-Release-Profile-RegEx.md
```yml
- Added: [3cTWeB][playWEB] - With a score of [125]
```
=> Added: [3cTWeB][playWEB] - With a score of [125]

docs/Radarr/V3/Radarr-recommended-naming-scheme.md
```yml
Updated: Radarr - Recommended naming scheme
- Removed: Recommend ID in folder name.
- Added: Extra warning and description why it's not recommended to use ID in foldername.
```
=> Removed: Recommend ID in folder name.

docs/Sonarr/V3/Sonarr-recommended-naming-scheme.md
```yml
Updated: Sonarr - Recommened naming scheme
- Added: Optional Series Folder Format for the beta Plex TV Series Scanner
```
=> Added: Optional Series Folder Format for the beta Plex TV Series Scanner

docs/Radarr/V3/Radarr-collection-of-custom-formats.md
```yml
- Updated: [x264] - Cleaned up regex
- Updated: [x265] - Cleaned up regex
- Fixed: [BR-DISK] - Condition: BR-DISK Groups - Disabled Required (False)
```
=> Radarr cf collection 20210426

docs/Radarr/V3/Radarr-collection-of-custom-formats.md, docs/Radarr/V3/Radarr-setup-custom-formats.md
```yml
Updated: Radarr - How to setup Custom Formats
- Added: Short description - How Custom formats are implemented within and have their impact controlled by Quality Profiles
- Added: Quality Trumps All - Order
- Changed: FAQ to make them external link able
- Added: Quality Trumps All - Order
```
=> Radarr formatting layout

docs/Downloaders/Deluge/Deluge-Basic-Setup.md, docs/Downloaders/Deluge/Deluge-how-to-add-labels.md, docs/Downloaders/NZBGet/NZBGet-Basic-Setup.md, docs/Downloaders/SABnzbd/SABnzbd-Basic-Setup.md, docs/Downloaders/qBittorrent/qBittorrent-Basic-Setup.md, docs/Downloaders/qBittorrent/qBittorrent-how-to-add-categories.md, docs/Downloaders/ruTorrent/ruTorrent-Basic-Setup.md, mkdocs.yml
```yml
Renamed: How-to-setup-NZBGet.md => NZBGet-Basic-Setup.md - To stay consistent with the upcoming  the upcoming Guides
Added: Redirect of the old NZBGet to the new NZBGet location
Created: SABnzbd - Basic Setup Placeholder
Created: Deluge - Basic Setup Placeholder
Created: qBittorrent - Basic Setup Placeholder
Created: ruTorrent - Basic Setup Placeholder
Created: qBittorent - How to add categories - Placeholder
Created: Deluge - How to add labels - Placeholder
=> Downloaders 20210505

docs/Hardlinks/Check-if-hardlinks-are-working.md
Corrected command.
Earlier one would not run
=> Minor change

docs/Radarr/V3/Radarr-Quality-Settings-File-Size.md, docs/Sonarr/V3/Sonarr-Quality-Settings-File-Size.md
Clarifies meaning of 'as high as possible'
=> Added to note.

docs/Radarr/V3/Radarr-collection-of-custom-formats.md, docs/Radarr/scripts/hq-webdl.json, docs/Radarr/scripts/obfuscated.json
```yml
- Added: [Obfuscated] - Optional (use these only if you dislike renamed and retagged releases) - Recommended Score: [-9999]
- Added: [HQ-WEBDL] - A personal collection of P2P WEB-DL groups - Recommended Score [100] (Same as [HQ])
```
=> Radarr cf collection 20210523

docs/Radarr/V3/Radarr-collection-of-custom-formats.md, docs/json/radarr/dovi-webdl.json
```yml
- Changed: [DoVi (NoWEBDL)] - please read above what has been changed and how to make use of it and the scoring.
- Renamed: [DoVi (NoWEBDL)] => [DoVi (WEBDL)] - To match Radarr's naming for WEB-DL
- Renamed: [EVO (no WEB-DL)] => [EVO (no WEBDL)] - To match Radarr's naming for WEB-DL
```
=> Radarr cf collection 20210526

docs/json/radarr/3d.json
```yml
- Updated: [3d] - Better recornizing of 3D formats
```
=> Updated: [3d] - Better recornizing of 3D formats

docs/Notifiarr/Quick-Start.md, docs/Radarr/Radarr-import-custom-formats.md, docs/Radarr/Radarr-setup-custom-formats.md, docs/Sonarr/Sonarr-Release-Profile-RegEx.md, docs/stylesheets/extra.css
```yml
- Fixed: Table color if using light theme
- Changed: made the link working for shortcuts
Updated: Radarr - Setup Custom Formats
- Fixed: broken links
Updated: Radarr - Import Custom Formats
- Fixed: broken links
Updated: Notifiarr - Quick Start
- Changed: old URL to new URL
```
=> Maintance release 20210627

docs/index.md
=> Minor edits

docs/Misc/how-to-provide-a-docker-compose.md
=> Minor edit

docs/json/radarr/br-disk.json
Co-Authored-By: bakerboy448 <55419169+bakerboy448@users.noreply.github.com>
=> Updated: [BR-DISK] - Fixed VC1 regex for better recornizing

docs/Bazarr/Setup-Guide.md, docs/Hardlinks/How-to-setup-for/Synology.md, docs/Hardlinks/How-to-setup-for/Unraid.md, docs/Radarr/Radarr-collection-of-custom-formats.md, docs/Radarr/Radarr-recommended-naming-scheme.md, docs/Radarr/Radarr-setup-custom-formats.md, docs/Sonarr/Sonarr-Release-Profile-RegEx.md, docs/json/radarr/lq.json
*Maintenance release 20210827 #333*
Updated: Bazarr - Setup Guide
- Fixed: Typo (Thnx sfxhewitt)
Updated: Radarr - Recommended naming scheme
- Changed: Minimal details + the irreplaceable data from [Quality Title] to [Quality Full]
- Added: [CLICK TO EXPAND] to hidden examples.
- Fixed: Formatting
- Added: [CLICK TO EXPAND] to hidden examples.
- Added: Warning for season packs regex
- Fixed: Formatting
Updated: Radarr - How to setup Custom Formats
- Added: [CLICK TO EXPAND] to hidden examples.
- Fixed: Formatting
- Added: new [LQ] groups.
- Changed: Description
- NOTE: Yes I do know that some LQ groups show up also in other conditions , I did this so it's easier for me to maintain. and you can …
=> Maintenance release 20210827

docs/Sonarr/Sonarr-Release-Profile-RegEx-Anime.md
Most are simple changes;  just cleanup and dedupe the regex a bit
Visual for the biggest change
Old
New
=> Refactor and Cleanup some regex (Anime)

docs/Sonarr/Sonarr-Release-Profile-RegEx-Anime.md
- Changed: Modified Kaizoku to have brackets so it would not interfere with alternate title.
=> Updated: Sonarr - Release Profile RegEx (Anime)

docs/Sonarr/Sonarr-Release-Profile-RegEx.md
Remove duplication
Make all case insensitive
=> (Sonarr) (dovi) Minor regex fixups & convert to lower case

docs/Sonarr/Sonarr-Release-Profile-RegEx.md
- Fixed: Formatting for TRaSH Updater
- Added: extra note for optional
=> Fixed: Formatting for TRaSH Updater

docs/Hardlinks/How-to-setup-for/Synology.md
Put in a test command for pullio.
=> Update pullio info

docs/Hardlinks/How-to-setup-for/Synology.md
Added a note to permission section in case someone decides to copy files from an old library into new library.
=> Update permissions section syno guide

docs/Bazarr/Setup-Guide.md, docs/Plex/Tips/Plex-media-server.md, docs/Radarr/Radarr-remote-path-mapping.md, docs/Radarr/Radarr-setup-custom-formats.md, docs/Sonarr/Sonarr-remote-path-mapping.md
=> Fixed: typo allot > alot

docs/Bazarr/Setup-Guide.md, docs/Plex/Tips/Plex-media-server.md, docs/Radarr/Radarr-remote-path-mapping.md, docs/Radarr/Radarr-setup-custom-formats.md, docs/Sonarr/Sonarr-remote-path-mapping.md
Fixed: #447 alot > a lot (thnx @davidnewhall )
=> Fixed: #447 alot > a lot

.github/workflows/deploy.yml
=> Fix page revision time

docs/json/radarr/hq.json
- Updated: CF `[HQ]` Added `FraMeSToR`.
=> Updated: CF `[HQ]` Added `FraMeSToR`.

docs/Sonarr/Sonarr-Release-Profile-RegEx.md
notifiarr pull on hold w/ this change - https://github.com/Notifiarr/sonarr-release-profiles/pull/15
=> add hbom as aka for hbomax

docs/Sonarr/Sonarr-Release-Profile-RegEx-Anime.md
This reverts commit b75d78a09287d4540657e178778b8353ceda8f22, reversing
changes made to 2165744e067ad1079820de669eabe08cb74d23e2.
Reverting the changes as more detail is needed and big changes should be explained. The other problem is that we need more quality control on these changes as there are now duplicates in the rest of the repo that need to be addressed as well.
=> Revert "Merge pull request #426 from mizz141/patch-1"

docs/Hardlinks/.pages, docs/Hardlinks/Replace-copies-with-hardlinks.md, mkdocs.yml
- NEW: Replace copies with hardlinks
=> NEW: Replace copies with hardlinks

docs/Radarr/Radarr-setup-custom-formats.md, docs/SQP/index.md, includes/cf/misc.md, includes/cf/movie-versions-imaxe.md, includes/cf/movie-versions.md, includes/cf/unwanted.md, includes/sqp/1-2-cf-scoring.md
- Complete redo and updating of the scoring and formatting of the guide
=> Updated: How to setup Custom Formats 20220123

docs/json/radarr/dv-webdl.json
Sorry @TRaSH- , i dumbly forgot to add this one... (file stayed unsaved)
=> Forgot dv-webdl for DOLBYVISION fix

docs/json/radarr/no-rlsgroup.json
Updated: CF [No-RlsGroup] Sync with Radarr
- Updated: Handle Exception Release Groups that don't follow -RlsGrp
=> Updated: CF [No-RlsGroup] Sync with Radarr

docs/json/radarr/lq.json
- Added: Nominated Unwanted Groups, these are groups are nominated to be in the LQ for different reasons.
=> Updated: CF [LQ] Added Nominated Unwanted Groups

docs/Sonarr/Sonarr-Release-Profile-RegEx.md, docs/json/radarr/2160p.json, docs/json/radarr/dv-webdl.json, docs/json/radarr/dv.json, docs/json/radarr/hdr-undefined.json, docs/json/radarr/hdr.json, docs/json/radarr/hlg.json, docs/json/radarr/pq.json
Back with this one, sorry @TRaSH- 
As @rg9400 suggested, this is way more elegant and simple.
=> Refactor Dolby Vision regexp to make it less complex

docs/Sonarr/Sonarr-Release-Profile-RegEx.md
Fixed: trash updater Structural Guidelines mess up
=> Sonarr RP RegEx WEBDL trash updater fix

docs/json/radarr/hdr10plus.json
- Fixed: CF [HDR10+] Added No DV Condition.
=> Radarr CF [HDR10+] No DV

docs/json/radarr/dv-webdl.json
- Fixed: CF `[DV WEBDL]` Added the group `Flights` to the `Group Exceptions` condition.
=> Radarr CF DV WEBDL Flights

docs/json/radarr/hq-remux.json
- Updated: CF `[HQ Remux]` added group `playBD`
=> Radarr CF HQRemux playBD

mkdocs.yml
=> Reverted failed URL Redirect

docs/Misc/How-to-setup-Torguard-for-port-forwarding.md, docs/json/radarr/framestor.json, docs/json/radarr/imax-enhanced.json
Maintenance Release 20220320
- Updated: CF `[IMAX Enhanced]` Scoring from `750` to `800` to make sure it scores better against `DV HDR10`.
- Updated: CF `[FraMeSToR]` Scoring from `1` to `51` to make sure it scors better against `DV HDR10`.
Misc - How to set Torguard for port forwarding.
- Added: Note `As of 13 March Torguard Settles Piracy Lawsuit and has agreed to use commercially reasonable efforts to block BitTorrent traffic on its servers in the US using firewall technology`
=> Maintenance Release 20220320

docs/Plex/Tips/.pages, docs/Plex/Tips/Optimal-plex-client-settings.md
- NEW: Page with link(s) for Optimal Plex Client Settings.
=> Optimal Plex Client Settings

docs/Downloaders/qBittorrent/.pages, docs/Downloaders/qBittorrent/3rd-party-tools.md
- NEW: Link to qBit Manage.
- NEW: Link to qbittorrent-cli.
- NEW: Link to qbittools.
- NEW: Link to A Dark but not black qBittorrent WebUI.
=> qBittorrent 3rd Party tools

docs/json/radarr/hq-remux.json
- removed flights for overcropping and using IMAX enhanced DV metadata in remuxes
=> Removed flights

docs/Hardlinks/How-to-setup-for/Synology.md
Small punctuation update.
Corrected the !attention command at the end, where it used the `compose -f` command, which does not work with pullio.
=> Updated command

docs/Bazarr/Setup-Guide.md, docs/Downloaders/qBittorrent/3rd-party-tools.md, docs/Radarr/Radarr-Quality-Settings-File-Size.md, docs/Radarr/Radarr-collection-of-custom-formats.md, docs/Radarr/Radarr-how-to-update-custom-formats.md, docs/Radarr/Radarr-import-custom-formats.md, docs/Radarr/Radarr-recommended-naming-scheme.md, docs/Radarr/Radarr-remote-path-mapping.md, docs/Radarr/Radarr-setup-custom-formats.md, docs/Radarr/Tips/Merge-quality.md, docs/Radarr/Tips/Radarr-add-a-movie-collection.md, docs/Radarr/Tips/Radarr-rename-your-folders.md, docs/Radarr/Tips/Radarr-show-unknown-movie-items.md, docs/Radarr/Tips/Sync-2-radarr-sonarr.md, docs/SQP/1-1.md, docs/SQP/index.md, docs/Sonarr/Sonarr-Quality-Settings-File-Size.md, docs/Sonarr/Sonarr-Release-Profile-RegEx-Anime.md, docs/Sonarr/Sonarr-Release-Profile-RegEx.md, docs/Sonarr/Sonarr-recommended-naming-scheme.md, docs/Sonarr/Sonarr-remote-path-mapping.md, docs/Sonarr/Tips/Merge-quality.md, docs/Sonarr/index.md, docs/index.md, includes/sqp/1-2-workflow.md
Went through the majority of the guide and looked for typos, unnecessary spaces/missing punctuations, and restructured some confusing sentences. I have not changed any formatting, but found one error that I fixed.
=> Typo fixes

docs/json/sonarr/.editorconfig, docs/json/sonarr/lqGroups.json, docs/json/sonarr/optional.json, docs/json/sonarr/optionals.json, docs/json/sonarr/p2pRepackProper.json, docs/json/sonarr/streaming.json, docs/json/sonarr/visorakAnimeOne.json, docs/json/sonarr/visorakAnimeTwo.json
For only the Sonarr JSON files, I performed a "Reformat Document" in Visual Studio Code. This solved a few issues:
- Inconsistent style between JSON files
- Difficulty reading the JSON files in web file viewer due to inconsistent indentation characters
- Lack of consistent style within a single file
There will now be a consistent formatting style going forward enforced by `.editorconfig` file.
The diff is large, but all I did was reformat whitespace. There is NO change to the actual data in the JSON files.
=> Add editorconfig and reformat Sonarr JSON files

includes/cf/misc.md
- Updated: CF [Repack/Proper] scoring.
=> Radarr - How to setup Custom Formats

docs/Radarr/index.md, docs/Sonarr/index.md
- Added: all Star branch versions including warnings
- Added: How to update to a Starr Apps branche.
=> Starr index page update

docs/Misc/how-to-provide-a-docker-compose.md
- Updated: *arr to Starr Apps.
- Added: privatebin.net
=> How to provide a docker-compose

docs/Sonarr/Sonarr-Release-Profile-RegEx.md
Update page according to changes in #573.
=> Update "Ignore scene releases" optional

docs/Sonarr/Sonarr-Release-Profile-RegEx.md, docs/json/sonarr/lqGroups.json
- Messed up #581 and @mynameisbogdan  came to rescue
=> Fix for #581

docs/Radarr/Tips/Sync-2-radarr-sonarr.md
- Updated: How to access the SQP (Special Quality Profile) Discord channel.
=> Radarr/Sonarr sync update for SQP

docs/json/radarr/dv-hdr10.json
Score updated to fix some upgrading issues from SPHD to W4NK3R
=> Updated: Score of "DV HDR10" from 1550 to 1500

docs/Sonarr/Sonarr-Quality-Settings-File-Size.md
- Changed: Minimum file size for `HDTV-2160p`, `WEBRip-2160p` and `WEBDL-2160p`
=> Sonarr - Quality Settings (File Size)

docs/json/sonarr/v4/normal/amazon.json, docs/json/sonarr/v4/normal/apple-tvplus.json, docs/json/sonarr/v4/normal/br-disk.json, docs/json/sonarr/v4/normal/dc-universe.json, docs/json/sonarr/v4/normal/deflate-inflate.json, docs/json/sonarr/v4/normal/dislike-obfuscated.json, docs/json/sonarr/v4/normal/dislike-retags.json, docs/json/sonarr/v4/normal/disneyplus.json, docs/json/sonarr/v4/normal/dv-webdl.json, docs/json/sonarr/v4/normal/dv.json, docs/json/sonarr/v4/normal/hbo-max.json, docs/json/sonarr/v4/normal/hbo.json, docs/json/sonarr/v4/normal/hdr.json, docs/json/sonarr/v4/normal/hq-webdl.json, docs/json/sonarr/v4/normal/hulu.json, docs/json/sonarr/v4/normal/itunes.json, docs/json/sonarr/v4/normal/lq.json, docs/json/sonarr/v4/normal/netflix.json, docs/json/sonarr/v4/normal/paramountplus.json, docs/json/sonarr/v4/normal/peacock-tv.json, docs/json/sonarr/v4/normal/quibi.json, docs/json/sonarr/v4/normal/repack-proper.json, docs/json/sonarr/v4/normal/repack-v2.json, docs/json/sonarr/v4/normal/repack-v3.json, docs/json/sonarr/v4/normal/showtime.json, docs/json/sonarr/v4/normal/x265-7201080p.json, docs/json/sonarr/v4/normal/youtube-red.json
- Testing: a easier way on the backend to manage the frontend of the guide
=> backend-maintenance-test

docs/json/sonarr/v4/normal/amazon.json, docs/json/sonarr/v4/normal/apple-tvplus.json, docs/json/sonarr/v4/normal/disneyplus.json, docs/json/sonarr/v4/normal/hbo-max.json, docs/json/sonarr/v4/normal/hulu.json, docs/json/sonarr/v4/normal/itunes.json, docs/json/sonarr/v4/normal/netflix.json, docs/json/sonarr/v4/normal/paramountplus.json, docs/json/sonarr/v4/normal/peacock-tv.json, docs/json/sonarr/v4/normal/quibi.json, docs/json/sonarr/v4/normal/showtime.json, docs/json/sonarr/v4/normal/youtube-red.json
=> Backend maintenance test v2

docs/Sonarr/Sonarr-Release-Profile-RegEx.md, docs/json/sonarr/optional.json, docs/json/sonarr/optionals.json, docs/updates.txt
- Added: KOGI to the Dislike Scene Releases for indexers that rename
- Added: DEPRECATED warning for the optional.json, please use optionals.json
=> Added KOGI to the Dislike Scene Releases for indexers that rename

docs/json/sonarr/optional.json
As proposed in #619.
This will also fix a bug in recyclarr (recyclarr/recyclarr#87).
=> Made the deprecated optional.json file a valid JSON file again

docs/json/radarr/amazon.json, docs/json/radarr/apple-tvplus.json, docs/json/radarr/disneyplus.json, docs/json/radarr/hbo-max.json, docs/json/radarr/netflix.json, docs/json/radarr/paramountplus.json, docs/json/radarr/peacock-tv.json, docs/updates.txt
- Changed: On request Streaming Service to short names.
=> Shortened Streaming Service naming

docs/json/radarr/amazon.json, docs/json/radarr/apple-tvplus.json, docs/json/radarr/disneyplus.json, docs/json/radarr/hbo-max.json, docs/json/radarr/hulu.json, docs/json/radarr/netflix.json, docs/json/radarr/paramountplus.json, docs/json/radarr/peacock-tv.json
- Added: Score 0 for recyclarr compatibility
=> Added: Score 0 for recyclarr compatibility

docs/json/radarr/amazon.json, docs/json/radarr/apple-tvplus.json, docs/json/radarr/disneyplus.json, docs/json/radarr/hbo-max.json, docs/json/radarr/hulu.json, docs/json/radarr/netflix.json, docs/json/radarr/paramountplus.json, docs/json/radarr/peacock-tv.json
=> Reverting #627

includes/cf/hdr-metadata.md
- Fix: scoring of the guide to match JSON
=> Fix: scoring of the guide to match JSON

docs/Downloaders/qBittorrent/Basic-Setup.md, docs/Sonarr/Sonarr-Release-Profile-RegEx-Anime.md
Downloaders - qBittorent - Basic Setup
- Improved: readability of description.
Sonarr - Release Profile RegEx (Anime)
- Fixed: Series Folder Format issue: #624
=> Guide formatting fixes

docs/json/radarr/hq-remux.json, docs/json/radarr/hq-webdl.json, docs/json/radarr/hq.json, docs/json/radarr/lq.json, docs/json/radarr/no-rlsgroup.json, docs/updates.txt
- Updated: CF `[LQ]` Separated conditions on request.
- Updated: CF `[HQ-Remux]` Separated conditions on request.
- Updated: CF `[HQ]` Separated conditions on request.
- Updated: CF `[HQ-WEBDL]` Separated conditions on request.
- Updated: CF `[HQ-WEBDL]` added  group `HONE`.
- Updated: CF `[No-RlsGroup]` added group `HONE` to the exemption.
=> Radarr CF 20220624

docs/json/radarr/hq-webdl.json, docs/json/radarr/no-rlsgroup.json
- Updated: CF `[HQ-WEBDL]` Added word boundary for `HONE`.
- Updated: CF `[No-RlsGroup]` Added word boundary for `HONE`.
=> Added word boundary for HONE

docs/json/radarr/aac.json, docs/json/radarr/atmos-undefined.json, docs/json/radarr/dd-atmos.json, docs/json/radarr/ddplus.json, docs/json/radarr/dts-es.json, docs/json/radarr/dts-hd-hra.json, docs/json/radarr/dts-hd-ma.json, docs/json/radarr/dts-x.json, docs/json/radarr/dts.json, docs/json/radarr/flac.json, docs/json/radarr/pcm.json, docs/json/radarr/truehd-atmos.json, docs/json/radarr/truehd.json
fixed and added conditions in DTS and DTS-ES to better match their respective releases.
also updated the regex to fix the recognition of Basic Dolby Digital to help with incorrect matching of some CFs.
=> Fixed: Conditions in various sound codec CFs

docs/Misc/trash-sync.md
=> Added: GUI option

docs/Downloaders/qBittorrent/Tips/How-to-run-the-unRaid-mover-for-qBittorrent.md
- Fixed: formatting to make it more understandable.
=> Fixed: formatting to make it more understandable.

docs/Hardlinks/Check-if-hardlinks-are-working.md
=> How to check if hardlinks work formatting fix

docs/json/radarr/lq.json
=> Added: PSA to LQ

docs/Downloaders/qBittorrent/3rd-party-tools.md, docs/updates.txt
- Added: Cross-Seed to the 3rd party tools.
=> Added: Cross-Seed to the 3rd party tools

docs/Hardlinks/How-to-setup-for/Synology.md
I updated the script, and made some changes to the textual part of this guide.
=> textual update for automated script

docs/requirements.txt
=> Removed: markdown pin

docs/Hardlinks/How-to-setup-for/Docker.md, docs/Hardlinks/How-to-setup-for/Synology.md, docs/Hardlinks/How-to-setup-for/Unraid.md, includes/downloaders/basic-setup.md, includes/hardlinks/bad-path-suggestion.md
- Added: missing bad path suggestion for some parts
This should also solve issue: #688
=> Guides Bad path suggestion

docs/json/radarr/framestor.json, docs/json/radarr/hq-remux.json
=> Fix: for PR #695

docs/json/radarr/dts-hd-ma.json, docs/json/radarr/dts.json
- FIXED: CF [DTS-HD MA] mismatch. Issue: #701
=> FIXED: CF DTS-HD MA mismatch

.github/workflows/metadata-validation.yml, metadata.schema.json
* chore: Fix incorrect references in metadata schema
* ci: Validation workflow for metadata.json
The goal of this pipeline is to assist in catching issues with changes
made to `metadata.json`. This will be especially useful to have during
pull requests, where changes can be validated before they are merged,
which will avoid breaking any tooling that depends on the
`metadata.json` file.
=> Validation workflow for metadata.json

docs/Sonarr/Sonarr-Release-Profile-RegEx.md, docs/json/sonarr/optionals.json
=> Add missing SCENE groups

docs/stylesheets/github-permalink-style.css, mkdocs.yml
- Changed: Better looking permalink icon
=> Changed: Better looking permalink icon

docs/json/sonarr/cf/anime/anime-bd-tier-01-(top-seadex-muxers).json, docs/json/sonarr/cf/anime/anime-bd-tier-02-(seadex-muxers).json, docs/json/sonarr/cf/anime/anime-bd-tier-03-(seadex-muxers).json, docs/json/sonarr/cf/anime/anime-bd-tier-05-(remuxes).json, docs/json/sonarr/cf/anime/anime-bd-tier-06-(fansubs).json, docs/json/sonarr/cf/anime/anime-bd-tier-07-(p2pscene).json, docs/json/sonarr/cf/anime/anime-bd-tier-08-(mini-encodes).json, docs/json/sonarr/cf/anime/anime-dubs-only.json, docs/json/sonarr/cf/anime/anime-lq-groups.json, docs/json/sonarr/cf/anime/anime-raws.json, docs/json/sonarr/cf/anime/anime-v2.json, docs/json/sonarr/cf/anime/anime-v3.json, docs/json/sonarr/cf/anime/anime-v4.json, docs/json/sonarr/cf/anime/anime-web-tier-01-(muxers).json, docs/json/sonarr/cf/anime/anime-web-tier-02-(top-fansubs).json, docs/json/sonarr/cf/anime/anime-web-tier-03-(subsplease).json, docs/json/sonarr/cf/anime/anime-web-tier-04-(official-subs).json, docs/json/sonarr/cf/anime/anime-web-tier-05-(fansubs).json, docs/json/sonarr/cf/anime/anime-web-tier-06-(fansubs).json
I tried to sort all the various anime CFs alphabetically
=> Sort Anime CFs alphabetically

.github/CONTRIBUTING.md
- Added: regex test case info, from now on when updating or adding a new CF the test case url needs to be added to the json.
=> Added: regex test case info

docs/Sonarr/Sonarr-setup-custom-formats-Anime.md
**Purpose**
Creating PR to fix broken links
**Approach**
**Learning**
=> Sonarr Anime fix broken links

docs/stylesheets/extra.css
- Changed: link color to make it better readable
=> Change: link color

docs/Radarr/Radarr-import-custom-formats.md, docs/Sonarr/sonarr-import-custom-formats.md
- Added: Setup the scores in your Quality Profile
=> [Starr] import custom formats added how to score

docs/Sonarr/sonarr-collection-of-custom-formats.md
**Purpose**
**Approach**
**Learning**
=> fix missing anchor for v1 anime

docs/json/sonarr/cf/web-tier-02.json
- Added: SMURF
- Sorted: ASC
**Purpose**
**Approach**
**Learning**
=> [Sonarr] CF `[WEB Tier 02]`

docs/Sonarr/sonarr-collection-of-custom-formats.md
- Fix: forgot to remove SE from table and collection list
=> Fix: table link

docs/json/radarr/cf/flights-no-imax.json
**Purpose**
**Approach**
**Learning**
=> Fix: screw up

docs/json/radarr/cf/special-edition.json
**Purpose**
**Approach**
**Learning**
=> fix Special Edition for new {edition-} naming

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/Sonarr/sonarr-collection-of-custom-formats.md, docs/json/radarr/cf/atvp.json, docs/json/sonarr/cf/atvp.json, includes/cf/sonarr-streaming-services.md
- Added: CF `[ATVP]`
- DELETED: faulty CF `[APTV]`
=> [Starr] CF `[ATVP]` Fix

docs/json/radarr/cf/bad-dual-groups.json, docs/json/sonarr/cf/bad-dual-groups.json
- Added: `PTHome` to the CF `[Bad Dual Groups]`.
- Added: `ZigZag` to the CF `[Bad Dual Groups]`.
=> [Starr] Added: `PTHome` + `ZigZag"`

docs/json/radarr/cf/truehd-atmos.json, docs/json/sonarr/cf/truehd-atmos.json
- Added: `Not DTS X` condition to prevent false positive.
=> [Starr] CF `[TrueHD ATMOS]`

docs/Downloaders/qBittorrent/Tips/How-to-run-the-unRaid-mover-for-qBittorrent.md
- Add: pip from nerdpack for qBit mover
=> [Downloaders] add pip from for qBit mover

docs/json/radarr/cf/lq.json
- Fixed: matching epic in release name
- Added: word boundaries
=> [Radarr] CF [LQ] fix matching epic in release name

docs/json/radarr/cf/dts-hd-hra.json, docs/json/sonarr/cf/dts-hd-hra.json
- Fix: Wrongly matching DTS-Hi10P
=> [Starr] CF `[DTS-HRA]`

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/Sonarr/sonarr-collection-of-custom-formats.md
- Reorganized the table order for certain categories.
=> [Guide] Table reorganize

docs/json/radarr/cf/uhd-bluray-tier-01.json, docs/json/radarr/cf/uhd-bluray-tier-02.json, docs/json/radarr/cf/uhd-bluray-tier-03.json
=> [Radarr] Added: UHD Tier

docs/json/radarr/cf/uhd-bluray-tier-02.json
- Removed: WEBDV, fix paste error of #845
=> Removed: WEBDV, fix paste error

docs/json/radarr/cf/v0.json, docs/json/radarr/cf/v1.json, docs/json/radarr/cf/v2.json, docs/json/radarr/cf/v3.json, docs/json/radarr/cf/v4.json, docs/json/sonarr/cf/v0.json, docs/json/sonarr/cf/v1.json, docs/json/sonarr/cf/v2.json, docs/json/sonarr/cf/v3.json, docs/json/sonarr/cf/v4.json
**Purpose**
Updated v CFs for Radarr and Sonarr to match better
**Approach**
**Learning**
=> feat(anime) - updated version CFs

docs/json/radarr/cf/v3.json
**Purpose**
There was a typo in the v3 CF for Radarr.
**Approach**
**Learning**
=> CF fix for Radarr v3

docs/SQP/5.md
=> Radarr SQP-5 patch 1

docs/json/radarr/quality-size/movie.json, docs/json/radarr/quality-size/sqp-streaming.json, docs/json/radarr/quality-size/sqp-uhd.json
- Changed: Lowered min file size 1080p-WEB
=> [Radarr] Lowered min file size 1080p-WEB

docs/json/radarr/quality-size/sqp-streaming.json, docs/updates.txt, includes/sqp/1-quality-size.md
- Add: WEB-720p quality file size (#access-to-sqp for more info)
resolves: #894
=> [SQP-1] Add: WEB-720p quality file size

includes/sqp/2-why.md, includes/sqp/5-why.md
**Purpose**
To fix a couple spelling errors.
**Approach**
Use the correct spelling
=> Fix spelling errors in the SQP

docs/SQP/yml/sqp-2.yml, docs/SQP/yml/sqp-3.yml, docs/SQP/yml/sqp-4.yml, docs/SQP/yml/sqp-5.yml, docs/updates.txt, includes/sqp/1-cf-scoring.md
- Add: [SQP-1] Add also warning for plain IMAX.
- Add: end of line comment on the scores that override defaults.
=> [SQP] Add end of line comment on the scores that override defaults

docs/Sonarr/Sonarr-Release-Profile-RegEx.md, docs/json/sonarr/rp/optionals.json, docs/updates.txt
- Fix: aggressive in `Dislike release containing: 1-`
=> [Sonarr] Fix: aggressive `Dislike release containing: 1-`

docs/json/radarr/cf/2160p.json, docs/json/radarr/cf/sdr.json, includes/sqp/uhd-radarr-unwanted.md
- NEW: CF `SDR`
- Updated: CF `2160p` Added Condition `NOT SDR`
=> [SQP] CF `SDR` and `2160p` Update

docs/SQP/yml/sqp-2.yml, docs/SQP/yml/sqp-3.yml, docs/SQP/yml/sqp-4.yml, docs/SQP/yml/sqp-5.yml
**Purpose**
Add SDR as an unwanted format in Recyclarr SQP 2-5
**Approach**
Just trying to be helpful
=> Add SDR as unwanted in SQP2-5

docs/Radarr/Radarr-Quality-Settings-File-Size.md, docs/Sonarr/Sonarr-Quality-Settings-File-Size.md
**Purpose**
enhance user exp.
**Approach**
clarify w/ words
**Learning**
=> radarr qualities - add descriptor to values

docs/Prowlarr/index.md, docs/Radarr/index.md, docs/Sonarr/index.md, docs/updates.txt
- Switched to STARR version listings using the build server.
- Updated: Branch description to match the official WikiArr.
=> Switched to STARR version listings

docs/json/radarr/cf/anime-web-tier-01-muxers.json, docs/json/sonarr/cf/anime-web-tier-01-muxers.json
**Purpose**
Added sam to anime web tier 01 for Radarr and Sonarr
**Approach**
**Learning**
=> Update anime-web-tier-01 for Radarr and Sonarr

docs/Sonarr/Sonarr-Release-Profile-RegEx.md, docs/json/radarr/cf/opus.json, docs/json/sonarr/cf/lq.json, docs/json/sonarr/cf/opus.json, docs/json/sonarr/rp/lqGroups.json, docs/updates.txt
**Purpose**
Fix issues #944 and #945.
**Approach**
Add `MeGusta` to the Sonarr `LQ` CF and add a group negation for `OPUS` in the `Opus` CF.
=> Fixed: Issues #944 and #945

docs/json/radarr/cf/special-edition.json
**Purpose**
**Approach**
**Learning**
=> Radarr CF (special-edition): Fix regex, match test

docs/SQP/1.md, docs/SQP/2.md, docs/SQP/3.md, docs/SQP/4.md, docs/SQP/5.md, docs/updates.txt, includes/sqp/move-quality-to-top.md
- Add: Move selected quality to top tip
=> [SQP] Move selected quality to top tip

docs/Radarr/Radarr-setup-custom-formats.md, docs/updates.txt
- Add: Main Flowchart to guide
=> Add: Main Flowchart to guide

includes/sqp/2-qp-settings.md, includes/sqp/3-qp-settings.md, includes/sqp/4-qp-settings.md, includes/sqp/5-qp-settings.md
**Purpose**
CF `1080p` + `HDR` is 550. Lower scored releases are not wanted.
=> Set min. CF score to 550 for all SQP2-5

docs/Misc/trash-sync.md
**Purpose**
In Misc - TRaSH Sync
Changed link to just the TLD, as the profile.php doesn't exists anymore and is only accessible after login anyways.
=> Updated broken Link

docs/Radarr/Radarr-setup-custom-formats.md
all groups of custom formats were incorrectly listed under `releases to avoid`
current state
**Purpose**
**Approach**
**Learning**
=> fix setup custom format guides improper heading indents

includes/cf/dv-info.md, includes/cf/radarr-all-hdr-formats.md
=> [Radarr] Added: DV info

docs/json/sonarr/rp/optionals.json
- Fix: `AV1` Formatting in the json.
=> [Sonarr] Fix: `AV1` Formatting in the json

includes/cf/radarr-suggest-attention.md
=> [Guide] Fix link to naming guide

docs/json/radarr/cf/no-rlsgroup.json
=> Updated: CF `No-RlsGroup`

docs/Radarr/radarr-setup-quality-profiles.md
**Purpose**
**Approach**
**Learning**
=> add quality profile header

docs/Sonarr/.pages, docs/Sonarr/sonarr-collection-of-custom-formats.md, docs/Sonarr/sonarr-how-to-update-custom-formats.md, docs/Sonarr/sonarr-import-custom-formats.md, docs/Sonarr/sonarr-setup-quality-profiles-anime.md, docs/Sonarr/sonarr-setup-quality-profiles.md, docs/updates.txt, includes/cf/sonarr-streaming-services.md, mkdocs.yml
**[Sonarr v4]**
- NEW: Sonarr v4 Beta to guide
=> [Sonarr] v4 to Guide

docs/Downloaders/NZBGet/Basic-Setup.md, docs/Downloaders/NZBGet/Paths-and-Categories.md, docs/Downloaders/NZBGet/index.md, docs/Downloaders/NZBGet/scripts/index.md, docs/Downloaders/index.md, docs/stylesheets/extra.css, docs/updates.txt
**[NZBGet]**
- NZBGet development has been officially abandoned by the developer.
=> [NZBGet] abondoned message

docs/Sonarr/index.md
=> [Sonarr] Added v4 Version and Info

docs/json/radarr/cf/web-tier-01.json, docs/json/sonarr/cf/web-tier-01.json, docs/updates.txt
**[Starr]**
Added: `APEX` to CF `WEB Tier 01`
=> Starr Added APEX to WEB Tier 01

docs/json/radarr/cf/web-tier-01.json, docs/json/sonarr/cf/web-tier-01.json
**Purpose**
Add additional RlsGroup variations similar to APEX
**Approach**
N.A.
**Learning**
=> Update: Additional APEX variations to WEB Tier 01

docs/json/radarr/cf/web-tier-01.json, docs/json/sonarr/cf/web-tier-01.json
**Purpose**
Combine the variations of APEX RlsGroups in 1 CF
**Approach**
**Learning**
=> Combine APEX RlsGroups in 1 CF

docs/index.md
**Purpose**
Anyway is used to change the subject of a conversation, similar to nonetheless. any way is used similar to “in any manner” or by “by any means”
=> Small grammar fix

docs/json/radarr/cf/bcore.json
**Purpose**
https://github.com/TRaSH-/Guides/issues/1021
https://github.com/TRaSH-/Guides/issues/1019
Took "BCORE" to generate hash.
=> Added `BCORE`

docs/json/sonarr/cf/web-tier-03.json
**Purpose**
Add -DRACULA to Web Tier -3 resolves #1018 
**Learning**
=> feat(sonarr) - web tier 03 update

docs/json/radarr/cf/dv-webdl.json, docs/json/radarr/cf/hdr-undefined.json, docs/json/radarr/cf/hdr.json, docs/json/radarr/cf/sdr.json, docs/json/sonarr/cf/dv-webdl.json, docs/json/sonarr/cf/hdr-undefined.json, docs/json/sonarr/cf/hdr.json, docs/json/sonarr/cf/sdr.json, docs/json/sonarr/cf/web-tier-01.json, docs/json/sonarr/rp/p2pRepackProper.json
**Purpose**
Fix capitalization of the RlsGrp `SiC`.
**Approach**
Lowercase the `i` in `SIC`.
=> fix(starr-cfs): capitalization of RlsGrp `SiC`

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/json/radarr/cf/pathe.json, docs/json/radarr/cf/web-tier-03.json, docs/updates.txt
**[Radarr]**
- Added: Dutch streaming service
- Added: Dutch rlsgrp
=> [Radarr] Added dutch streaming service

docs/SQP/yml/sqp-1.yml, docs/SQP/yml/sqp-2.yml, docs/SQP/yml/sqp-3.yml, docs/SQP/yml/sqp-4.yml, docs/SQP/yml/sqp-5.yml
**Purpose**
To updated the SQP ymls to the latest recommended config.
**Approach**
Added: `reset_unmatched_scores`
Removed: `preferred_ratio` (guide's own ratio now set by default)
**Learning**
=> Updated SQP ymls to latest config

docs/Radarr/Radarr-recommended-naming-scheme.md
Included a bit more information on the pros and cons of using {Original Title} versus the recommended naming scheme
**Purpose**
**Approach**
**Learning**
=> Update alternate naming scheme

docs/Sonarr/Sonarr-recommended-naming-scheme.md
Added a bit more info for using original title vs. standard naming scheme
**Purpose**
**Approach**
**Learning**
=> Updated original title naming scheme

docs/Radarr/Radarr-collection-of-custom-formats.md
**Purpose**
**Approach**
**Learning**
=> Clarify Radarr x265 wording

docs/Sonarr/sonarr-setup-quality-profiles-french-en.md, docs/Sonarr/sonarr-setup-quality-profiles-french-fr.md, docs/json/sonarr/cf/french-anime-tier-optional.json, includes/french-guide/sonarr-cf-french-anime-scoring-en.md, includes/french-guide/sonarr-cf-french-anime-scoring-fr.md, includes/french-guide/sonarr-french-anime-info-en.md, includes/french-guide/sonarr-french-anime-info-fr.md, includes/french-guide/sonarr-french-unwanted-en.md, includes/french-guide/sonarr-french-unwanted-fr.md, includes/french-guide/sonarr-french-unwanted-uhd-en.md, includes/french-guide/sonarr-french-unwanted-uhd-fr.md
**Purpose**
Added small information regarding recent feedbacks.
**Learning**
=> [Sonarr] Small update on Sonarr french cf

docs/Radarr/radarr-setup-quality-profiles.md, docs/Sonarr/sonarr-setup-quality-profiles.md
**Purpose**
To clarify what the Audio Channels CFs are for and that they relate to, eg 2.0, 5.1, 7.1 etc.
**Approach**
Add some description of what the Audio Channels CFs are for to the Radarr/Sonarr quality profiles pages.
**Learning**
=> Clarify Audio Channels CFs

docs/json/sonarr/cf/dsnp.json
Was not matching Disney+
**Purpose**
Update DSNP CF to fix matching issues for Disney+
Example https://regex101.com/r/AdEeCO/1
**Learning**
=> Updated to match Disney+

docs/json/radarr/naming/radarr-naming.json, docs/json/sonarr/naming/sonarr-naming.json
- Fix: emby/jellyfin folder naming scheme
=> [Starr] Fix: emby/jellyfin folder naming scheme

docs/Radarr/Radarr-recommended-naming-scheme.md, docs/Sonarr/Sonarr-recommended-naming-scheme.md, docs/Sonarr/sonarr-setup-quality-profiles-anime.md, docs/updates.txt
- Make use of the json files for the naming scheme
=> [Guide] Move naming scheme to json part2

docs/json/radarr/naming/radarr-naming.json
- Fix: Emby/JF naming scheme for imdbid
=> Fix: Emby/JF naming scheme for imdbid

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/Sonarr/sonarr-collection-of-custom-formats.md
**Purpose**
clarify to users who only view the CF entry and don't view the guide what the score should be
**Approach**
see above
**Learning**
=> Explicitly Note DV (WEB-DL) should be added with -10000/-1000

docs/Radarr/recyclarr-config/hd_bluray_web.yml, docs/Radarr/recyclarr-config/remux_web_1080p.yml, docs/Radarr/recyclarr-config/remux_web_2160p.yml, docs/Radarr/recyclarr-config/uhd_bluray_web.yml, docs/SQP/yml/sqp-1.yml, docs/SQP/yml/sqp-2.yml, docs/SQP/yml/sqp-3.yml, docs/SQP/yml/sqp-4.yml, docs/SQP/yml/sqp-5.yml
**Purpose**
Add BCORE CFs to all recyclarr config files.
**Approach**
So they're up to date with the guides.
**Learning**
=> Add BCORE to recyclarr config files (and tidy some formatting)

docs/Downloaders/SABnzbd/Paths-and-Categories.md, docs/Downloaders/qBittorrent/How-to-add-categories.md
- Add: info which root/base path is used
=> info which root/base path is used

docs/Sonarr/Sonarr-Quality-Settings-File-Size.md
=> Revert "Add preferred quality note to Sonarr filesize page"

docs/json/sonarr/cf/remux-tier-02.json
Adding playBD to remux tier 02
**Purpose**
Updating remux tier 02 to add playBD
**Learning**
=> Update Sonarr Remux Tier 02

docs/json/sonarr/naming/sonarr-naming.json
- [Sonarr] Updated naming scheme to be consistent with Radarr.
=> [Sonarr] Updated naming scheme to be consistent with Radarr.

docs/json/sonarr/naming/sonarr-naming.json
=> Revert "[Sonarr] Updated naming scheme to be consistent with Radarr."

docs/json/sonarr/cf/red.json, docs/updates.txt
- [Sonarr] CF `RED` to not match episode title with the word RED.
=> [Sonarr] CF `RED` Fix

mkdocs.yml
PR enables the following previously enabled options that have now become opt-in:
content.code.copy
content.action.edit
content.action.view
https://squidfunk.github.io/mkdocs-material/upgrade/
=> enable opt-in features

docs/Radarr/recyclarr-config/hd_bluray_web.yml, docs/Radarr/recyclarr-config/remux_web_1080p.yml, docs/Radarr/recyclarr-config/remux_web_2160p.yml, docs/Radarr/recyclarr-config/uhd_bluray_web.yml, docs/SQP/yml/sqp-1.yml, docs/SQP/yml/sqp-2.yml, docs/SQP/yml/sqp-3.yml, docs/SQP/yml/sqp-4.yml, docs/SQP/yml/sqp-5.yml, docs/Sonarr/recyclarr-config/web_1080p_v4.yml, docs/Sonarr/recyclarr-config/web_2160p_v4.yml
**Purpose**
To add the STAN streaming service to Recyclarr config files
**Approach**
Added the STAN CF to the streaming services section(s)
**Learning**
=> Add STAN to Recyclarr Config Files (Radarr/Sonarr/SQPs)

docs/json/radarr/cf/stan.json, docs/updates.txt
**[New]**
- None
**[Updated]**
- None
**[Fixed]**
- [Radarr] CF `Stan` Fix.
=> [Radarr] CF `Stan` Fix

docs/SQP/yml/sqp-1.yml, docs/SQP/yml/sqp-2.yml, docs/SQP/yml/sqp-3.yml, docs/SQP/yml/sqp-4.yml, docs/SQP/yml/sqp-5.yml
**Purpose**
To update SQP 1-5 recyclarr configs to clarify use of optional CFs
**Approach**
Make it clearer that uncommenting a CF in the optional section will ensure it is added to that quality profile
**Learning**
=> Update SQP 1-5 recyclarr configs to clarify use of optional CFs

docs/Sonarr/Sonarr-Release-Profile-RegEx.md, docs/json/sonarr/rp/lqGroups.json, docs/json/sonarr/rp/optionals.json, docs/json/sonarr/rp/p2pRepackProper.json
**Purpose**
To update the Release Profile RegEx (WEB-DL) guide page for Sonarr V3 to patch the current scores and regexes
**Approach**
Copied scores and manual format regexes from JSON files.
**Learning**
=> Update Sonarr V3 Release Profile RegEx (WEB-DL) Guide Page

docs/updates.txt, includes/cf/dv-info.md
**[New]**
- None
**[Updated]**
- [Sonarr v3] Updated several regex and scoring to match Sonarr v4.
- [Starr] Updated HDR info for AppleTV Profile 5 - It has been confirmed that with the latest beta build of Plex, Profile 5 MKV files now play correctly.
**[Fixed]**
- None
=> Maintance Release 20230205

docs/updates.txt, includes/sqp/2-merge-qualities.md, includes/sqp/3-merge-qualities.md, includes/sqp/4-merge-qualities.md, includes/sqp/5-merge-qualities.md
- [SQP 2-5] Added extra info for the HD/UHD merge/split.
=> [SQP 2-5] Added extra info for the HD/UHD merge/split.

docs/json/radarr/cf/lq.json
Fixes #1159
**Purpose**
**Approach**
**Learning**
=> [radarr] add PiRaTeS to LQ CF

docs/json/radarr/cf/sdr.json, docs/json/sonarr/cf/sdr.json, docs/updates.txt
**[New]**
- None
**[Updated]**
- None
**[Fixed]**
- [Starr] Added `HLG(10)` to CF `SDR` - For proper scoring.
=>  [Starr] Added `HLG(10)` to CF `SDR` - For proper scoring.

docs/json/radarr/cf/upscaled.json
**Purpose**
Block another naming for upscaled in the `Upscaled` CF.
**Approach**
Add a `Regrade` condition to the `Upscaled` CF.
=> feat(radarr): add `Regrade` to the `Upscaled` CF

docs/recyclarr-configs/radarr/sqp/sqp-3.yml, docs/recyclarr-configs/radarr/sqp/sqp-4.yml, docs/recyclarr-configs/radarr/sqp/sqp-5.yml, docs/recyclarr-configs/sonarr/web-2160p-v4.yml
Also improve the DV (WEBDL) comment in the Sonarr config file
**Purpose**
Bring the DV (WEBDL) comment in line with the newly updated Radarr configs
**Approach**
Update the comment
**Learning**
=> Update DV (WEBDL) comment in Sonarr recyclarr 2160p config and fix profile names in SQP configs

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/json/radarr/cf/vinegar-syndrome.json, docs/recyclarr-configs/radarr/hd-bluray-web.yml, docs/recyclarr-configs/radarr/remux-web-1080p.yml, docs/recyclarr-configs/radarr/remux-web-2160p.yml, docs/recyclarr-configs/radarr/sqp/sqp-1.yml, docs/recyclarr-configs/radarr/sqp/sqp-2.yml, docs/recyclarr-configs/radarr/sqp/sqp-3.yml, docs/recyclarr-configs/radarr/sqp/sqp-4.yml, docs/recyclarr-configs/radarr/sqp/sqp-5.yml, docs/recyclarr-configs/radarr/uhd-bluray-web.yml
**Purpose**
Add a CF for `Vinegar Syndrome` releases to properly score and grab them.
Closes #1220 
**Approach**
Create the `Vinegar Syndrome` CF and add it to the guide and all necessary recyclarr yamls.
=> feat(radarr): create `Vinegar Syndrome` CF and add to guide/recyclarr yamls

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/Sonarr/sonarr-collection-of-custom-formats.md, docs/json/radarr/cf/hfr.json, docs/json/sonarr/cf/hfr.json
**Purpose**
Add a `HFR` custom format to either prefer or reject HFR releases.
Close #1219 
**Approach**
Create a custom format for `HFR` and add it to the guides.
=> feat(starr): add `HFR` CF

docs/Sonarr/Sonarr-Release-Profile-RegEx.md, docs/json/radarr/cf/scene.json, docs/json/sonarr/cf/scene.json, docs/json/sonarr/rp/optionals.json
**[New]**
- None
**[Updated]**
- None
**[Fixed]**
- [Starr] CF `Scene` prevent matching on releases renamed by trackers.
=> [Starr] CF Scene prevent matching on releases renamed by trackers

docs/json/radarr/cf/lq.json
**Purpose**
Fix #1241 
**Approach**
Add `GPTHD` to `LQ` custom format.
=> feat(radarr): add `GPTHD` to `LQ` CF

docs/json/radarr/cf/web-tier-02.json, docs/json/sonarr/cf/web-tier-02.json
**Purpose**
Adding XEBEC to Web Tier 2
**Learning**
=> feat(starr) - added XEBEC to tier 2

includes/sqp/1-quality-size.md
- [SQP] Removed preferred quality size from table
=> [SQP] remove preferred quality size from table

docs/Radarr/radarr-setup-quality-profiles-anime.md, docs/Sonarr/sonarr-setup-quality-profiles-anime.md
**Purpose**
Updating SeaDex URLs to point to the correct URL
**Learning**
=> Feat(anime) - update URL for SeaDex

docs/Hardlinks/How-to-setup-for/Docker.md, docs/Hardlinks/How-to-setup-for/Dockstarter.md, docs/Hardlinks/How-to-setup-for/Synology.md, includes/hardlinks/bad-path-suggestion.md, includes/hardlinks/breakdown-folder-structure-docker.md, includes/hardlinks/breakdown-folder-structure-synology.md, includes/hardlinks/docker-tree-full.md, includes/hardlinks/docker-tree-usenet.md
**[New]**
- None
**[Updated]**
- [Guides Hardlinks] Improve readability paths
**[Fixed]**
- None
=> Guide hardlinks improve readability paths

docs/Sonarr/Sonarr-Release-Profile-RegEx.md, docs/json/sonarr/cf/scene.json, docs/json/sonarr/cf/web-scene.json, docs/json/sonarr/cf/web-tier-01.json, docs/json/sonarr/cf/web-tier-02.json, docs/json/sonarr/cf/web-tier-03.json, docs/json/sonarr/rp/p2pRepackProper.json, docs/updates.txt
**[New]**
- None
**[Updated]**
- [Sonarr] added RlsGrp `CMRG` to `Tier 02`.
**[Fixed]**
- [Sonarr v4] fixed WEB Tier RlsGrp conditions to prevent double scoring.
=> [Sonarr] added RlsGrp `CMRG` to `Tier 02`

docs/recyclarr-configs/radarr/french-remux-web-1080p-multi.yml, docs/recyclarr-configs/radarr/french-remux-web-2160p-multi.yml, docs/recyclarr-configs/radarr/french-uhd-bluray-web-multi.yml, docs/recyclarr-configs/radarr/french-uhd-bluray-web-vostfr.yml
=> [French Guide] Fix typos between Bluray/Remux and 1080p/2160p

includes/hardlinks/docker-tree-full.md, includes/hardlinks/docker-tree-usenet.md
**[New]**
- None
**[Updated]**
- None
**[Fixed]**
- [Guide - Hardlinks] Added the usenet incomplete folder to the folder tree.
=> [Guide - Hardlinks] Added usenet incomplete folder to the folder tree

docs/json/radarr/cf/lq.json
**Purpose**
**Approach**
**Learning**
Fixes #1301
=> [Radarr] Add GHD to LQ

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/SQP/index.md, docs/Sonarr/sonarr-collection-of-custom-formats.md, docs/json/radarr/cf/vp9.json, docs/json/radarr/quality-size/sqp-streaming.json, docs/json/sonarr/cf/vp9.json, includes/sqp/1-4k-quality-size.md
**[New]**
- [Starr] Added CF 'VP9'
**[Updated]**
- [SQP-1 2160p] Added Quality Size 2160p WEBDL
**[Fixed]**
- [SQP-1 2160p] Formatting of index name to be more consistent
=> [Starr] Added CF `VP9`

docs/json/radarr/cf/2160p.json, docs/json/sonarr/cf/2160p.json
**[New]**
- None
**[Updated]**
- None
**[Fixed]**
- [Starr] Added `HLG` to CF `2160p`
=> [Starr] Added `HLG` to CF `2160p`

includes/cf/sonarr-streaming-services-anime.md
**Purpose**
Fixed CR & Funi anchor links
**Approach**
**Learning**
=> Fixing CR & Funi anchor links in table

docs/json/radarr/cf/web-tier-02.json, docs/json/sonarr/cf/web-tier-02.json, docs/json/sonarr/rp/p2pRepackProper.json
**Purpose**
Adding Kitsune to Web tier 2
**Learning**
=> feat(sonar) add Kitsune to web tier 2

docs/json/radarr/cf/max.json, docs/json/sonarr/cf/max.json
**Purpose**
Provide regex example for `Max` CF.
**Approach**
Add regex example to `Max` CF json.
=> chore(starr): add regex example to Max CF

docs/json/radarr/cf/bhdstudio.json, docs/json/radarr/cf/flux.json, docs/json/sonarr/cf/flux.json
- [Starr] Added CF `FLUX`
- [Radarr] Changed score CF `BHDStudio` to `1850`
=> [Starr] Added CF `FLUX`

docs/json/radarr/cf/lq.json, docs/updates.txt
**[New]**
- None
**[Updated]**
- None
**[Fixed]**
- [Radarr] CF `LQ` Fix `YTS` Condition.
=> [Radarr] CF `LQ` Fix `YTS` Condition

docs/Sonarr/Sonarr-Release-Profile-RegEx.md, docs/Sonarr/sonarr-collection-of-custom-formats.md, docs/json/sonarr/cf/extras.json, docs/json/sonarr/rp/optionals.json, includes/cf/sonarr-unwanted-uhd.md, includes/cf/sonarr-unwanted.md
**Purpose**
To prevent Extra / Bonus packs being eligible for season grabs.
**Approach**
Similar to Radarr Extras
**Learning**
=> Added: `Extras` CF for Sonarr

docs/Sonarr/sonarr-collection-of-custom-formats.md, docs/json/radarr/cf/lq.json, docs/json/radarr/cf/remux-tier-03.json, docs/json/radarr/cf/x265-no-hdrdv.json, docs/json/sonarr/cf/x265-no-hdrdv.json
**Purpose**
Address various issues and add CiNEPHiLES to Radarr Remux Tier 03.
**Approach**
=> feat(maintenance): various changes to the Starr CFs

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/Sonarr/sonarr-collection-of-custom-formats.md
**Purpose**
This should make it easier for users to compare the different audio options.
**Approach**
**Learning**
=> Replace the placeholder description of DTS-HD RSA

docs/json/sonarr/cf/web-tier-02.json
- add Miu and PHOENiX to WEB Tier 02
=> [Sonarr] add `Miu` and `PHOENiX` to `WEB Tier 02`

docs/json/sonarr/cf/hybrid.json
- Fixed quality modifier for remuxes
=> Fix PR#1340

docs/Sonarr/sonarr-collection-of-custom-formats.md
**Purpose**
Add UHD Boosts to table
**Learning**
=> feat(sonar) - add UHD Boosts to Streaming Services Table

docs/Sonarr/Sonarr-Release-Profile-RegEx.md, docs/json/radarr/cf/web-tier-03.json, docs/json/sonarr/cf/web-tier-03.json, docs/json/sonarr/rp/p2pRepackProper.json
**Purpose**
Fix #1373 
**Approach**
Add `NINJACENTRAL` to `WEB Tier 03` for both Sonarr and Radarr.
=> feat(starr): add NINJACENTRAL to WEB Tier 03

.github/labeler.yml
=> chore: update labels & sync

.github/labeler.yml
**Purpose**
Bring Sonarr directorys in `labeler.yaml` in order.
**Approach**
Move `docs/json/sonarr/naming/**`.
=> chore(labeler): sort Sonarr directory order

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, docs/Bazarr/scripts/index.md, docs/index.md, mkdocs.yml
**Purpose**
Several needed changes because of the change from personal GitHub to Organizations
**Approach**
- Changed: URL from personal to Organizations
- Added: Branch naming to Contributing Guidelines
- Added: Pull Request naming to Contributing Guidelines
- Added: DRAFT Pull Request - When doing a PR that is WIP to Contributing Guidelines
**Learning**
=> chore(backend): several backend changes

docs/Sonarr/Sonarr-Release-Profile-RegEx.md, docs/json/radarr/cf/scene.json, docs/json/sonarr/cf/scene.json, docs/json/sonarr/rp/optionals.json
**Purpose**
Added multiple groups, both new and old, to the "Scene" CF
**Approach**
Referenced trackers and releases.
- [ X ] Use github checklists. When solved, check the box and explain the answer.
- [ X ] These changes meet the standards for [contributing](https://github.com/TRaSH-/Guides/blob/master/.github/CONTRIBUTING.md).
- [ X ] I have read the [code of conduct](https://github.com/TRaSH-/Guides/blob/master/.github/CODE_OF_CONDUCT.md).
=> feat(starr): Additions to Scene CF

.github/labeler.yml
=> chore(labeler): fix labeler paths

.github/workflows/lint-markdown.yml
=> chore(GIT): update lint-markdown.yml to fix issues

.github/workflows/labeler.yml
=> chore(labeler): run when PR changes or master updates config

.github/workflows/conflicts.yml
=> chore(GHA): fix conflict labeler perms

.github/CONTRIBUTING.md
Seems that `CONTRIBUTING.md` doesn't support certain extra variables to open links on a new tab/window.
- Removed open in new window/tab, not working on this page
- formatting
=> style(backend): fixed formatting

docs/Hardlinks/How-to-setup-for/Synology.md, includes/hardlinks/docker-iptables-fix.sh
fix for #1433 and #1434 because of the mark jinja error
- Put the bash script in it's own file in the includes and use the Embedding external files to show it
=> fix(backed): Synology docker iptables-fix.sh

docs/Hardlinks/How-to-setup-for/Synology.md
Textual error.
Please, someone native English, review the iptables bit (on the bottom).
=> fixup! fix(backed): Synology docker iptables-fix.sh (#1435)

docs/Misc/How-to-setup-Torguard-for-port-forwarding.md
Updated the torguard affiliate code to be unique
Updated the torguard affiliate code to be unique
=> chore(backend): updated torguard affiliate code

docs/json/radarr/cf/anime-lq-groups.json, docs/json/sonarr/cf/anime-lq-groups.json
Resolve #1446 
Add `KQRM` to `Anime LQ Groups`.
=> feat(starr): Add KQRM to Anime LQ Groups

docs/json/radarr/cf/french-web-tier-02.json
Added the FR group `ONLYMOViE` to the `FR WEB Tier 02` CF.
=> feat(radarr-fr): Added ONLYMOViE to FR WEB Tier 02

docs/json/radarr/cf/french-uhd-bluray-tier-01.json, docs/json/radarr/cf/french-uhd-bluray-tier-02.json
Update the French guide to follow PR #1444
=> fix(radarr-fr): Updated score in both FR UHD Tier 01 and 02 to follow original guide

docs/Sonarr/sonarr-setup-quality-profiles-french-en.md, docs/Sonarr/sonarr-setup-quality-profiles-french-fr.md, includes/cf/sonarr-unwanted-uhd.md, includes/cf/sonarr-unwanted.md, includes/french-guide/sonarr-french-streaming-services-anime-en.md, includes/french-guide/sonarr-french-streaming-services-anime-fr.md, includes/french-guide/sonarr-french-unwanted-en.md, includes/french-guide/sonarr-french-unwanted-fr.md, includes/french-guide/sonarr-french-unwanted-uhd-en.md, includes/french-guide/sonarr-french-unwanted-uhd-fr.md
- Reviewed the presentation for Anime streaming services
- Added the UHD boost/cut
- Added the `Extra` CF to the Unwanted section
=> fix(sonarr-fr): Update the French guide

docs/Hardlinks/Replace-copies-with-hardlinks.md
Speedup Jdupes
Filter files based on specified criteria, in this case it will only compare the following extensions: mp4, mkv, avi
=> fix(guides): jdupes speedup

docs/Guide-Sync/index.md
Additionally, reorganized the Recyclarr section a little bit and added a small description.
=> Add Quality Profile feature set to the Guide Sync page

docs/Sonarr/Sonarr-Release-Profile-RegEx.md, docs/json/sonarr/cf/scene.json, docs/json/sonarr/rp/optionals.json
Resolve #1503 
Add `SuccessfulCrab` to Sonarr `Scene` CF and Sonarr Guide.
=> feat(sonarr): add SuccessfulCrab to Scene CF and Guide

docs/Sonarr/Sonarr-Release-Profile-RegEx.md, docs/json/radarr/cf/lq.json, docs/json/sonarr/cf/lq.json, docs/json/sonarr/rp/lqGroups.json
Bring the `LQ` CF and `LQ` RP back up-to-date.
=> feat(starr): update LQ CF and Sonarr v3 LQ RP

CONTRIBUTING.md
add requirements for groups being added to tiers
=> feat(docs): Add contributing requirements for tier groups

docs/Downloaders/qBittorrent/3rd-party-tools.md
Adding a new 3rd Party tool for qbittorrent
Adding docs
- [x ] Docs updated with tool features
- [ x] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [ x] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).
=> docs(qbittorrent): Added Qbitrr as a 3rd party tool

docs/json/radarr/cf/multi-audio.json, docs/json/sonarr/cf/multi-audio.json
- Now recognize (VOSTFR or VOST or VO) + Any VF
- Updated Regex
=> fix(french-starr): Update Multi-Audio CF

includes/sqp/1-workflow.md
FIX: #1493 
- #1493 
Improve the sentence of the workflow
=> fix(radarr): SQP-1 workflow sentence if limited sources

docs/updates.txt
Updated changelog, and testing if links work
=> # 2023-09-01 10:45

docs/Radarr/Tips/How-to-setup-language-custom-formats.md
=> fix(radarr): explain how original language is determined

docs/json/radarr/cf/lq.json, docs/json/sonarr/cf/lq.json, docs/json/sonarr/rp/lqGroups.json
Fix #1551 
Adjust regex in the `LQ` CFs and the Sonarr v3 `LQ` RP.
=> fix(starr): inaccurate Pahe regex

docs/Sonarr/Sonarr-Release-Profile-RegEx.md, docs/json/sonarr/cf/lq.json, docs/json/sonarr/rp/lqGroups.json
Fix #1559 
Add d3g to the `LQ` CF for Sonarr v4 and to the `LQ` RP for Sonarr v3.
=> feat(sonarr): add d3g to LQ

docs/Guide-Sync/index.md
- Recyclarr now supports deleting CFs and naming sync
- Separated RPs/CFs line into two, to show that Recyclarr supports deleting CFs (but not RPs).
=> Update features list for Recyclarr

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/Sonarr/sonarr-collection-of-custom-formats.md, docs/json/radarr/cf/french-voq.json, docs/json/sonarr/cf/french-voq.json, includes/french-guide/radarr-french-audio-version-en.md, includes/french-guide/radarr-french-audio-version-fr.md, includes/french-guide/sonarr-french-audio-version-en.md, includes/french-guide/sonarr-french-audio-version-fr.md
Add VOQ CF for Original Quebec movie as informative CF
Resolves #1572
=> feat(French-Starr): add VOQ (Version Originale Québecoise | Quebec Original Version) CF

docs/Sonarr/Sonarr-Release-Profile-RegEx.md, docs/json/radarr/cf/scene.json, docs/json/sonarr/cf/scene.json, docs/json/sonarr/rp/optionals.json
=> feat(starr): Add NHTFS to Scene CF

docs/json/radarr/cf/french-audio.json, docs/json/sonarr/cf/french-audio.json
Fixes #1609 
Apply the **Language: Prefer Language X** tips
=> fix(french-starr): remove non-French Language conditions in the French Audio CF

docs/json/radarr/cf/web-tier-02.json, docs/json/sonarr/cf/web-tier-02.json
Fixes #1556 
Add `SbR` to `WEB Tier 02`.
=> feat(starr): add SbR to WEB Tier 02

docs/Downloaders/Deluge/Tips/Unraid-Mover.md
adds tabs for installation methods and updates config description for mover script guide
add tabs and update config description
=> update(deluge-mover): update mover script guide for changes

docs/Downloaders/qBittorrent/Tips/How-to-run-the-unRaid-mover-for-qBittorrent.md
=> fix(guides): Fixed typo "qbittorrent-qpi"

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/Sonarr/sonarr-collection-of-custom-formats.md
=> fix(guides): add DTS-X details

includes/cf/audio-info.md
Corrected some spelling errors and cleaned up grammar for clarity.
=> fix(guide): corrected grammar and typo: audio-info.md

docs/json/radarr/cf/extras.json, docs/json/radarr/cf/special-edition.json, docs/json/sonarr/cf/extras.json
=> fix(radarr): add `Extended Clip` to Extras CF

docs/json/sonarr/cf/french-web-tier-02.json
Added the FR group `TAT` to the FR WEB Tier 02 CF.
=> feat(Sonarr-fr): add `TAT` to FR WEB Tier 2

docs/Sonarr/sonarr-collection-of-custom-formats.md, docs/Sonarr/sonarr-setup-quality-profiles-anime.md, docs/json/radarr/cf/anime-lq-groups.json, docs/json/radarr/cf/anime-raws.json, docs/json/radarr/cf/anime-web-tier-01-muxers.json, docs/json/radarr/cf/anime-web-tier-04-official-subs.json, docs/json/sonarr/cf/abema.json, docs/json/sonarr/cf/anime-lq-groups.json, docs/json/sonarr/cf/anime-raws.json, docs/json/sonarr/cf/anime-web-tier-01-muxers.json, docs/json/sonarr/cf/anime-web-tier-04-official-subs.json, docs/updates.txt, includes/cf/sonarr-streaming-services-anime.md
Updates to the Sonarr and Radarr Anime CFs
Fix for the Sonarr version badge on the Anime guide page
=> feat(anime): updates to sonarr and radarr CFs

docs/Sonarr/Sonarr-Release-Profile-RegEx.md, docs/json/radarr/cf/scene.json, docs/json/sonarr/cf/scene.json, docs/json/sonarr/rp/optionals.json
Match `SURCODE` & `B0MBARDIERS` as a Scene group.
Add `SURCODE` & `B0MBARDIERS` to the `Scene` CF.
=> feat(starr): add SURCODE & B0MBARDIERS to Scene CF

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/Sonarr/sonarr-collection-of-custom-formats.md, docs/json/radarr/cf/dv-hdr10plus.json, docs/json/sonarr/cf/dv-hdr10.json, docs/json/sonarr/cf/dv-hdr10plus.json
Add a custom format for `DV HDR10Plus` that was just added to the Starrs.
Fix #1285
=> feat(starr): add DV HDR10Plus CF

.github/labeler.yml
=> chore(gha): fix labeler

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/Sonarr/sonarr-collection-of-custom-formats.md
=> proof(improve-cf-desc): language clarification and grammar

docs/json/sonarr/cf/hidive.json
Allow `HIDI` to be fall under the `HIDIVE` custom format.
=> fix(sonarr): match `HIDI` as HIDIVE

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/Sonarr/sonarr-collection-of-custom-formats.md, docs/json/radarr/cf/internal.json, docs/json/sonarr/cf/internal.json
For those that prefer scene releases may want to boost internals as they generally have higher settings that may not conform to ruleset.
In some rare cases P2P use also INTERNAL.
=> feat(Starr) add NEW CF `INTERNAL`

docs/Sonarr/Sonarr-Release-Profile-RegEx.md, docs/json/radarr/cf/scene.json, docs/json/sonarr/cf/scene.json, docs/json/sonarr/rp/optionals.json
Fix `Scene` CF mismatching `WEB` in the movie/show/episode title.
Check for year before `WEB` in the regex.
=> fix(starr): Scene CF mismatching title

includes/cf/sonarr-all-hdr-formats.md, includes/cf/sonarr-optional.md, includes/merge-quality/sonarrv4-current-logic.md
Fix Sonarr case sensitive issue in links
Fix Sonarr case sensitive issue in links
=> fix(guide): Sonarr case sensitive issue

docs/Misc/How-to-setup-Torguard-for-port-forwarding.md
Updated the torguard affiliate code
- Updated the torguard affiliate code
- Added warning message box `If the US server doesn't work for you use another country`
=> chore(misc): updated the torguard affiliate code

docs/update.txt
=> chore(test): redirect test

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/Sonarr/sonarr-collection-of-custom-formats.md
sorts the streaming services and certain cf's in alphabetical order in sonarr and radarr cf collection table
ABC....
=> sort(cf-collections): alphabetically sort tables

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/Sonarr/sonarr-collection-of-custom-formats.md
sorts the streaming services and certain cf's in alphabetical order in sonarr and radarr cf collection table
ABC....
=> sort(cf-collections): alphabetically sort tables (no-colons)

docs/Radarr/Radarr-recommended-naming-scheme.md, docs/Sonarr/Sonarr-recommended-naming-scheme.md, docs/json/radarr/naming/radarr-naming.json, docs/json/sonarr/naming/sonarr-naming.json
Remove Emby warning for ID and add IMDB ID to naming scheme
Removed Emby warning for ID and added IMDB ID to naming scheme
=> feat(starr): Added imdb id to Emby naming scheme

docs/Sonarr/index.md
Remove v3 version from index
Removed v3 version from index
=> fix(sonarr): remove v3 version from index

docs/Hardlinks/How-to-setup-for/Synology.md
update the link to the pullio documentation, seems like it was moved to a `scripts` subdirectory
N/A
=> update link to Pullio documentation

docs/Sonarr/sonarr-collection-of-custom-formats.md, docs/json/sonarr/cf/upscaled.json, includes/cf/sonarr-unwanted-uhd.md
- Add NEW CF Upscaled to Sonarr
- Add UPS to CF Upscaled
- Fix: #1732
=> feat(starr): Add upscaled to Sonarr and add UPS

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/Sonarr/sonarr-collection-of-custom-formats.md
Improve and update the Custom Formats Collection Description.
Improve and update the Custom Formats Collection Description.
Review the existing descriptions
===[Radarr]===
===[Sonarr]===
=> feat(guide): Collection of Custom Formats - HQ Release Groups - Improve description

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/Sonarr/sonarr-collection-of-custom-formats.md, includes/cf-descriptions/dolby-vision.md, includes/cf-descriptions/dv-hdr10.md, includes/cf-descriptions/dv-hdr10plus.md, includes/cf-descriptions/dv-hlg.md, includes/cf-descriptions/dv-sdr.md, includes/cf-descriptions/dv.md, includes/cf-descriptions/hdr-formats-info.md, includes/cf-descriptions/hdr-undefined.md, includes/cf-descriptions/hdr.md, includes/cf-descriptions/hdr10.md, includes/cf-descriptions/hdr10plus.md, includes/cf-descriptions/hlg.md, includes/cf-descriptions/pq.md
Improve and update the Custom Formats Collection Description.
Improve and update the Custom Formats Collection Description.
Review the existing descriptions
===[Radarr]===
===[Sonarr]===
=> feat(guide): Collection of Custom Formats - HDR Formats - Improve description

docs/Downloaders/qBittorrent/3rd-party-tools.md
Update qBitrr doc to reflect recent updates
=> Docs/qbittorrent qBitrr description update

docs/Misc/x265-4k.md
Fix the Sonarr link to the Golden Rule.
Update the Sonarr link to point to the Golden Rule CF.
=> fix(sonarr): golden rule link

docs/Misc/how-to-provide-a-docker-compose.md
=> feat(guide): clarify sharing docker compose

docs/Misc/how-to-provide-a-docker-compose.md
=> fix(guide): clarify sharing docker compose

docs/json/radarr/cf/av1.json, docs/json/sonarr/cf/av1.json
Avoid `AV1` by default.
Change default score of `AV1` to
=> feat(starr): change AV1 default score to -10000

docs/Hardlinks/Examples.md
Add links to the full downloader guides
Added links to the full downloader guides
=> feat(guide): hardlinks - add links to the full downloader guide

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/Sonarr/sonarr-collection-of-custom-formats.md, docs/json/radarr/cf/itvx.json, docs/json/sonarr/cf/itvx.json, includes/cf-descriptions/itvx.md
Add Custom Format for streaming service ITVX
Fix: #1797 
Created CF for streaming service ITVX
=> feat(starr): Add Custom Format for streaming service ITVX

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/Sonarr/sonarr-collection-of-custom-formats.md, docs/json/radarr/cf/viu.json, docs/json/sonarr/cf/viu.json, includes/cf-descriptions/viu.md
Add Custom Format for streaming service VIU
Created CF for streaming service VIU
=> feat(starr): Add Custom Format for streaming service VIU

.github/workflows/deploy.yml
=> (chore): deploy - add concurrence and only build latest

docs/SQP/1-4k.md, docs/SQP/1.md, docs/SQP/2.md, docs/SQP/3.md, docs/SQP/4.md, docs/SQP/5.md, docs/SQP/index.md
looking at options to remove SQP from the google search results
Adding `<meta name="robots" content="noindex, nofollow" />` to SQP markdown files, looking at options to create a robots.txt
=> chore(backend): remove sqp from google search results

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/Sonarr/sonarr-collection-of-custom-formats.md
Categorize the streaming services
=> style(guide): Categorize streaming services

docs/json/radarr/cf/french-vfq.json, docs/json/sonarr/cf/french-vfq.json
=> fix(french-starr): update VFQ CFs with right condition

docs/Sonarr/sonarr-collection-of-custom-formats.md, docs/json/sonarr/cf/freeleech.json
=> feat(sonarr): add FreeLeech custom format

.vscode/settings.json, docs/json/radarr/cf/anime-bd-tier-01-top-seadex-muxers.json, docs/json/radarr/cf/anime-bd-tier-02-seadex-muxers.json, docs/json/radarr/cf/anime-lq-groups.json, docs/json/radarr/cf/anime-web-tier-01-muxers.json, docs/json/radarr/cf/anime-web-tier-02-top-fansubs.json, docs/json/radarr/cf/dubs-only.json, docs/json/sonarr/cf/anime-bd-tier-01-top-seadex-muxers.json, docs/json/sonarr/cf/anime-bd-tier-02-seadex-muxers.json, docs/json/sonarr/cf/anime-lq-groups.json, docs/json/sonarr/cf/anime-web-tier-01-muxers.json, docs/json/sonarr/cf/anime-web-tier-02-top-fansubs.json, docs/json/sonarr/cf/dubs-only.json, docs/updates.txt
=> feat(starr anime): updates to various CFs

docs/json/radarr/cf/upscaled.json, docs/json/sonarr/cf/upscaled.json
Fix #1817 
Adjust the regex for both the Sonarr and the Radarr CF.
=> fix(starr): Upscale false positives

includes/sqp/2-why.md
Rephrased the sentences to make it more clear.
Just a rephrase of the statements here. The "must support DoVi from start to finish" was a little harsh for people with Samsung TVs, specially because down under in the guide there is a way to configure to avoid DV (WEB-DL) and boost HDR10+.
Just trying to make the text more clear.
=> style(2-why.md): Rephrase SQP2's "Why?" to make it clearer.

docs/json/radarr/cf/3d.json
Fix #1819 
Adjust the regex for the Radarr CF.
=> fix(radarr): 3D false positives

docs/Radarr/Tips/How-to-setup-language-custom-formats.md
On Discord, someone was confused about where the score goes. Mention that it goes in the profile! :)
Edit a tiny amount of text to be a tiny amount better.
- [*] These changes meet the standards for [contributing](https://github.com/TRaSH-Guides/Guides/blob/master/CONTRIBUTING.md).
- [*] I have read the [code of conduct](https://github.com/TRaSH-Guides/Guides/blob/master/.github/CODE_OF_CONDUCT.md).
=> Make the text about adding the CF and setting the score in your profile a little clearer

docs/json/radarr/cf/lq.json, docs/json/sonarr/cf/lq.json
=> feat(Starr): Add iVy to LQ

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/Sonarr/sonarr-collection-of-custom-formats.md, docs/json/radarr/cf/x265.json, docs/json/radarr/cf/x266.json, docs/json/sonarr/cf/x266.json
=> feat(Starr:) Add New x266 Custom Formats

docs/Downloaders/qBittorrent/Tips/How-to-run-the-unRaid-mover-for-qBittorrent.md
Updated line numbers referenced in [mover.py](https://raw.githubusercontent.com/StuffAnThings/qbit_manage/master/scripts/mover.py)
Update documentation to match the current mover.py
=> fix(guide): update line numbers in mover.py

includes/cf/radarr-audio.md
fix typo in audio section
fixed typo in audio section
=> feat(guide): fix typo in audio section

.github/workflows/conflicts.yml, .github/workflows/deploy.yml, .github/workflows/labeler.yml, .github/workflows/lint-editor.yml, .github/workflows/lint-markdown.yml, .github/workflows/lint-yaml.yml, .github/workflows/metadata-validation.yml
Stop duplicate GHA and misc workflow cleanup
=> (chore): quiet CI

docs/json/sonarr/cf/remux-tier-01.json, docs/json/sonarr/cf/remux-tier-02.json
Update Sonarr remux tiers in line with recent changes to Radarr remix tiers
None
=> feat(guides): Update Sonarr Remux Tiers

.all-contributorsrc, contributors.md, docs/index.md
add all contributors to a list so we can show them in the guide
installed [all contributor bot](https://allcontributors.org/)
added link in the index page
=> chore(backend): testing contributers list

docs/Hardlinks/How-to-setup-for/Synology.md, mkdocs.yml
Updated guide.
Removed too much info on the subfolders part (the breakdown). 
Removed unnecessary warnings / infos.
Make the guide a bit more simple to follow.
Removing info that seems overwhelming.
=> feat(Synology): Simplify Synology Guide

includes/cf/radarr-optional-uhd.md, includes/cf/sonarr-optional-uhd.md
Fix Optional UHD include error
Replaced include link for written description
=> fix(guide): Fix Optional UHD include error

docs/Radarr/Radarr-collection-of-custom-formats.md, includes/cf-descriptions/bcore.md, includes/sqp/2-workflow.md, includes/sqp/3-workflow.md, includes/sqp/4-why.md, includes/sqp/4-workflow.md, includes/sqp/5-workflow.md
adds imax description and imax enhanced description update to radarr cf collection
addresses a few grammar/language things i happen to notice during this
[discord convo/thread](https://discord.com/channels/492590071455940612/1227634246152228914)
=> update(imax-descriptions): language and descriptions around imax(e)

docs/json/sonarr/cf/lq.json
Remove `NERO` from Sonarr LQ as it is a French Scene
=> update(sonarr): remove NERO from LQ

docs/Bazarr/Setup-Guide.md
add (Sonarr) to section [Options and Path Mappings]  to the Setup-Guide for Bazarr because it was missing.
style(Bazarr)
Update style for Bazarr Setup-Guide
More clear and understandable
=> style(Bazarr): add missing (Sonarr) for Bazarr Setup-Guide.md

docs/json/radarr/cf/anime-bd-tier-06-fansubs.json, docs/json/radarr/cf/anime-web-tier-02-top-fansubs.json, docs/json/radarr/cf/dubs-only.json, docs/json/sonarr/cf/anime-bd-tier-06-fansubs.json, docs/json/sonarr/cf/anime-web-tier-02-top-fansubs.json, docs/json/sonarr/cf/dubs-only.json
Updating various CFs to fix issues
=> feat(anime): updates to CFs

docs/Hardlinks/How-to-setup-for/Synology.md
Added prowlarr to default compose.
Made sure this is reflected in the guide.
=> update(syno/compose): add prowlarr to default

docs/json/radarr/cf/lq.json, docs/json/sonarr/cf/lq.json
Resolve #1905 
Add `ShieldBearer` to `LQ` CFs.
=> feat(starr): add ShieldBearer to LQ

docs/Downloaders/Deluge/Tips/Unraid-Mover.md, docs/Downloaders/qBittorrent/Tips/How-to-run-the-unRaid-mover-for-qBittorrent.md, docs/Hardlinks/How-to-setup-for/Dockstarter.md, docs/Sonarr/sonarr-collection-of-custom-formats.md
fix several broken/forgotten ~~links~~ anchors
Noticed that some ~~links~~ anchors where broken/forgotten so fixed them.
=> chore(guides): fix several broken/forgotten anchors

docs/json/radarr/cf/anime-web-tier-05-fansubs.json, docs/json/sonarr/cf/anime-web-tier-05-fansubs.json
Adds SobsPlease group to web fantranslation. They do fantranslations and are currently the only group that makes proper Girls Band Cry subs (there are no official ones)
=> feat(starr): Add SobsPlease

docs/json/radarr/cf/anime-bd-tier-01-top-seadex-muxers.json, docs/json/radarr/cf/anime-bd-tier-03-seadex-muxers.json, docs/json/radarr/cf/anime-lq-groups.json, docs/json/radarr/cf/anime-web-tier-01-muxers.json, docs/json/sonarr/cf/anime-bd-tier-01-top-seadex-muxers.json, docs/json/sonarr/cf/anime-bd-tier-03-seadex-muxers.json, docs/json/sonarr/cf/anime-lq-groups.json, docs/json/sonarr/cf/anime-web-tier-01-muxers.json
Updates to various Anime CFs based on feedback from the team and community
=> feat(anime): update CFs

docs/json/radarr/quality-size/movie.json
=> feat(radarr): update quality size

docs/updates.txt
=> chore(Changelog): Update: # 2024-05-15 12:00

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/json/radarr/cf/repack3.json, docs/json/radarr/quality-profiles/hd-bluray-web.json, docs/json/radarr/quality-profiles/remux-web-1080p.json, docs/json/radarr/quality-profiles/remux-web-2160p.json, docs/json/radarr/quality-profiles/sqp-1-1080p.json, docs/json/radarr/quality-profiles/sqp-1-2160p.json, docs/json/radarr/quality-profiles/sqp-2.json, docs/json/radarr/quality-profiles/sqp-3.json, docs/json/radarr/quality-profiles/sqp-4.json, docs/json/radarr/quality-profiles/sqp-5.json, docs/json/radarr/quality-profiles/uhd-bluray-web.json, includes/cf/radarr-misc.md
To allow for preferential scoring for a third Repack or Proper release
None
=> feat(radarr): Add New `Repack3` Custom Format

CONTRIBUTORS.md, docs/json/radarr/cf/lq-release-title.json
Because of their inconsistent naming scheme, they weren't always recognized as a release group.
Added RlsGrp `TEKNO3D` to `LQ (Release Title)`
=> feat(radarr): Add RlsGrp `TEKNO3D` to `LQ (Release Title)`

docs/json/radarr/cf/lq-release-title.json, docs/json/radarr/cf/lq.json
Fix #1961 
Move `SWTYBLZ` from `LQ` CF to `LQ Release Title` CF.
=> chore(radarr): move SWTYBLZ to LQ Release Title

docs/updates.txt
Publish an update to users with the latest Guides changes
None
=> chore(guides): Update changelog to 2024-06-09

docs/Bazarr/Tips/Bazarr-suggested-scoring.md, docs/Downloaders/Deluge/Basic-Setup.md, docs/Downloaders/Deluge/Port-Forwarding.md, docs/Downloaders/Deluge/Using-Labels.md, docs/Downloaders/Deluge/index.md, docs/Downloaders/NZBGet/Basic-Setup.md, docs/Downloaders/NZBGet/Paths-and-Categories.md, docs/Downloaders/SABnzbd/Basic-Setup.md, docs/Downloaders/SABnzbd/Paths-and-Categories.md, docs/Downloaders/qBittorrent/3rd-party-tools.md, docs/Downloaders/qBittorrent/Basic-Setup.md, docs/Downloaders/qBittorrent/How-to-add-categories.md, docs/Downloaders/ruTorrent/ruTorrent-Basic-Setup.md, docs/Hardlinks/How-to-setup-for/Docker.md, docs/Hardlinks/How-to-setup-for/Dockstarter.md, docs/Hardlinks/How-to-setup-for/Native.md, docs/Hardlinks/How-to-setup-for/Synology.md, docs/Hardlinks/How-to-setup-for/TrueNAS-Core.md, docs/Plex/Tips/Optimal-plex-client-settings.md, docs/Plex/Tips/Plex-media-server.md, docs/Plex/profiles/index.md, docs/Radarr/Tips/Merge-quality.md, docs/Radarr/Tips/Radarr-show-unknown-movie-items.md, docs/Radarr/radarr-setup-quality-profiles.md, docs/Sonarr/sonarr-setup-quality-profiles.md, docs/index.md, includes/cf/score-attention.md, includes/support.md
- Changed discords shields.io to a click here button, hopefully to solve the rate limiting issue.
- Changed `{! include-markdown "../../../includes/support.md" !}` to `--8<-- "includes/support.md"` to be more consistent with the other pages and less failures depending on where the page is located
=> chore(guide): Changed discord shield to button

docs/updates.txt
=> chore(guides): Update changelog to 2024-06-13

docs/Radarr/radarr-setup-quality-profiles-anime.md, docs/Sonarr/sonarr-setup-quality-profiles-anime.md
=> fix(anime): Update language regarding scores to use

.github/scripts/update-changelog.sh, .github/workflows/automatic-changelog.yml
Automatically generate a changelog from conventional commit messages either weekly or manually.
Fetch the last time the `updates.txt` was edited, check all the commits since that date using `git log` and then filter out bot commits and commits not following conventional commits.
=> feat(ci): automatic changelog

.github/workflows/automatic-changelog.yml
Remove unnecessary chmod for the update script.
Remove the chmod line in the workflow.
=> fix(ci): remove unnecessary chmod

docs/json/sonarr/cf/lq.json
Resolve #2009 
Add `OFT` to the `LQ` CF for Sonarr.
=> feat(sonarr): add OFT to LQ CF

docs/Hardlinks/Check-if-hardlinks-are-working.md, docs/Hardlinks/Hardlinks-and-Instant-Moves.md
Add info about exFAT not supporting hardlinks and that it should be avoided.
Added info about exFAT not supporting hardlinks and that it should be avoided.
=> feat(Guide): Add exFAT hardlink limitation to hardlinks guide

docs/Downloaders/qBittorrent/Tips/How-to-run-the-unRaid-mover-for-qBittorrent.md
add info to use Qbt port
added info to use Qbt port
=> fix(guide): qBit Mover - Add info to use qBt WebGUI port

docs/Hardlinks/Replace-copies-with-hardlinks.md
give more accurate detail of usage and standard options
language stuff
stuff and things
=> update(hardlinks/jdupes): include hashdb feature and expand on installation and usage

CONTRIBUTING.md
add updated container instructions link in development section
=> update(docs/contributing): reference updated installation instructions for mkdocs container

docs/Bazarr/index.md
=> fix(bazarr): inconsistent headers

docs/Hardlinks/How-to-setup-for/Windows.md, docs/Hardlinks/How-to-setup-for/index.md
Recommendations and suggestions for Windows users on how to set up their File and Folder Structure
Added recommendations and suggestions for Windows users on how to set up their File and Folder Structure
=> feat(guide): Hardlinks - File and Folder Structure for Windows

docs/json/radarr/cf/anime-dual-audio.json, docs/json/sonarr/cf/anime-dual-audio.json
Reverts TRaSH-Guides/Guides#2054
Reverting this PR as it breaks part of the guides
=> Revert "feat(starr-anime): Add Korean to Anime Dual Audio"

docs/json/radarr/cf/anime-raws.json, docs/json/sonarr/cf/anime-raws.json
Asuka Raws is a raws-only anime group
Closes https://github.com/TRaSH-Guides/Guides/issues/2066
Added to the sonarr and radarr anime raws CF
=> feat(starr-anime): Add AsukaRaws to Anime Raws

docs/Glossary/index.md
fixed broken links (MD051) and Admonitions formatting
fixed broken links (MD051) and Admonitions formatting
=> fix(guide): Glossary formatting and broken links

includes/merge-quality/sonarr-current-logic.md
=> fix(sonarr): update comparison logic

docs/Downloaders/Deluge/Port-Forwarding.md, docs/Downloaders/qBittorrent/Port-forwarding.md, includes/downloaders/port-forwarding.md
The downloaders section for port-forwarding was missing information on why port-forwarding would be needed.
Added the following information
- Why port-forwarding
- How to port-forward
- How to Check if Your VPN is Working
- How to Check if a Port is Open or Closed
=> feat(guide): Add information to the port forwarding guide

docs/Hardlinks/Check-if-hardlinks-are-working.md
=> fix(guide): label check hardlink methods & add windows method fsutil

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/Sonarr/sonarr-collection-of-custom-formats.md, docs/json/radarr/cf/my5.json, docs/json/sonarr/cf/my5.json, includes/cf-descriptions/my5.md
Add MY5 (the UK streaming service for channel 5)
=> feat(guide): Add streaming service `MY5`

docs/Radarr/Radarr-collection-of-custom-formats.md
Single character missing, fixes spelling and therefore the sentence.
=> style(Radarr): Fixed Spelling Issue

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/Sonarr/sonarr-collection-of-custom-formats.md, docs/json/radarr/cf/cbc.json, docs/json/sonarr/cf/cbc.json, includes/cf-descriptions/cbc.md
Add Streaming Services CBC (Canada) Custom Format to Sonarr/Radarr
=> feat(guide): Starr - Add Streaming Services `CBC` (Canada) Custom Format

docs/Guide-Sync/index.md
Notifiarr now supports TRaSH QP => Starr QP Sync
- Pending Notifiarr Merge to prod
=> feat(guide-sync): notifiarr profile support

docs/Sonarr/sonarr-collection-of-custom-formats.md
Fixed the issue with an error containing a link to '#rtbf,'
Fixed: anchor link.
=> fix(starr): Update of the French Guide

includes/cf/audio-info.md, includes/cf/audio-limitations-atv.md, includes/cf/dv-info-green-purple.md, includes/cf/dv-info-profiles.md
Several small grammar corrections
Several small grammar corrections like `a` that should be `an`
=> style(guide): Several small grammar corrections

docs/json/radarr/cf/htsr.json, docs/json/sonarr/cf/htsr.json, includes/cf-descriptions/htsr.md
ran across a tag that was previously not included, it isn't really common or anything but it was easy enough to add, why not
decided to proof edit the service's description while I was at it....
let me know what you think
=> update(starr/cf): add additional service tag in regex and proof-edit definition

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/Sonarr/sonarr-collection-of-custom-formats.md, docs/json/radarr/cf/german-dl.json, docs/json/sonarr/cf/german-dl.json, includes/cf-descriptions/language-german-dl.md
Last minute Custom Format name change
Renamed the Custom Format and links to the Custom Format
=> fix(starr): last minute CF name change for German DL

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/Sonarr/sonarr-collection-of-custom-formats.md, docs/json/radarr/cf/language-german-dl.json, docs/json/sonarr/cf/language-german-dl.json
This is a backend fix for the 3rd party apps
=> fix(backend): Related stuff for 3rd party apps

docs/json/radarr/cf/lq.json
Bad audio, gore movie scenes are cut, and weird warnings about alcohol throughout the movie.
Also, they did something weird with the audio track where it gets detected as “Hindi” for some reason.
Added:  `BAUCKLEY` to Radarr `LQ` Custom Format
=> feat(Guide): Add `BAUCKLEY` to Radarr `LQ` Custom Format

docs/File-and-Folder-Structure/Check-if-hardlinks-are-working.md, docs/File-and-Folder-Structure/Hardlinks-and-Instant-Moves.md, docs/File-and-Folder-Structure/How-to-set-up/index.md, docs/File-and-Folder-Structure/Replace-copies-with-hardlinks.md, docs/File-and-Folder-Structure/index.md
Fix broken links in the hardlinks index page.
Fix broken links on the hardlinks index page and address minor inconsistencies in wording and grammar mistakes.
=> fix(guide): Fix broken links in the hardlinks index page

docs/Sonarr/sonarr-collection-of-custom-formats.md
Update Sonarr Season Pack custom format description
- Update description to clarify that Sonarr now uses its new Release Type custom format condition
- Addresses #2182
None
=> feat(Guides): Update Sonarr Season Pack custom format description

docs/json/radarr/quality-profiles/german-hd-bluray-web.json, docs/json/radarr/quality-profiles/german-uhd-bluray-web-alternative.json, docs/json/radarr/quality-profiles/german-uhd-bluray-web.json, docs/json/radarr/quality-profiles/german-uhd-remux-web.json
German QP sorting fix for the 3rd party sync apps
German QP sorting fix for the 3rd party sync apps
=> chore(guide): German QP sorting fix for the 3rd party sync apps

docs/json/radarr/cf-groups/advanced-audio-formats.json, docs/json/radarr/cf-groups/hdr-formats.json, docs/json/radarr/cf-groups/misc-optional.json, docs/json/radarr/cf-groups/misc-uhd-optional.json, docs/json/radarr/cf-groups/movie-versions-noremux.json, docs/json/radarr/cf-groups/movie-versions.json, docs/json/radarr/cf-groups/sqp-1-1080p-misc-optional.json, docs/json/radarr/cf-groups/sqp-1-2160p-misc-optional.json, docs/json/radarr/cf-groups/sqp-2-3-4-5-misc-optional.json
chore(guide): Updated QP excludes for the 3rd party sync apps
chore(guide): Updated QP excludes for the 3rd party sync apps
=> chore(guide): Updated QP excludes for the 3rd party sync apps

docs/Radarr/radarr-setup-quality-profiles-german-en.md, includes/german-guide/radarr-cf-german-remux-web-scoring-en.md, includes/german-guide/radarr-cf-german-resolution-scoring-hd-only-en.md, includes/german-guide/radarr-cf-german-uhd-bluray-web-scoring-en.md
It was unclear which qualities should be merged for which profile.
We clarified it in the individual profiles sections.
=> feat(radarr): Clarify the use of merged qualities for the German Guide

docs/json/radarr/cf/lq.json
- Update the LQ custom format with newly discovered groups
- Fix: #2201
=> feat(Guides): Add new groups to LQ custom format

README.md
Time to update the GitHub readme
Updated the GitHub readme
=> chore(guide): Updated README.md

docs/json/sonarr/cf/french-anime-fansub.json
Added `Yangire-Raws` to FR Sonarr anime fansub
=> feat(sonarr-anime): Add Yangire-Raws to FR anime fansub

docs/Radarr/Radarr-collection-of-custom-formats.md, docs/json/radarr/cf-groups/misc-optional.json, docs/json/radarr/cf-groups/misc-uhd-optional.json, docs/json/radarr/cf-groups/sqp-1-1080p-misc-optional.json, docs/json/radarr/cf-groups/sqp-1-2160p-misc-optional.json, docs/json/radarr/cf-groups/sqp-2-3-4-5-misc-optional.json, docs/json/radarr/cf/black-and-white-editions.json, includes/cf/radarr-misc-optional.md, includes/sqp/1-4k-cf-scoring-sqp1.md, includes/sqp/hd-radarr-misc-optional.md
=> feat(Radarr): Add new Black and White Editions custom format

docs/Radarr/Radarr-collection-of-custom-formats.md
Fix formatting in the table
Fixed formatting in the table
=> style(radarr): table formatting

.github/workflows/pr-naming-check.yml
Updating the PR naming check regex for stricter controls
=> feat(gha): update pr naming check regex

docs/json/radarr/cf/web-tier-03.json, docs/json/sonarr/cf/web-tier-03.json
Add BYNDR to WEB Tier 03 for Radarr and Sonarr
Modify the WEB Tier 03 custom formats for Radarr and Sonarr to add a match for BYNDR
None
=> feat(Starr): Add BYNDR to WEB Tier 03

docs/json/radarr/cf/anime-web-tier-02-top-fansubs.json, docs/json/sonarr/cf/anime-web-tier-02-top-fansubs.json
Add MALD and Half-Baked to Anime Web Tier 02 due to consistent high quality web releases
Copy anime regex for these two groups
=> feat(starr-anime): Add MALD and Half-Baked to Anime Web Tier 2

CONTRIBUTING.md
Add `quality-profile` and `cf-groups` info to `CONTRIBUTING.md`
Added `quality-profile` and `cf-groups` info to `CONTRIBUTING.md`
=> feat(guide): Add `quality-profile` and `cf-groups` info to `CONTRIBUTING.md`

CONTRIBUTING.md
Fixed: broken link `CONTRIBUTING.md`
Fixed: broken link `CONTRIBUTING.md`
=> fix(guide): Fixed: broken link `CONTRIBUTING.md`

docs/js/hide_announce.js
=> feat(gha): change hide_announce to evaluate again hostname

.github/workflows/deploy-pr.yml
=> feat(gha): remove redundant sha lookup

docs/File-and-Folder-Structure/Examples.md
Removed outdated NZBGet message
Removed outdated NZBGet message
=> fix(hardlinks): Removed outdated NZBGet message

docs/json/radarr/cf-groups/dolby-vision-incompatible-devices.json, docs/json/radarr/cf-groups/required-golden-rule-hd.json, docs/json/radarr/cf-groups/required-golden-rule-uhd.json, docs/json/radarr/quality-profiles/german-hd-bluray-web.json, docs/json/radarr/quality-profiles/german-hd-remux-web.json, docs/json/radarr/quality-profiles/german-uhd-bluray-web-alternative.json, docs/json/radarr/quality-profiles/german-uhd-bluray-web.json, docs/json/radarr/quality-profiles/german-uhd-remux-web.json, docs/json/radarr/quality-profiles/hd-bluray-web.json, docs/json/radarr/quality-profiles/remux-2160p-alternative.json, docs/json/radarr/quality-profiles/remux-2160p-combined.json, docs/json/radarr/quality-profiles/sqp-2.json, docs/json/radarr/quality-profiles/sqp-3.json, docs/json/radarr/quality-profiles/sqp-4.json, docs/json/radarr/quality-profiles/sqp-5.json, docs/json/sonarr/cf-groups/dolby-vision-incompatible-devices.json, docs/json/sonarr/cf-groups/streaming-services-anime.json
Fix Profile exclusions
Added Profile exclusions for some groups and removed forced CF that now are selectable
=> fix(guide-sync): Profile exclusions

includes/cf-descriptions/generated-dynamic-hdr.md
Improved `Generated Dynamic HDR` Custom Formats description
Improved `Generated Dynamic HDR` Custom Formats description
=> fix(starr): Improved `Generated Dynamic HDR` Custom Formats description

docs/Radarr/Radarr-collection-of-custom-formats.md
`Line/Mic Dubbed` is something you see more commonly with German releases
Moved `Line/Mic Dubbed` Custom Format to the German Misc
=> feat(radarr): Move `Line/Mic Dubbed` Custom Format to the German Misc

.github/ISSUE_TEMPLATE/bug-error-found-in-the-guide.yml
=> style(misc): fixed typo in the issue template

docs/json/radarr/cf/lq-release-title.json, docs/json/radarr/cf/lq.json, docs/json/sonarr/cf/lq-release-title.json, docs/json/sonarr/cf/lq.json
RlsGrp `Feranki1980` Creates Microsized Releases
Added RlsGrp `Feranki1980` to Custom Format `LQ` and `LQ (Release Title)`
=> feat(starr): Add RlsGrp `Feranki1980` to Custom Format `LQ` and `LQ (Release Title)`

docs/json/radarr/cf/generated-dynamic-hdr.json
Closes #2324 
Add VD0N to Generated Dynamic HDR CF
None
=> feat(radarr): Add VD0N to Generated Dynamic HDR CF

docs/json/radarr/quality-profiles/anime-remux-1080p.json, docs/json/sonarr/quality-profiles/anime-remux-1080p.json
fix(guide-sync): Add missing quality sources for the new  Anime profiles take 2
fix(guide-sync): Add missing quality sources for the new  Anime profiles take 2
=> fix(guide-sync): Add missing quality sources for the new  Anime profiles take 2

CONTRIBUTING.md
Added Index
Added Index
Added Index
=> chore(guide): Update CONTRIBUTING.md

docs/json/radarr/cf-groups/optional-misc.json
Added missing excludes for SQP 2-5 to [Optional] Miscellaneous
Added missing excludes for SQP 2-5 to [Optional] Miscellaneous
=> fix(guide-sync): Added excludes to [Optional] Miscellaneous

docs/Glossary/index.md
Fix #2127 
Add a `SCENE` entry to the Glossary.
=> feat(glossary): add SCENE

docs/json/radarr/quality-profiles/french-multi-vo-uhd-bluray-web.json, docs/json/radarr/quality-profiles/french-multi-vo-uhd-remux-web.json
Fixed issue with re-using the same template
=> fix(guide-sync): `French MULTi.VO` profiles for Radarr

docs/File-and-Folder-Structure/How-to-set-up/Unraid.md
Add a permissions note to Unraid if a user creates folders as root.
Added a permissions note to Unraid if a user creates folders as root.
=> feat(hardlinks): Added a permissions note to Unraid if a user creates folders as root

docs/json/radarr/cf/anime-web-tier-04-official-subs.json, docs/json/radarr/cf/anime-web-tier-05-fansubs.json, docs/json/sonarr/cf/anime-web-tier-04-official-subs.json, docs/json/sonarr/cf/anime-web-tier-05-fansubs.json
Since Some-Stuffs is not official subs, move from tier 04 to tier 05 (fansubs)
Just move it
=> feat(starr-anime): Move Some-Stuffs to Anime Web Tier 05

docs/index.md
Fix broken chat shields on the index.md
Fix broken chat shields on the index.md
=> fix(guide): broken shields in the index.md

docs/json/radarr/cf/german-bluray-tier-02.json, docs/json/radarr/cf/german-bluray-tier-03.json, docs/json/radarr/cf/german-lq.json, docs/json/radarr/cf/german-remux-tier-02.json, docs/json/radarr/cf/german-scene.json, docs/json/radarr/cf/german-web-tier-02.json, docs/json/radarr/cf/german-web-tier-03.json, docs/json/sonarr/cf/german-bluray-tier-03.json, docs/json/sonarr/cf/german-microsized.json, docs/json/sonarr/cf/german-remux-tier-02.json, docs/json/sonarr/cf/german-scene.json, docs/json/sonarr/cf/german-web-tier-02.json, docs/json/sonarr/cf/german-web-tier-03.json
=> feat(starr-german): Tier update

docs/Downloaders/NZBGet/Basic-Setup.md, docs/Downloaders/SABnzbd/scripts/index.md, docs/Downloaders/qBittorrent/Basic-Setup.md
=> style(misc): fixed some typos

docs/Downloaders/Deluge/Tips/Unraid-Mover.md, docs/Downloaders/qBittorrent/Tips/How-to-run-the-unRaid-mover-for-qBittorrent.md, includes/downloaders/mover-workflow.md
Added a description of what the mover script does +  Mover Tuning tips
Added a description of what the mover script does +  Mover Tuning tips
=> feat(downloaders): Added a description of what the mover script does +  Mover Tuning tips

docs/Radarr/radarr-setup-quality-profiles-german-en.md, docs/Sonarr/sonarr-setup-quality-profiles-german-en.md
Fixes https://github.com/TRaSH-Guides/Guides/issues/2376
=> fix(starr-german): Add german audio block to sonarr and radarr HD remux profiles

docs/json/radarr/cf/lq.json
Fix #2395 
Add `AOC` to `LQ` CF.
=> feat(radarr): add AOC to LQ

docs/json/radarr/cf/lq-release-title.json
Update the Radarr LQ Release Titles with releases that are low quality but are labeled as high quality with a note file
~~Add `HDHUB4U` as a possible match to the Radarr LQ Release Title json~~
~~Add `READNFO` as a possible match to the Radarr LQ Release Title json~~
Add `READ NOTE` & `READ.NOTE` as a possible match to the Radarr LQ Release Title json
=> feat(radarr): Add READ NOTE to Radarr lq-release-title.json
